### ISSUE TITLE
Desktop notifications no longer work

### ISSUE THREAD

**Issue by cattenbb** [sindresorhus/caprine#381] opened 2018-01-29 15:28 UTC
When I enable it, a while later I double check it and it is unmarked again.

**Comment by bfred-it** [comment] 2018-02-01 05:05
Same for me, 10.13.2

I resorted to the icon bounce:

<img width="282" alt="icon bounce" src="https://user-images.githubusercontent.com/1402241/35661982-351e7b48-0748-11e8-870a-064e0b15362d.png">

**Comment by bfred-it** [comment] 2018-02-01 05:06
Actually a duplicate of #369

**Closed** 2018-03-09 05:37 UTC
