### ISSUE TITLE
Regression - increase text size/decrease text size not working

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#1494] opened 2020-12-17 21:30 UTC
I'm stuck at one text size. View -> Increase Text Size and View -> Decrease Text Size don't do anything anymore.

This just started today, so I think it's a regression.

Windows 7.

**Comment by dusansimic** [comment] 2020-12-17 21:55
Duplicate of #1439

**Closed by dusansimic** 2020-12-17 21:55 UTC
