### ISSUE TITLE
Large image preview causes unexpected horizontal scrolling

### ISSUE THREAD

**Issue by AlessandroHardjono** [sindresorhus/caprine#859] opened 2019-04-15 02:19 UTC
I recently just saw an issue about the image preview earlier and would like to point out that this also causes unexpected horizontal scrolling through the chat (using a touchpad), which can get mildly annoying. I am using the linux version of this program, and the horizontal scrolling will only happen when there is a image preview too large. It will also only do the horizontal scroll when it is actually scrolling through the chat (ie it cannot do horizontal scrolling alone).

Thanks in advance.

**Comment by rachelyhe** [comment] 2019-04-21 14:38
> causes unexpected horizontal scrolling through the chat (using a touchpad)

Do you have screenshot examples of this behavior? Also, try adding this commentary to  #851 so it can be tracked from the original issue. 

Duplicate of #851

**Comment by rachelyhe** [comment] 2019-04-21 14:41
Duplicate of #851

**Closed** 2019-11-11 16:32 UTC
Labels: bug, help wanted
