### ISSUE TITLE
Windows - Taskbar icon no longer getting marked when receiving a message

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#1713] opened 2021-09-30 01:09 UTC
Windows - Taskbar icon no longer getting marked when receiving a message. Normally when a message is received, something happens to the taskbar icon. I forget what exactly. Blinks orange, or a little red circle with number, or something. Starting a couple of days ago, nothing happens now.

Windows 7
Caprine 2.54.1

![image](https://user-images.githubusercontent.com/43397938/135369163-e927da4d-3fd2-4bfc-8401-45cf874550fe.png)

**Comment by MineEric64** [comment] 2021-11-21 12:19
same issue on Windows 10 and Caprine 2.55.0

**Comment by lefterisgar** [comment] 2022-08-24 13:03
Closing as duplicate of #1823.

**Closed by lefterisgar** 2022-08-24 13:03 UTC
