### ISSUE TITLE
Dark mode no longer available on Mojave 

### ISSUE THREAD

**Issue by jonny333** [sindresorhus/caprine#1482] opened 2020-12-14 21:02 UTC
![Screenshot 2020-12-14 at 23 03 53](https://user-images.githubusercontent.com/48863056/102135476-b8043c80-3e60-11eb-8b41-5c3b4cd51f32.jpg)
Since Facebook's crash few days ago, Caprine no longer turns dark no matter what. I'm running last version of Mojave (Tried downgrading from the latest version - no change)

**Comment by dusansimic** [comment] 2020-12-14 22:15
Duplicate of #1439

**Closed by dusansimic** 2020-12-14 22:15 UTC
