### ISSUE TITLE
dark mode didn't work

### ISSUE THREAD

**Issue by Dontageme** [sindresorhus/caprine#1451] opened 2020-11-21 14:43 UTC
---

Caprine 2.41.1
Electron 7.1.1
win32 10.0.18363
Locale: zh-TW

**Comment by mobaradev** [comment] 2020-11-21 15:35
I have same issue, my eyes really asking where is dark mode

**Comment by Syndamia** [comment] 2020-11-21 19:06
Probably the same problem as #1450 and #1447.

**Comment by dusansimic** [comment] 2020-11-21 20:52
Duplicate of #1439

**Closed by dusansimic** 2020-11-21 20:52 UTC
