### ISSUE TITLE
Caprine Version 2.51.1 (2.51.1) Dark Mode

### ISSUE THREAD

**Issue by listingpro** [sindresorhus/caprine#1497] opened 2020-12-18 06:21 UTC
Caprine doesn't recognize system appearance (set to dark) OR Dark mode. a relaunch appears to display dark mode for a moment then turns white when the UI loads. also doesn't save unchecked setting for show menu bar icon, every computer reboot displays menu bar icon until display menu bar mode is clicked in menu bar icon dropdown.

---

Caprine 2.51.1
Electron 10.1.5
darwin 19.6.0
Locale: en-US

**Comment by dusansimic** [comment] 2020-12-18 08:04
Duplicate of #1439

**Closed by dusansimic** 2020-12-18 08:04 UTC
