### ISSUE TITLE
Weird clipboard capturing for Paste when not actually in focus

### ISSUE THREAD

**Issue by z-ax** [sindresorhus/caprine#262] opened 2017-07-25 21:26 UTC
The issue: when Caprine is not in focus, sometimes it's input field still receives clipboard (via Cmd+V).
And this is fixed only when I make Caprine in focus and then switch to another app again.

I'm still not sure about the steps, but it happened several times in last couple of weeks already.
Like I'm in another chat or browser, writing a message, then press Cmd+V and like nothing happens. But if Caprine window is open but not in focus I see the clipboard (like a link I copied from browser) goes there all those attempts.

Kinda weird stuff, I'd say.

Caprine 2.5.0.
macOS 10.12.6.

**Comment by MarceI** [comment] 2017-07-26 22:59
Dupe of #258.

**Comment by sindresorhus** [comment] 2017-07-27 00:47
Duplicate of #258.

**Closed by sindresorhus** 2017-07-27 00:47 UTC

**Comment by sindresorhus** [comment] 2017-07-27 01:04
New release is out that disables the problematic code: https://github.com/sindresorhus/caprine/releases/tag/v2.6.0
