### ISSUE TITLE
add Multi-Account login feature 

### ISSUE THREAD

**Issue by shaeinst** [sindresorhus/caprine#1425] opened 2020-10-11 17:45 UTC
how about adding a muli-account login feature? so that i can login into my multi account easily without going to logout option and re login.
this feature would something like this=>
easily login to as many as account user want
easily switch between logged in accounts

**Comment by sindresorhus** [comment] 2020-10-11 19:10
Duplicate of https://github.com/sindresorhus/caprine/issues/176

**Closed by sindresorhus** 2020-10-11 19:10 UTC
