### ISSUE TITLE
Privacy features not working on new design

### ISSUE THREAD

**Issue by luttrellnicholas** [sindresorhus/caprine#1584] opened 2021-03-12 02:34 UTC
when caprine is open and got to the privacy settings there are 3 options and i selected those 3 options. ok, under the File tab there is caprine settings tab and under that is the privacy tab. The 3 settings are block seen indicator, block typing indicator, and block delivery receipts.
I checked all 3 but they dont work. My wife is using an iphone 12 pro max, and can see all of those. ---

Caprine 2.52.1
Electron 10.1.5
linux 5.4.0-67-generic
Locale: en-US

**Comment by AggelosM** [comment] 2021-03-16 19:56
This is an ongoing [issue](https://github.com/sindresorhus/caprine/issues/1503). You can fund it here https://issuehunt.io/r/sindresorhus/caprine/issues/1503

**Comment by dusansimic** [comment] 2021-07-31 09:32
Duplicate of #1503

**Closed by dusansimic** 2021-07-31 09:32 UTC
Labels: bug, help wanted
