### ISSUE TITLE
Messenger does not update nor show new message notifications after random period

### ISSUE THREAD

**Issue by dodancs** [sindresorhus/caprine#898] opened 2019-05-11 17:53 UTC
Launch the app. Leave it running and occasionaly reply to messages. After a while people start calling me and my friends to tell me that I did not read their message. I then refresh the client using Ctrl+R and it shows the new messages... This is completely unusable. Please fix.

---

Caprine 2.31.0
Electron 5.0.0
win32 10.0.17763
Locale: en-US

**Comment by marcus13345** [comment] 2019-05-12 21:06
this is an issue for me as well, here are my specs: 

Caprine 2.23.0
Electron 3.0.12
win32 10.0.17134
Locale: en-US

**Comment by ashtonx** [comment] 2019-05-14 11:41
Same Issue. Stuff arrives on phone without problem.

Caprine 2.30.2
Electron 4.1.4
linux 5.0.13-arch1-1-ARCH
Locale: en-US

**Comment by pkuczynski** [comment] 2019-05-15 09:47
I am also experiencing the same issue :(

Caprine 2.31.0
macOS 10.14.4

**Comment by pkuczynski** [comment] 2019-05-25 18:08
Duplicate of #893?

**Comment by Nawor3565** [comment] 2019-05-29 21:52
Here too

Caprine 2.31.0
Electron 5.0.0
win32 10.0.17763
Locale: en-US

**Comment by jeremyclement** [comment] 2019-06-26 03:08
Same for me

**Comment by realtaras** [comment] 2019-07-10 11:04
Yep, I have this issue too.

Version 2.33.1 (2.33.1.1510)
MacOS: 10.14.5

**Comment by lotus42** [comment] 2019-07-29 01:20
Also have this issue.

Version 2.34.0 (2.34.0.1549)
MacOS: 10.14.5

**Comment by Spounka** [comment] 2022-09-18 10:12
same here, Arch Linux
Version: 2.56.1-2
uname -a: Linux spounka-pc 5.19.9-arch1-1 SMP PREEMPT_DYNAMIC Thu, 15 Sep 2022 16:08:26 +0000 x86_64 GNU/Linux

**Comment by dusansimic** [comment] 2023-05-06 16:40
Stale and can't reproduce

**Closed by dusansimic** 2023-05-06 16:40 UTC
