### ISSUE TITLE
Caprine forgets settings on restart

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#1371] opened 2020-05-31 23:35 UTC
For example, I went to File -> Caprine Settings -> check "Mute Notifications". When I restarted Caprine, this setting was back to unchecked.

Consider having Caprine save its settings somewhere, and keep these settings between program restarts.

![2020-05-31_163500](https://user-images.githubusercontent.com/43397938/83365412-c07da580-a35c-11ea-9156-7dbc04637583.png)

---

Caprine 2.46.0
Electron 8.2.5
win32 6.1.7601 (Windows 7)
Locale: en-US

**Comment by timhor** [comment] 2020-06-02 06:07
Duplicate of #1334

**Closed** 2020-10-30 21:04 UTC
