### ISSUE TITLE
App reloads and background turns whiteish when switching chats

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/caprine#737] opened 2019-01-20 13:17 UTC
![2019-01-20 14 10 19](https://user-images.githubusercontent.com/10532611/51439602-2532e580-1cbd-11e9-9b7f-cf78312f3fd7.gif)

I need to quit the app and restart it to restore the background color (reloading does not help).

This happens maybe 50% of times I switch chats to. Sometimes it seems like some chats always work fine while others always reload, then suddenly the "working" chats show the same behaviour.

Disabling vibrancy makes the background color not change but the app still reloads:

![2019-01-20 14 12 33](https://user-images.githubusercontent.com/10532611/51439633-77740680-1cbd-11e9-81d3-881ae918e6a5.gif)

There is also a significant delay between clicking and the app reloading with the right chat selected, which makes the app very unpleasant to use.

There are no logs in the console.

**Comment by CvX** [comment] 2019-01-20 14:38
The background color issue is tracked in #712.

Messenger reloading itself on conversation change - that I haven't seen before. 😮 Doesn't happen with any of my conversations.
Could you check if Messenger also reloads itself when used via https://messenger.com?

**Comment by felixfbecker** [comment] 2019-01-20 14:39
> Could you check if Messenger also reloads itself when used via messenger.com?

It doesn't

**Comment by CvX** [comment] 2019-01-20 14:52
Alright then. You can find out what triggers it in Caprine:

- open DevTools
- go to Sources tab
- in the "Event Listener Breakpoints" select "beforeunload" in the "Load" section
- then click on a conversation that causes a reload

You should have a Call Stack that might tell us what's up.

**Comment by bromarius** [comment] 2019-02-16 20:01
I can confirm having the exact same issue, only it started about 10 days ago

**Comment by aleminopuy** [comment] 2019-02-20 19:33
Yup. Having the same issue over here. Also started quite recently.

**Comment by aleminopuy** [comment] 2019-02-20 19:35
> Alright then. You can find out what triggers it in Caprine:
> 
> * open DevTools
> * go to Sources tab
> * in the "Event Listener Breakpoints" select "beforeunload" in the "Load" section
> * then click on a conversation that causes a reload
> 
> You should have a Call Stack that might tell us what's up.

Maybe this is a n00b question, but where do I enable DevTools in Caprine to get this info?

**Comment by CvX** [comment] 2019-02-20 21:36
That's a good, especially since DevTools aren't an option in the menu!
The keyboard shortcut is the same as in [Chrome](https://developers.google.com/web/tools/chrome-devtools/shortcuts):

* `Command+Option+I` on macOS
* `F12` or `Control+Shift+I` on Windows and Linux

**Comment by bromarius** [comment] 2019-02-26 21:35
I don't know if this will help, but here's the Call Stack that was produced when I tried going from one chat to another. It was all in a single line: 

`__d("TimeSliceImpl",["invariant","CallStackExecutionObserver","CircularBuffer","Env","ErrorUtils","FBLoggerImpl","IntervalTrackingBoundedBuffer","WorkerUtils","getReusableTimeSliceContinuation","nullthrows","performanceAbsoluteNow","wrapFunction"],(function(a,b,c,d,e,f,g){__p&&__p();var h=[],i=[],j="key"+Math.random(),k=1,l=!1,m=0,n=1,o=2,p={},q=m,r=new(b("CircularBuffer"))(100),s=0,t=0;c=b("Env").timesliceBufferSize;c==null&&(c=5e3);var u=new(b("IntervalTrackingBoundedBuffer"))(c),v="stackTraceLimit"in Error,w=[],x=[],y=[];function z(){return A(w)}function A(a){return a.length>0?a[a.length-1]:null}function B(a,c){var d={};b("ErrorUtils").applyWithGuard(F,null,[a,c,d]);b("ErrorUtils").applyWithGuard(G,null,[a,c,d]);w.push(a);x.push(c);y.push(d)}function C(a,b,c){h.forEach(function(d){var e=d.onNewContextCreated(z(),b,c);a[d.getBeforeID()]=e})}function D(a,b){h.forEach(function(c){c.onContextCanceled(a,b[c.getBeforeID()])})}function E(a,b,c){i.forEach(function(d){d.onAfterContextEnded(a,b[d.getBeforeID()],c[d.getBeforeID()],a.meta)})}function F(a,b,c){h.forEach(function(d){var e=d.onBeforeContextStarted(a,b[d.getBeforeID()],a.meta);c[d.getBeforeID()]=e})}function G(a,b,c){h.forEach(function(d){var e=d.onAfterContextStarted(a,b[d.getBeforeID()],c[d.getBeforeID()],a.meta);c[d.getBeforeID()]=e})}function H(){__p&&__p();var a=z(),c=A(x),d=A(y);if(a==null||c==null||d==null){b("FBLoggerImpl")("TimeSlice").mustfix("popped too many times off the timeslice stack");l=!1;return}b("ErrorUtils").applyWithGuard(E,null,[a,c,d]);l=!a.isRoot;w.pop();x.pop();y.pop()}var I={PropagationType:{CONTINUATION:0,EXECUTION:1,ORPHAN:2},guard:function(a,c,d){__p&&__p();typeof a==="function"||g(0,3725);typeof c==="string"||g(0,3726);var e=J(d);if(a[j])return a;e.root||I.checkCoverage();var f;l&&(f=z());var h={},i=0,m=void 0,n=b("Env").deferred_stack_trace_rate||0;n!==0&&Math.random()*n<=1&&b("Env").timeslice_heartbeat_config&&b("Env").timeslice_heartbeat_config.isArtilleryOn&&d&&d.registerCallStack&&(m=b("ErrorUtils").normalizeError(new Error("deferred execution source")));var o={cancel:function(){o.invoked||b("ErrorUtils").applyWithGuard(D,null,[c,h])},tokens:[],invoked:!1};n=function(){__p&&__p();var d=b("performanceAbsoluteNow")(),g,j=k++,n={contextID:j,name:c,isRoot:!l,executionNumber:i++,meta:e,absBeginTimeMs:d};o.invoked||(o.invoked=!0,o.tokens.length&&(o.tokens.forEach(function(a){delete p[a]}),o.tokens=[]));B(n,h);if(f!=null){var q=!!e.isContinuation;f.isRoot?(n.indirectParentID=f.contextID,n.isEdgeContinuation=q):(n.indirectParentID=f.indirectParentID,n.isEdgeContinuation=!!(q&&f.isEdgeContinuation))}var r=b("WorkerUtils").isWorkerContext();l=!0;try{if(!n.isRoot||r)return a.apply(this,arguments);else{var s="TimeSlice"+(c?": "+c:"");g=b("ErrorUtils").applyWithGuard(a,this,[].concat(Array.prototype.slice.call(arguments)),null,s,{deferredSource:m});return g}}finally{var v=z();if(v==null)b("FBLoggerImpl")("TimeSlice").mustfix("timeslice stack misaligned, not logging the block"),l=!1;else{var w=v.isRoot,x=v.contextID,y=v.indirectParentID,A=v.isEdgeContinuation,C=b("performanceAbsoluteNow")();v.absEndTimeMs=C;if(w&&d!=null){t+=C-d;var D=babelHelpers["extends"]({begin:d,end:C,id:x,indirectParentID:y,representsExecution:!0,isEdgeContinuation:f&&A,guard:c},e,a.__SMmeta);u.pushElement(D)}H()}}};n=n;n[j]=o;b("ErrorUtils").applyWithGuard(C,null,[h,c,e]);return n},copyGuardForWrapper:function(a,b){a&&a[j]&&(b[j]=a[j]);return b},cancel:function(a){a=a?a[j]:null;a&&!a.invoked&&(a.cancel(),a.tokens.forEach(function(a){delete p[a]}),a.invoked=!0)},cancelWithToken:function(a){p[a]&&I.cancel(p[a])},registerForCancelling:function(a,b){a&&(b[j]&&(p[a]||(b[j].invoked||(p[a]=b,b[j].tokens.push(a)))))},inGuard:function(){return l},checkCoverage:function(){var a;if(q!==o&&!l){v&&(a=Error.stackTraceLimit,Error.stackTraceLimit=50);var c=new Error("Missing TimeSlice coverage");v&&(Error.stackTraceLimit=a);q===n&&Math.random()<s?b("FBLoggerImpl")("TimeSlice").catching(c).debug("Missing TimeSlice coverage"):q===m&&b("nullthrows")(r).write(c)}},setLogging:function(a,c){if(q!==m)return;s=c;a?(q=n,b("nullthrows")(r).read().forEach(function(a){Math.random()<s&&b("FBLoggerImpl")("TimeSlice").catching(a).warn("error from logging buffer")})):q=o;b("nullthrows")(r).clear();r=void 0},getContext:function(){return z()},getTotalTime:function(){return t},getGuardedContinuation:function(a){return I.guard(function(a){for(var b=arguments.length,c=new Array(b>1?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];return a.apply(this,c)},a,{propagationType:I.PropagationType.CONTINUATION})},getReusableContinuation:function(a){return b("getReusableTimeSliceContinuation")(I,j,a)},getPlaceholderReusableContinuation:function(){var a=function(a){return a()};a.last=a;return a},getGuardNameStack:function(){return w.map(function(a){return a.name})},registerExecutionContextObserver:function(a){__p&&__p();var b=!1;for(var c=0;c<h.length;c++)if(h[c].getBeforeID()>a.getBeforeID()){h.splice(c,0,a);b=!0;break}b||h.push(a);for(var c=0;c<i.length;c++)if(i[c].getAfterID()>a.getAfterID()){i.splice(c,0,a);return}i.push(a)},catchUpOnDemandExecutionContextObservers:function(a){for(var b=0;b<w.length;b++){var c=w[b],d=x[b],e=y[b]||{};d=a.onBeforeContextStartedWhileEnabled(c,d[a.getBeforeID()],c.meta);e[a.getBeforeID()]=d;y[b]=e}},getBuffer:function(){return u}};function J(a){__p&&__p();var b={};a&&a.propagateCounterAttribution!==void 0&&(b.propagateCounterAttribution=a.propagateCounterAttribution);a&&a.root!==void 0&&(b.root=a.root);switch(a&&a.propagationType){case I.PropagationType.CONTINUATION:b.isContinuation=!0;b.extendsExecution=!0;break;case I.PropagationType.ORPHAN:b.isContinuation=!1;b.extendsExecution=!1;break;case I.PropagationType.EXECUTION:default:b.isContinuation=!1,b.extendsExecution=!0}return b}b("Env").sample_continuation_stacktraces&&I.registerExecutionContextObserver(b("CallStackExecutionObserver"));b("wrapFunction").setWrapper(I.guard,"entry");a.TimeSlice=I;e.exports=I}),3);`

**Comment by bromarius** [comment] 2019-02-27 16:16
huh, issue seems to be fixed now! When I opened up the application this morning, it doesn't appear to reload every time I press on a new conversation (ie back to normal)! I don't know if it was a result of what was on the Call Stack, but regardless, thank you!

**Comment by CvX** [comment] 2020-01-22 10:58
#1250 fixed the white background issue after refresh.

And if the "refresh on chat selection" happens again and is reproducible, it'll be best to open a new issue where we can try to debug it. 🙂

**Closed by CvX** 2020-01-22 10:58 UTC
