### ISSUE TITLE
Multiple settings no longer work on macOS 11.0.1

### ISSUE THREAD

**Issue by thagorastos** [sindresorhus/caprine#1456] opened 2020-12-01 08:48 UTC
In the latest version of macOS Big Sur settings as the light/dark theme, vibrancy, show hidden messages (and probably more) do not have any effect for the last two versions of Caprine. 

Maybe fb decided to make things harder for developers since they probably want to promote their desktop version of their app. Who knows?

---

Caprine 2.51.2
Electron 10.1.5
darwin 20.1.0
Locale: en-GB

**Comment by dusansimic** [comment] 2020-12-01 08:50
Duplicate of #1439

**Closed by dusansimic** 2020-12-01 08:50 UTC
