### ISSUE TITLE
Pictures don't show when they are being clicked on in a conversation

### ISSUE THREAD

**Issue by atleta** [sindresorhus/caprine#1827] opened 2022-04-26 12:19 UTC
Pictures don't show when they are being clicked on in a conversation. All I see is a blank (white) page.

![Selection_01993](https://user-images.githubusercontent.com/6267837/165298046-5db5ed71-77e5-4d56-aa76-5870f934d93d.png)

![Messenger_00001](https://user-images.githubusercontent.com/6267837/165298102-36490c61-04f9-472b-879c-a42e79ae1f37.png)

Note that this also happened with the previous version I had (I've just uprgaded from 2.55.2)

---

Caprine 2.55.4
Electron 10.4.7
linux 5.4.0-109-generic
Locale: en-US
OS: Ubuntu 20.04

**Comment by JoelFeiner** [comment] 2022-04-26 15:07
Same problem for me. It's been this way for a number of versions.

**Comment by lefterisgar** [comment] 2022-04-26 19:57
As a temporary solution you could try using [my fork](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3).

**Comment by JoelFeiner** [comment] 2022-04-26 20:19
> As a temporary solution you could try using [my fork](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) which contains the patch.

Thank you! Could you make a snap build? I have all my settings associated with snap.

**Comment by lefterisgar** [comment] 2022-04-26 20:23
Oh! Even though I use Ubuntu I have no idea about how snap works. It is just slow for me. :(
You could try locating the Caprine directory inside .snap directory (I think) and then copying its contents to ~/.config/Caprine.

**Comment by profucius** [comment] 2022-04-27 15:25
This was happening one or two weeks ago, then there was a hotfix released, which resolved the issue.

Now the issue is occurring again, same as before, click an image and the whole window is blank.

**Comment by lefterisgar** [comment] 2022-04-27 19:18
@profucius Which version of Caprine do you currently have? If it's 2.55.4 then it doesn't have the patch.

**Comment by TheRolf** [comment] 2022-04-29 08:23
Same issue, pressing F5 solves it for me, but it is quite tedious to do all the time.
(Also "forward" and other context menus do not work for a while, might be related, but I'm making an issue for this.)

**Comment by lefterisgar** [comment] 2022-04-29 08:25
@TheRolf Just try the fork and post the results here.

**Comment by TheRolf** [comment] 2022-04-29 08:27
@lefterisgar Just did, works like a charm! Fixes both the pictures and the menu.

**Comment by lefterisgar** [comment] 2022-04-29 09:09
That's nice!

**Comment by TheRolf** [comment] 2022-05-03 07:14
@lefterisgar I made that comment too early; after closing and re-opening the app, it requires a new login every time. Maybe some cookie/session issue of the fixed version?

**Comment by lefterisgar** [comment] 2022-05-03 10:52
Well, I'm not sure. No issues for me whatsoever. Try deleting the Caprine directory:
`$ rm -rf ~/.config/Caprine`

See if that helps.

**Comment by jlatusek** [comment] 2022-05-06 06:20
I've tried deleting the Caprine directory, and that didn't help me.

**Comment by KiM-stud** [comment] 2022-05-06 07:15
Tried the fork. Works so far  without a hitch. Good job and thank you!

**Comment by lefterisgar** [comment] 2022-05-06 13:47
@jlatusek Go to Help -> About Caprine. Which version does it show you have?

**Comment by lefterisgar** [comment] 2022-05-06 13:47
> Tried the fork. Works so far without a hitch. Good job and thank you!

Really appreciate your kind words!

**Comment by MarsRon** [comment] 2022-05-07 13:34
> As a temporary solution you could try using [my fork](https://github.com/lefterisgar/caprine/releases) which contains the patch.

Thank you very much for the patch! It's working well on Windows 10, until...

Caprine auto updates to the latest bugged version from `sindresorhus/caprine` everytime I start it up. I have to manually delete `C:\Users\MarsRon\AppData\Local\caprine-updater` each startup to stop the auto updater. I tried making the folder read-only, but Caprine could still download the bugged version and update it the next time I start up Caprine.

Any ways to stop the auto updates? Thanks.

**Comment by lefterisgar** [comment] 2022-05-07 18:30
> > As a temporary solution you could try using [my fork](https://github.com/lefterisgar/caprine/releases) which contains the patch.
> 
> Thank you very much for the patch! It's working well on Windows 10, until...
> 
> Caprine auto updates to the latest bugged version from `sindresorhus/caprine` everytime I start it up. I have to manually delete `C:\Users\MarsRon\AppData\Local\caprine-updater` each startup to stop the auto updater. I tried making the folder read-only, but Caprine could still download the bugged version and update it the next time I start up Caprine.
> 
> Any ways to stop the auto updates? Thanks.

Thank you so much for the detailed bug report! Being a Linux user I didn't even realize Caprine has a built-in updater. I'm surprised that you are the first person reporting it.

In any case, I have issued another release which (hopefully) fixes the issue. I'm only testing on a VM so expect issues with this update.

**Comment by lefterisgar** [comment] 2022-05-07 20:48
> This was happening one or two weeks ago, then there was a hotfix released, which resolved the issue.
> 
> Now the issue is occurring again, same as before, click an image and the whole window is blank.

@profucius We have found the cause! Now update the fork to the latest version and you should be okay. Caprine probably was auto-updated. Based on that you are probably a Windows user.

**Comment by meme1255** [comment] 2022-05-07 21:31
> 

Is there a version of fork for macOS? If not, I don't mind building from the source, however, some additional instructions (dependencies) would be handy to have. Thanks!

**Comment by lefterisgar** [comment] 2022-05-07 21:46
Unfortunately you can't create a build for macOS if you don't have a Mac (which I obviously don't) so you are on your own :( . I think that by running `node_modules/.bin/electron-builder -m` you might get somewhere. Just clone the repo and try it.

**Comment by MarsRon** [comment] 2022-05-08 15:34
> > > As a temporary solution you could try using [my fork](https://github.com/lefterisgar/caprine/releases) which contains the patch.
> > 
> > 
> > Thank you very much for the patch! It's working well on Windows 10, until...
> > Caprine auto updates to the latest bugged version from `sindresorhus/caprine` everytime I start it up. I have to manually delete `C:\Users\MarsRon\AppData\Local\caprine-updater` each startup to stop the auto updater. I tried making the folder read-only, but Caprine could still download the bugged version and update it the next time I start up Caprine.
> > Any ways to stop the auto updates? Thanks.
> 
> Thank you so much for the detailed bug report! Being a Linux user I didn't even realize Caprine has a built-in updater. I'm surprised that you are the first person reporting it.
> 
> In any case, I have created another release which (hopefully) fixes the issue. I'm only testing on a VM so expect issues with this update.

Thank you very much for patch and also the quick response, the updater is working correctly now. Really appreciate your help!

**Comment by drewclauson** [comment] 2022-05-10 19:48
> Is there a version of fork for macOS? If not, I don't mind building from the source, however, some additional instructions (dependencies) would be handy to have. Thanks!

I was able to clone down the fork, then run this to get it to build and run.  You'll need node installed.

`npm install && npm start`

@lefterisgar The fork fixed the pictures not being shown on macOS!

**Comment by lefterisgar** [comment] 2022-05-11 07:40
That's great! If you want to take it one step further you could also build a dmg. Try this command `node_modules/.bin/electron-builder -m` and it should build one. I couldn't do it because I dont own a Mac, thus can't sign it.

**Comment by frozenpandaman** [comment] 2022-05-16 07:57
@lefterisgar Any chance of a Mac build?

**Comment by lefterisgar** [comment] 2022-05-16 10:16
> @lefterisgar Any chance of a Mac build?

Yay! It's now official!

**Comment by frozenpandaman** [comment] 2022-05-16 10:24
Woohoo!

**Comment by PixsaOJ** [comment] 2022-05-16 18:02
Was there a PR to be merged? Can we get the solution from fork in upstream?

**Comment by lefterisgar** [comment] 2022-05-16 18:20
Yes. The PR has been merged. If you want to keep using my fork, you can do so because I will still be providing updates and other improvements.

**Comment by PixsaOJ** [comment] 2022-05-16 18:23
@lefterisgar Oh, I guess it needed restart after last update.

@atleta Lets close this issue then.

**Comment by ibockowsky** [comment] 2022-05-23 12:39
Hey @lefterisgar! Thanks for your job, I have started to use your fork, but I'm missing dark mode there. :( Could you help me? Just downloaded AppImage, but I was trying to do build it by myself, but dark mode was missing also. X11 + KDE Plasma on Arch LInux

**Comment by lefterisgar** [comment] 2022-05-23 15:47
Hi @ibockowsky and thanks a lot for your feedback! It really seems strange to me as I also use KDE Plasma. I use Kubuntu, but I'm always on a development release with the latest packages. Also dark theme is my preferred option and I can't find any issue with using that. Does dark theme work when you use the official Caprine AppImage? What happens if you clone my repo and run `$ npm start`?

**Comment by ibockowsky** [comment] 2022-05-24 07:26
@lefterisgar Thanks for your reply, it started working by itself... haha

**Comment by lefterisgar** [comment] 2022-05-24 11:52
@ibockowsky That's great news!

**Comment by mquevill** [comment] 2022-06-17 16:08
This issue was fixed in v2.55.5. Please upgrade to a newer version to check that it is resolved.

**Closed** 2022-06-17 16:10 UTC
