### ISSUE TITLE
No popup notifacations on arch linux KDE DE (sound or toast)

### ISSUE THREAD

**Issue by XDM-Inc** [sindresorhus/caprine#1991] opened 2023-02-09 07:48 UTC
im running endeavor os  based on arch and while i have this running i don't get ANY sounds or popups from this app. clicking messenger settings also does not work. I also notice that in my system settings > notifications menu this app dose not even show up there.

**Comment by RobDean69** [comment] 2023-02-15 20:13
I'm running Opensuse tumbleweed KDE and have the same issue. Caprine is installed via flatpak if that makes a difference.

**Comment by dusansimic** [comment] 2023-02-15 22:10
Duplicate of #1825

**Closed by dusansimic** 2023-02-15 22:10 UTC
