### ISSUE TITLE
dark mode, and other features not working

### ISSUE THREAD

**Issue by robinsrk** [sindresorhus/caprine#1484] opened 2020-12-16 06:53 UTC
today after logging in, I found some errors, like dark mode, notifications, custom styles and some more features not working. tried reinstalling and fresh installing, but no luck.

**Comment by Pix13** [comment] 2020-12-16 07:20
I got the same issue, i think something changed on the facebook side

**Comment by dusansimic** [comment] 2020-12-16 08:10
Duplicate of #1439

**Closed by dusansimic** 2020-12-16 08:10 UTC
