### ISSUE TITLE
Feature request: Backup of conversations to guard against accidental deletion 

### ISSUE THREAD

**Issue by brandonnoltemulesoft** [sindresorhus/caprine#828] opened 2019-03-22 17:11 UTC
I would like to request a feature of automatic backup of conversations to ensure the conversation is recoverable if accidental deletion happens. If this is already a feature please let me know However I am unable to find this feature in any other software.

**Comment by sindresorhus** [comment] 2019-03-23 07:23
Duplicate of #602

**Closed by sindresorhus** 2019-03-23 07:23 UTC
