### ISSUE TITLE
App password login not working?

### ISSUE THREAD

**Issue by flipsticks** [sindresorhus/caprine#491] opened 2018-06-12 04:30 UTC
I prefer not to trust web wrapper applications with my passwords, so I found it unusual that app passwords didn't seem to let me login? 

I tested with another Facebook account and it's real password worked fine first try. Could you please add support for app passwords?

**Comment by sindresorhus** [comment] 2018-07-02 18:09
I think this was fixed by https://github.com/sindresorhus/caprine/commit/69d22e06bcd7ec46433424e8b85e1e127aa2584f and a duplicate of #495. Try the latest version.

**Comment by szmktk** [comment] 2019-01-04 22:36
I also can not authenticate with the second factor (be it TOTP code from authenticator app or u2f key), I'm using Caprine 2.23.0 on arch linux. After providing my credentials I can see the same page I'd see when logging through the browser, but the light on my u2f key does not flash. If I click "Use a different method." button then it opens a browser window instead of continuing in Caprine/Electron window.

I also tried the drill described in  #495 but unfortunately for no avail... is there anything I could do to further help with troubleshooting this issue? I believe there are plenty of users who use MFA and are interested in using Caprine ;)

**Comment by mihalyr** [comment] 2019-11-18 16:43
Just wanted to give this a try and login with app passwords doesn't seem to work in 2.41.1 AppImage. After entering the password I get the error `Please re-enter your password
The password you’ve entered is incorrect. Forgot Password?`

**Comment by plaskowski** [comment] 2020-03-26 11:34
bump.

**Closed** 2022-08-17 15:37 UTC
