### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by srafsan** [sindresorhus/caprine#1706] opened 2021-09-13 12:58 UTC
![image](https://user-images.githubusercontent.com/60515831/133087617-c0508ac0-88ce-47be-b093-c48e14008e27.png)

---

Caprine 2.54.1
Electron 10.1.5
win32 10.0.19043
Locale: en-US

**Comment by dotpointer** [comment] 2021-09-19 17:17
Same here.

Caprine 2.54.1
Electron 7.1.9
Debian GNU/Linux 10 (buster)
Locale: sv-SE

F12 console show this (excluding possibly private stuff and references to minimized `.js` files etc):

```
WebSocket connection to 'wss://gateway.facebook.com/ws/realtime?x-dgw-appid=...&x-dgw-appversion=0&x-dgw-authtype=1%3A0&x-dgw-version=4&x-dgw-uuid=...&x-dgw-tier=prod&x-dgw-loggingid=...&x-dgw-app-stream-group=...' failed: HTTP Authentication failed; no valid credentials available

DevTools failed to load SourceMap: Could not load content for https://www.messenger.com/opt/Caprine/resources/app.asar/node_modules/uri-js/dist/es5/uri.all.js.map: Unknown error

WebSocket connection to 'wss://gateway.facebook.com/ws/realtime?x-dgw-appid=...&x-dgw-appversion=0&x-dgw-authtype=1%3A0&x-dgw-version=4&x-dgw-uuid=...&x-dgw-tier=prod&x-dgw-loggingid=...&x-dgw-app-stream-group=group1' failed: HTTP Authentication failed; no valid credentials available

ErrorUtils caught an error:

Transport could not be initialized

Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
```

**Comment by atleta** [comment] 2021-10-04 16:46
I've just run into this (probably). It happens with the older versions as well. In my case the issue is that the nameservers don't work and thus the app can't connect to facebook. An error message would be nice.

**Comment by dusansimic** [comment] 2021-10-04 21:52
@atleta at this moment Facebook has [some problems](https://downdetector.com/status/facebook-messenger/) so it's expected not to work. It's also usually the fault of Messenger.com and not Caprine. I'll close this since it happens from time to time and the issue authors usually don't close the issues after it starts working again. If there is a real issue with Caprine, open a new issue.

**Closed by dusansimic** 2021-10-04 21:52 UTC

**Comment by atleta** [comment] 2021-10-04 22:17
@dusansimic I know that facebook was havong problems. It was pretty hard not to realize :) And as you can see from my comment, I was fully aware that the app wasn't able to connect due to a DNS failure. (Though I at first thought it was my ISP, it doesn't make a difference.)

The problem we're reporting here (at least what my comment was about) is not that the app wasn't able to connect. It's that it didn't show an error message. So I personally ended up restarting, reloading several times, then upgrading the app. While if it behaved nicely as all apps should, it could have tell me that it can't access FB. (It could even tell the cause, like my browser does.)
