### ISSUE TITLE
"Show message preview in notifications" feature stopped working

### ISSUE THREAD

**Issue by Geryson** [sindresorhus/caprine#1473] opened 2020-12-11 22:33 UTC
After I installed the latest version (manual update, by .deb package), I don't get system notifications when I get new messages.  With this update the whole layout of the app changed also, but I'm not sure if this has any connection to the problem.

One thing I recently tried was disabling an re-enabling this feature in File > Caprine Settings. If this solves the problem, I'll reply under this post.

---

Caprine 2.51.2
Electron 10.1.5
linux 5.4.0-56-generic
Linux Mint 20 Cinnamon (Cinnamon version 4.6.7)
Locale: hu

**Comment by dusansimic** [comment] 2020-12-11 23:38
Since your layout of the Messenger app has changed, I'll flag this as a duplicate of #1439

**Closed by dusansimic** 2020-12-11 23:38 UTC

**Comment by dusansimic** [comment] 2020-12-11 23:40
Duplicate of #1439
