### ISSUE TITLE
Frequently switches to Marketplace window, even when in the background

### ISSUE THREAD

**Issue by Roving1** [sindresorhus/caprine#2187] opened 2024-06-06 13:49 UTC
See the title. 
Open the app, it will switch to Marketplace even if running in the background.

# System Details Report
---

## Report details
- **Date generated:**                              2024-06-06 08:48:58

## Hardware Information:
- **Hardware Model:**                              Framework Laptop
- **Memory:**                                      16.0 GiB
- **Processor:**                                   11th Gen Intel® Core™ i7-1185G7 × 8
- **Graphics:**                                    Intel® Xe Graphics (TGL GT2)
- **Disk Capacity:**                               250.1 GB

## Software Information:
- **Firmware Version:**                            03.19
- **OS Name:**                                     Ubuntu 24.04 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.0-35-generic

---

Caprine-pro 1.0.0
Electron 21.2.0
linux 6.8.0-35-generic
Locale: en-US

**Comment by mquevill** [comment] 2024-06-06 14:17
The "caprine-pro" on Snapcraft is **not** an official release of Caprine, and doesn't even follow the same version numbering as the real package (on this GitHub site). While this may be based off of Caprine, the Electron version used would mean it's from a version before v2.57.2 and will therefore be quite outdated with how often the Messenger site backend changes. It's also not clear what changes (if any) exist between this package and Caprine.

See the actual Snapcraft package here: https://snapcraft.io/caprine (However, the version is also bit out of date due to some issues with snap packaging.)

Duplicate of #2186.

**Closed by mquevill** 2024-06-06 14:17 UTC
