### ISSUE TITLE
picture not viewabe when clicked on

### ISSUE THREAD

**Issue by tolgaerok** [sindresorhus/caprine#1928] opened 2022-10-02 14:18 UTC
picture attachments are not viewable when clicked on

---

Caprine 2.56.1
Electron 20.0.3
linux 5.15.0-48-generic
Locale: en-GB

**Comment by dusansimic** [comment] 2022-10-03 07:26
Duplicate of #1909

**Closed by dusansimic** 2022-10-03 07:26 UTC

**Comment by tolgaerok** [comment] 2022-10-03 14:37
dosnt work. still no view of image

**Comment by dusansimic** [comment] 2022-10-03 15:12
This issue is not closed as solved, it's a duplicate issue.
