### ISSUE TITLE
Tray icon disappears in Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by cement-head** [sindresorhus/caprine#1307] opened 2020-03-18 19:50 UTC
Installed Caprine from deb. Running Untiy 7 (from PPA) on Ubuntu 18.04.4 LTS.  Have "Launch Minimised" checked.  Caprine launches, tray icon/applet shows from a brief moment on status bar and then crashes.

Do you need any debugging?

---

Caprine 2.44.0
Electron 8.0.0
linux 5.3.0-7642-generic
Locale: en-US

**Comment by logxseven** [comment] 2020-03-30 07:44
same problem on Linux mint 19.2 .. any solutions ?

**Comment by jaawerth** [comment] 2020-03-31 18:04
I noticed the same issue with both Caprine and other electron-based apps (Riot, for example) Arch + Cinnamon and did some further digging and found [this upstream electron issue](https://github.com/electron/electron/issues/21445). It appears to be related to electron 8 and its use of StatusNotifier.

I've found some workarounds in [this comment](https://github.com/electron/electron/issues/21445#issuecomment-565710027), and `"System Settings" -> "General" -> "Enable support for indicators"` did fix it for me in Cinnamon, but this is only a workaround and [may cause other issues (see comments)](https://github.com/linuxmint/cinnamon/issues/9176).

It sounds like it's related to the apis/libraries electron 8 is using to show the icons not being supported as widely but I haven't dug in super deep yet. Still,
- @logxseven the fix in Cinnamon will likely work for you as a workaround (I've seen no new problems caused by changing that setting yet, but we'll see)
- @cement-head this might be enough to get you started on finding a Unity fix...

----

@sindresorhus this is definitely an upstream issue but given how popular Caprine is I wouldn't be surprised if you're got the brunt of it, which may intensify once more distros get newer versions, so I figured I'd give you a heads up just in case you want to head off a flood of issues about this with an issue template or something :grin:

**Comment by logxseven** [comment] 2020-03-31 18:44
@jaawerth thank you for your response
unfortunately the solution doesn't work. enabling that option makes the tray icon appear, but you can't click it or interact with it at all.

**Comment by jaawerth** [comment] 2020-03-31 19:51
@logxseven 

Interesting.. did you restart cinnamon? It's working for me and I can even interact with the icon... though it's limited. Single-click only, which pops up a menu with Toggle and Quit options like so:

![Screenshot from 2020-03-31 15-48-56](https://user-images.githubusercontent.com/5314507/78069052-7762a280-7367-11ea-9ce1-d891eac763d8.png)

It does seem to change the behavior of my icons in general, which is probably related to the possible issues mentioned in the Cinnamon issue I linked.

I'm also on Cinnamon 4.4.8, but maybe there's something different about your build than mine, since we're on different distros.

**Comment by logxseven** [comment] 2020-03-31 19:53
@logxseven i did restart cinnamon, and even logged out and in again to be sure.

**Comment by jaawerth** [comment] 2020-03-31 20:02
Hmm.. my guess is that due to the different distros, it's *probably* something on my system that's newer than yours, I'm guessing either electron (I'm on 8.2.0, with Caprine 2.44) or one of the Cinnamon deps. Hard to say before, but I'm guessing the answer will be in either the electron or cinnamon projects. [This issue](https://github.com/linuxmint/cinnamon/issues/9176) is probably a good starting point though, since I don't think this is specific to Caprine.

**Comment by logxseven** [comment] 2020-03-31 20:14
@jaawerth  thank you for your help anyways.
i blame the electron team for this, i don't want to be the a-hole who shits on open source projects, but every time they fix something, they break 10 other things. 
i have submitted a ticket many months ago, and it got close for insufficient information, even though there weren't anymore information needed.
i wish a better more mainstream alternative with a better dev team appears. i'm sick of electron.

**Comment by dotenorio** [comment] 2020-04-02 19:34
See my solution:

https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150

**Closed** 2022-08-05 17:25 UTC
