### ISSUE TITLE
cmd+w functionality

### ISSUE THREAD

**Issue by jedireza** [sindresorhus/caprine#6] opened 2015-09-17 00:24 UTC
Could we make the cmd+w functionality on the Mac not close the app but just close/hide the window?

**Comment by sindresorhus** [comment] 2015-09-17 01:29
I know that's the OS X way, but doesn't make a lot of sense when the app is a single window app. Why do you need this?

**Comment by jedireza** [comment] 2015-09-17 02:01
I've been closing the app instead of just hiding the window. I guess it's muscle memory. The Gitter and Slack apps, although single windows also work this way.

**Comment by sindresorhus** [comment] 2015-09-17 03:07
If you intend to hide it, you should just hide it and not close it then: <kbd>Cmd</kbd> <kbd>H</kbd>

Caprine works like any other single-window apps on OS X: Notes, Reminder, Photos, Contacts, App Store, Photo Booth, FaceTime, Calculator, Dictionary, etc. All of those close the app if you close the window.

**Comment by timche** [comment] 2015-10-20 08:29
+1

In my opinion, Caprine should stay active. It's a chatting application and needs the option to stay active in the background. I'm closing my app windows with `cmd + w` in any other app like Slack or Goofy/ChitChat.

**Comment by sindresorhus** [comment] 2015-10-20 08:41
@timche Other apps doing it wrong is not a good argument. Cmd+H is the standard way of hiding a window. It's kinda amazing that you would rather maintain a fork than learn how to do it correctly...

**Comment by timche** [comment] 2015-10-20 08:56
Can you show me where this rule is written down that this is a wrong approach?

It's just how the majority of apps are handling cmd + w and they are not closing the app at all ... I don't need apps like Notes, Contacts, App Store running frequently in the background so it's okay they close at cmd + w, but when I'm using a chat app, I expect it's not quitting the whole app with cmd + w. I'm not the only one with this expectation.

**Comment by sindresorhus** [comment] 2015-10-20 09:02
> Can you show me where this rule is written down that this is a wrong approach?

What the built-in apps do is the rule in my view. If you can find anything written backing your argument I would be happy to reconsider.

But again, why not just always use Cmd+H and get consistent behaviour instead of Cmd+W which behaves sporadically.

**Comment by timche** [comment] 2015-10-20 09:09
> If you can find anything written backing your argument I would be happy to reconsider.

I can't, it's just my personal experience with other apps I'm using daily.

> But again, why not just always use Cmd+H and get consistent behaviour instead of Cmd+W which behaves sporadically.

Because I'm already get used to cmd + w, which behaves actually consistent except Caprine.

Please don't get me wrong, I'm really happy with Caprine and you did some nice work, because Goofy has a really poor performance. This cmd +w thing is the only point which would make Caprine a perfect Messenger app for OSX in my eyes.

**Comment by sindresorhus** [comment] 2015-10-22 17:13
I need to think about this. If this were to be accepted it would pretty much just be hiding the window on close, so that you would still get notifications while the window is "closed" (hidden). Would be really helpful to see something written in favor of this, though. That would make the decision easier.

**Comment by OakNinja** [comment] 2015-11-03 10:23
The "minimize on quit" behavior is, to me, a school book example of bad UX. There is a workaround; Use the designated minimize/hide functionality. Please do not modify the expected behavior.

**Comment by sindresorhus** [comment] 2015-11-03 10:34
@OakNinja Nobody has mentioned "minimize". It's unclear if you're arguing for or against what's being requested in this issue.

**Comment by OakNinja** [comment] 2015-11-03 11:58
@sindresorhus sorry if I was being unclear, I talked about it behavior in a general fashion. That's why I said minimize/hide. I like when close means close, hide means hide, etc. I don't like when close means hide, hide means close, or any variant of such.

**Comment by timche** [comment] 2015-11-03 12:08
You are getting it wrong.

As I said above, close doesn't mean to close the whole app. There is a difference between close and quit on OS X. On most apps, cmd+w (close) is just **closing the window** (not hide or minimize) and _not_ **quitting the app**. There are exceptions that are quitting the whole app with cmd+w, but these are rare.

**Comment by OakNinja** [comment] 2015-11-03 13:24
@timche that is true for multi-window applications. But even on OSX,  single window applications usually close on close.

**Comment by sindresorhus** [comment] 2015-11-12 10:18
@timche I've thought long and hard about this and decided to accept it if someone does a good pull request. I've noticed that a similar app, Messages.app, is kept open on window close even though it's a single-window app. The implementation should just do this though:

> If this were to be accepted it would pretty much just be hiding the window on close, so that you would still get notifications while the window is "closed" (hidden).

**Comment by timche** [comment] 2015-11-12 10:21
This is a good solution. Thanks @sindresorhus.

**Comment by sindresorhus** [comment] 2015-11-26 06:43
Fixed in 0.4.0: https://github.com/sindresorhus/caprine/releases/tag/0.4.0

**Closed by sindresorhus** 2015-11-26 06:43 UTC
Labels: enhancement, help wanted

**Comment by seriema** [comment] 2015-12-11 07:48
@sindresorhus how do I close the app completely on Windows? I close the window, as that's the only option I have, but the processes stick around until I kill them with the Task Manager.

**Comment by sindresorhus** [comment] 2015-12-11 10:59
@seriema Yeah, I didn't consider Windows when doing this. I use OS X. Seems like https://github.com/sindresorhus/caprine/pull/36 will fix this, right?
