### ISSUE TITLE
Remove/Delete Dead

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1994] opened 2023-02-21 18:53 UTC
As you know the Remove and Delete Buttons are inert. in 257.0.
My  Question is, would reinstalling fix those issues from your experience?

---

Caprine 2.57.0
Electron 21.2.3
win32 6.1.7601
Locale: en-US

**Comment by mirenradia** [comment] 2023-03-03 14:21
I can reproduce this on Fedora Linux 37. Furthermore, clicking on the existing reactions to a message does not work (should display a "Message reactions" popup showing who has reacted to a message and what they have reacted with).

**Comment by dusansimic** [comment] 2023-04-16 16:59
Duplicate of #2004

**Closed by dusansimic** 2023-04-16 16:59 UTC
