### ISSUE TITLE
about is empty

### ISSUE THREAD

**Issue by alekksander** [sindresorhus/caprine#1131] opened 2019-10-22 14:40 UTC
this is ubuntu lts based distro:
https://framapic.org/vC6bbXoqAmi5/Me7FBxQco3Ar.png

**Comment by RDKRACZ** [comment] 2021-04-09 15:54
Still:
![image](https://user-images.githubusercontent.com/43277609/114207440-ab01e080-995c-11eb-9dde-3c57384a5ec7.png)

**Comment by dusansimic** [comment] 2021-04-19 07:56
Duplicate of #1435

**Closed by dusansimic** 2021-04-19 07:56 UTC
