### ISSUE TITLE
No vibrancy mode on macOS 10.13.4 (17E202)

### ISSUE THREAD

**Issue by YannMCX** [sindresorhus/caprine#475] opened 2018-05-27 17:37 UTC
I can't enable Vibrancy Mode
---

Caprine 2.13.1
Electron 2.0.1
darwin x64 17.5.0

**Comment by sindresorhus** [comment] 2018-05-28 01:48
Duplicate of #463

**Closed by sindresorhus** 2018-05-28 01:48 UTC

**Comment by robjtede** [comment] 2018-09-20 13:50
_commenting here since the duplicate issue is locked_

How's support for vibrancy in the now-stable v3 ?
