### ISSUE TITLE
"Something went wrong" when opening Caprine 2.51.2

### ISSUE THREAD

**Issue by orsib78** [sindresorhus/caprine#1481] opened 2020-12-14 14:20 UTC
Hello.

Just installed Caprine 2.51.2 from a deb package on a fresh Pop_OS 20.10. Receiving the following error message when trying to login. I am happy to provide additional log files for developers if they can tell me where can I find them...

![Screenshot from 2020-12-14 15-17-26](https://user-images.githubusercontent.com/20341829/102091967-c9792480-3e1f-11eb-9e49-543f0888f66a.png)

**Comment by matiastonning** [comment] 2020-12-14 15:26
Also getting this on macOS 11.0.1

<img width="912" alt="CleanShot 2020-12-14 at 16 25 34@2x" src="https://user-images.githubusercontent.com/17254337/102099843-085fa800-3e29-11eb-84e8-15551514b1c8.png">

**Comment by dusansimic** [comment] 2020-12-14 16:42
Duplicate of #1474

**Closed by dusansimic** 2020-12-14 16:42 UTC
