### ISSUE TITLE
no notifications

### ISSUE THREAD

**Issue by ForumLiker** [sindresorhus/caprine#582] opened 2018-09-16 11:31 UTC
Hello. On the [deepin](https://www.deepin.org/) desktop, there are no notifications about the incoming message. Icon does not change color in tray, it is always gray.

**Comment by kolinger** [comment] 2018-09-16 13:00
Probably duplicate of #578?

**Comment by sindresorhus** [comment] 2018-10-02 09:47
Duplicate of #578

**Closed by sindresorhus** 2018-10-02 09:47 UTC
