### ISSUE TITLE
Strange view images issues

### ISSUE THREAD

**Issue by yardstudio** [sindresorhus/caprine#1590] opened 2021-03-18 09:27 UTC
I can´t view images in detail windows
I can´t place smile direct to attached image
I can´t resend attached image

[https://i.imgur.com/Df5X5o4.png](url)

---

Caprine 2.52.1
win64 10.0.19042
Locale: sk-SK

Edition	Windows 10 Pro
Version	20H2
Installed on	‎18.‎07.‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by dusansimic** [comment] 2021-03-18 10:28
Duplicate of #1579 and #1587

**Closed by dusansimic** 2021-03-18 10:29 UTC
