### ISSUE TITLE
Can't share pics or videos

### ISSUE THREAD

**Issue by Mystqr4** [sindresorhus/caprine#1862] opened 2022-07-19 14:06 UTC
Is anyone else having trouble sharing pics or videos?

**Comment by mquevill** [comment] 2022-07-21 00:04
What version are you using? There were issues that were fixed in v2.55.5 relating to this issue. However, it may not be completely resolved, since at least one user has reported issues with newer versions (see #1859).

**Comment by lefterisgar** [comment] 2022-08-06 13:15
Possible duplicate of #1859.

**Closed by lefterisgar** 2022-08-06 13:15 UTC
