### ISSUE TITLE
React not working

### ISSUE THREAD

**Issue by megseoh** [sindresorhus/caprine#1598] opened 2021-03-27 15:33 UTC
When I click on 'React' beside a message nothing happens.

Have noticed this quite often recently, & has been fixed by quitting & restarting Caprine. Now it's not working at all on both MacBook Pro 2018 & 2013.

MacOS Big Sur 11.2.2
MacOS High Sierra 10.13.6
Caprine 2.52.2

**Comment by RDKRACZ** [comment] 2021-03-27 17:41
Duplicate of #1579

**Closed** 2021-04-16 07:41 UTC
