### ISSUE TITLE
Can't sync old messages. The input for the pin never appears

### ISSUE THREAD

**Issue by AndrejSavatic** [sindresorhus/caprine#2226] opened 2024-09-07 11:35 UTC
---

Caprine 2.60.1
Electron 29.4.6
linux 6.10.8-arch1-1
Locale: en-US

**Comment by lordgabor** [comment] 2024-10-04 13:34
https://github.com/sindresorhus/caprine/issues/2167#issuecomment-2089402948

> A temporary workaround: If you access the developer tools via F12, you can edit the main <html> element to remove the hide-preferences-window class from the list within class="...".

**Comment by mquevill** [comment] 2024-11-29 22:49
Duplicate of #2167.

**Closed by mquevill** 2024-11-29 22:49 UTC
