### ISSUE TITLE
The app has no icons

### ISSUE THREAD

**Issue by wildcard-f8** [sindresorhus/caprine#1395] opened 2020-08-03 05:18 UTC
I installed the latest version and the app doesn't any icon. I'm on Ubuntu 20.04.
![Screenshot from 2020-08-03 13-17-38](https://user-images.githubusercontent.com/51791246/89148201-bd38ad00-d58b-11ea-846e-db38578be8cc.png)

**Comment by dusansimic** [comment] 2020-08-03 10:40
@wildcard-f8 how did you install Caprine. With .deb package, snap or appimage?

**Comment by wildcard-f8** [comment] 2020-08-03 10:58
@dusansimic I installed the .deb package.

**Comment by BananaManCJ** [comment] 2020-08-04 10:29
This is a duplicate of #1213

**Comment by wildcard-f8** [comment] 2020-08-05 04:35
awsome! it worked! thanks!

**Closed** 2020-08-05 04:35 UTC
