### ISSUE TITLE
App "content" is just a white window

### ISSUE THREAD

**Issue by jprobichaud** [sindresorhus/caprine#1384] opened 2020-06-22 14:28 UTC
Since the last week or so, Caprine just display a white window.  I can see the menus, but the actual content is only a white window.  I've nuke my ~/.config/Caprine and restarted, but nothing seems to do.

---

Caprine 2.47.0
Electron 9.0.4
linux 5.7.2-arch1-1
Locale: en-US

**Comment by mquevill** [comment] 2020-06-23 01:51
What method of installation did you use? (Snap, .deb, etc.)

**Comment by xXorAa** [comment] 2020-08-08 22:25
I am seeing this on the snap install on Ubuntu 20.04.1

snap list
Name               Version                     Rev   Tracking       Publisher     Notes
caprine            2.48.0                      38    latest/stable  sindresorhus  -

**Comment by jprobichaud** [comment] 2020-08-08 23:36
I get that too, using ArchLinux AUR package

**Comment by xXorAa** [comment] 2020-08-18 15:12
Ok for me this turned out to be /etc/resolv.conf being linked to somewhere the snap is not allowed to access (naughty VPNs). So this is no longer an issue for me!

**Comment by dusansimic** [comment] 2020-10-29 23:27
Duplicate of #1404

**Closed by dusansimic** 2020-10-29 23:27 UTC
