### ISSUE TITLE
Crashing upon start

### ISSUE THREAD

**Issue by vikr01** [sindresorhus/caprine#769] opened 2019-02-11 22:46 UTC
Sometimes when launching Caprine, it crashes with stacktrace:

```
Uncaught Exception:
TypeError: Cannot read property 'show' of undefined
    at App.app.on (/Applications/Caprine.app/Contents/Resources/app.asar/index.js:408:13)
    at App.emit (events.js:182:13)
```

The error still occurs when trying to launch Caprine again, but after restarting the computer seems to work. I'll see if I can find how to reproduce it.

I updated to macOS Mojave 10.14.3 last night and never had this error before then, so that probably has something to do with it.

**Comment by AreD** [comment] 2019-02-12 14:01
I have the same error, if I have closed the window and press the icon again:
`Uncaught Exception:
TypeError: Cannot read property 'show' of undefined
    at App.electron_1.app.on (/Applications/Caprine.app/Contents/Resources/app.asar/source/index.ts:441:13)
    at App.emit (events.js:182:13)`

But if I select "Quit" in dock menu I have another error:
`Uncaught Exception:
TypeError: Cannot read property 'getNormalBounds' of undefined
    at App.electron_1.app.on (/Applications/Caprine.app/Contents/Resources/app.asar/source/index.ts:446:43)
    at App.emit (events.js:182:13)`

OS El Capitan 10.11.6
Caprine 2.28.0.1220

**Comment by Sylk** [comment] 2019-02-18 17:25
@vikr01 is this still occurring?

**Comment by vikr01** [comment] 2019-02-18 17:38
@Sylk Nope, only occurred that day.

**Comment by Sylk** [comment] 2019-02-18 17:51
Alright, well let's close this down.

**Comment by Sylk** [comment] 2019-02-18 17:52
@AreD is the issue gone for you?

**Comment by AreD** [comment] 2019-02-18 17:54
@Sylk yep, the issue is gone for me

**Closed** 2019-02-18 23:14 UTC
