### ISSUE TITLE
"Synch now" button does not work.

### ISSUE THREAD

**Issue by Roving1** [sindresorhus/caprine#2171] opened 2024-05-01 16:02 UTC
The app informs me messages are missing and to "Synch now." However, that button does not work. I assume this connected with the end-to-end encryption.

---

Caprine 2.59.3
Electron 25.9.8
linux 6.5.0-28-generic
Locale: en-US

**Comment by mquevill** [comment] 2024-05-02 00:35
Duplicate of #2167

**Closed by mquevill** 2024-05-02 00:35 UTC
