### ISSUE TITLE
Block Seen Indicator not working

### ISSUE THREAD

**Issue by CarterSnich** [sindresorhus/caprine#1917] opened 2022-09-20 07:52 UTC
I'm using 2.56.1, and the Block Seen Indicator seems to be not working on Manjaro KDE. Other people still can see that I have seen the message.

**Comment by ks202005** [comment] 2022-09-21 08:26
This issue is present for me as well on Windows.

**Comment by dusansimic** [comment] 2022-09-22 07:30
Duplicate of #1503

**Closed by dusansimic** 2022-09-22 07:30 UTC
