### ISSUE TITLE
Feature Request: MSIX / Windows Store

### ISSUE THREAD

**Issue by Saijin-Naib** [sindresorhus/caprine#1666] opened 2021-07-16 15:38 UTC
I'd love to see Caprine bundled in MSIX for the Windows Store.

It would provide a similar UX to flatpak and other package-managed versions as on Linux, with similar sandboxing benefits as well.

You could even make an optional Donation/purchase DLC so that users may support it.

**Comment by dusansimic** [comment] 2021-07-21 08:15
Duplicate of #315

**Closed by dusansimic** 2021-07-21 08:15 UTC
