### ISSUE TITLE
Caprine starts in tray on Linux

### ISSUE THREAD

**Issue by ftpd** [sindresorhus/caprine#1613] opened 2021-04-18 22:44 UTC
I'm trying to run Caprine on void linux in vmware fusion's vm (host os: macOs Big Sur - Caprine works fine there). After trying to run appimage, nothing happens - I've tried running it from inside terminal, to see any output and errors, but it's just nothig. AppImage gets mounted and that's all.

Any ideas? Can it be because it's inside a VM? Other appimages works, there is no resource problem either (I know electron apps like memory, but I have almost all of my 4GB free).

**Comment by G-P-L** [comment] 2021-04-18 23:49
Hi, I think I know the problem. Caprine also won't launch in Arch in the last few days with the following message:
`/usr/lib/electron/electron: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory`
Arch is a rolling distro - like Void - and it had icu package update few days ago which is causing the issue.

**Comment by dusansimic** [comment] 2021-04-19 07:53
@ftpd could you please check if `caprine` process is running in the background. You can check that using applications like top, htop or any other process monitor. I suspect the problem is that for some odd reason Caprine is started hidden (in tray). What you could do to test that out is to open two terminal sessions and start it two times. First should just execute and output nothing and the second should exit automatically but it should also display Caprine window since if you run it while it's already running, it will just open the already running process.

@G-P-L I believe that that is unrelated to this issue since the original report says that there are no errors. Also since that is probably a problem with electron package on Arch or Caprine package on Arch, it's unrelated to us because we can't fix it from here. It should be reported on Arch website.

**Comment by ftpd** [comment] 2021-04-19 08:34
@dusansimic processes were there since my first try.
Your workaround worked and now when I'm starting the app (from dmenu) it shows window as expected. I will add some systray patch to my dwm to monitor it anyway.

Thanks, the 'problem' (imaginary one) is now solved.

**Comment by dusansimic** [comment] 2021-04-19 10:04
> Thanks, the 'problem' (imaginary one) is now solved.

Well in my opinion this is a problem and a very real one 😅. I'd like to leave this issue open and rename it to something more descriptive of the issue so it could be tracked.

**Comment by mquevill** [comment] 2021-06-07 20:15
In my testing, this seems to come from starting "fresh", whether it is a new install of Caprine or you are currently logged out. I am able to replicate the issue by simply logging out, closing out of Caprine entirely, and reopening.

I believe Caprine hangs on the following line and cannot actually get to the stage of opening the window:
https://github.com/sindresorhus/caprine/blob/9667e895ad5327286c6ac2b0c1c97da672841745/source/index.ts#L444

When you are logged out, the class `'._9dls'` does not exist yet. Perhaps before login, Facebook does not know if the user needs the old or new design? (and therefore which class to apply to the HTML document?)

During normal use:
![Caprine in Normal Use](https://user-images.githubusercontent.com/17033543/121081786-2fc97900-c7ab-11eb-89c1-b80f32e938ec.png)

While logged out:
![Caprine while Logged Out](https://user-images.githubusercontent.com/17033543/121081790-30faa600-c7ab-11eb-8d44-36ce91edc298.png)

**Closed** 2021-08-12 22:58 UTC
Labels: bug, help wanted
