### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mattnoir** [sindresorhus/caprine#1787] opened 2022-02-08 07:44 UTC
Hello,
I am behind a corporate network at work and can't change my proxy settings. Chrome works fine and I can connect to both facebook and messenger, however caprine does not even start, stating that I need internet connection for it to work.
Is there any chance of proxy support? Thank you!

**Comment by lefterisgar** [comment] 2022-08-05 16:58
Duplicate of #1399.

**Closed by lefterisgar** 2022-08-05 16:58 UTC
