### ISSUE TITLE
Privacy Features Not Working

### ISSUE THREAD

**Issue by stseia** [sindresorhus/caprine#1496] opened 2020-12-18 02:39 UTC
Privacy Features not working (Block Seen, Typing, and Delivery Receipt) indicators.

**Comment by raz-newb** [comment] 2020-12-18 03:58
is it only the privacy features that do not work on you ? in my case almost all of the features of caprine does not work.

**Comment by dusansimic** [comment] 2020-12-18 08:04
Duplicate of #1439

**Closed by dusansimic** 2020-12-18 08:04 UTC
