### ISSUE TITLE
file/sticker/gif/emoji/voice/play/photo — doesn't work

### ISSUE THREAD

**Issue by alekksander** [sindresorhus/caprine#786] opened 2019-02-15 15:07 UTC
![image](https://user-images.githubusercontent.com/3148302/52864960-b0c45880-313b-11e9-9256-12ea7e15349b.png)
none of these white buttons works. this is 2.28.0 running on plasma.

**Comment by CvX** [comment] 2019-02-16 17:19
Duplicate of #779.

**Closed by CvX** 2019-02-16 17:19 UTC
