### ISSUE TITLE
Messenger not working...

### ISSUE THREAD

**Issue by lostPin** [sindresorhus/caprine#722] opened 2019-01-14 13:12 UTC
I've launched Caprine today casually (as I do every day) and only a blank Messenger window appears. Restarting the app (and Ubuntu) does not fix the issue...

---

Caprine 2.26.0
Electron 4.0.1
linux 4.18.0-13-generic
Locale: en-US

**Comment by CvX** [comment] 2019-01-14 13:14
The issue is on the Messenger's side:

<img width="1068" alt="screen shot 2019-01-14 at 14 13 38" src="https://user-images.githubusercontent.com/66961/51114806-aa725200-1806-11e9-9b74-748e91a0e6cd.png">

**Comment by lostPin** [comment] 2019-01-14 13:22
Thanks for the quick response. I guess we'll have to wait for FB to fix the issue. Cheers!

**Comment by CvX** [comment] 2019-01-14 13:46
…and it's back! Closing this issue. 🙂

**Comment by CvX** [comment] 2019-01-14 13:49
(though it seems their fix is propagating slowly, so it might take some time and/or a couple of refreshes  to make it work)

**Comment by lostPin** [comment] 2019-01-14 14:48
Caprine works again. Thanks gentleman, and have a great day! :D

**Closed** 2019-01-14 14:50 UTC
