### ISSUE TITLE
Caprine Preference > Privacy > Block Seen Indicator feature is not working on Caprine Version 2.52.0 (MacOS Big Sur 11.1)

### ISSUE THREAD

**Issue by nguyenngocduy20** [sindresorhus/caprine#1535] opened 2021-01-26 03:28 UTC
Caprine Preference > Privacy > Block Seen Indicator feature is not working on Caprine Version 2.52.0 (MacOS Big Sur 11.1)

**Comment by dusansimic** [comment] 2021-01-26 08:16
Duplicate of #1503

**Closed by dusansimic** 2021-01-26 08:16 UTC
