### ISSUE TITLE
chats font text became white 

### ISSUE THREAD

**Issue by bossdominator** [sindresorhus/caprine#2150] opened 2024-03-20 06:01 UTC
I'm not sure if due to new version but when I opened it became like this _attachment below_

![Screenshot from 2024-03-20 14-00-34](https://github.com/sindresorhus/caprine/assets/82248534/951ff406-14cf-445c-8d25-4ca39f4021cd)

---

Caprine 2.59.3
Electron 25.9.8
linux 6.5.0-25-generic
Locale: en-US

**Comment by ashcrok** [comment] 2024-03-20 09:11
I have encountered the same issue

---

Caprine 2.59.3
Electron 25.9.8
linux 6.5.0-25-generic
Locale: en-US

**Comment by ashcrok** [comment] 2024-03-20 09:14
Also, this occurs only for messages that I receive, and in the embedded part of links I send out. The messages I send are OK:

![image](https://github.com/sindresorhus/caprine/assets/6136342/ac000765-4787-4865-b276-661f96dc1532)

**Comment by mirenradia** [comment] 2024-03-20 10:02
I also have this issue. I wonder if it's a problem at Facebook's end since, even in light mode in a web browser, the lack of chat bubbles looks odd.

**Comment by mquevill** [comment] 2024-03-20 15:54
Duplicate of #2148

**Closed by mquevill** 2024-03-20 15:54 UTC
