### ISSUE TITLE
Dark mode not set on start, Big Sur (and probably other stuff)

### ISSUE THREAD

**Issue by mardulas** [sindresorhus/caprine#1567] opened 2021-02-26 21:50 UTC
I've installed it from the webpage, I've installed it with rosetta homebrew, I've installed it with homebrew, results are exactly the same. Seems to me the config.json file is set but not read...

Starts up as default, dark mode is not set (if follow system or not).
"view - sidebar" settings aren't doing anything.

**Comment by RDKRACZ** [comment] 2021-02-26 22:57
... Duplicate of https://github.com/sindresorhus/caprine/issues/1525 and probably https://github.com/sindresorhus/caprine/issues/1538 too. It's not limited to Mac, I saw this on Windows and Linux too.

**Comment by dusansimic** [comment] 2021-03-01 08:02
Hi @mardulas! This issue is already reported in #1525. Dark mode for some reason is not set automatically but you can disable it and enable it to make it work.

Regarding sidebar options, they don't work since we haven't yet fixed them for new UI.

**Closed by dusansimic** 2021-03-01 08:02 UTC

**Comment by matthewstrasiotto** [comment] 2021-03-02 00:57
I'm pretty sure it's also been fixed in master, just not release
