### ISSUE TITLE
Dark Mode don't do any ting else then togle the checkmark to the left of the menu selection 

### ISSUE THREAD

**Issue by moloean** [sindresorhus/caprine#1478] opened 2020-12-13 09:39 UTC
click on  View -> Dark Mode background is still white
click on it once more it the background is still thewhite.
---

Caprine 2.51.2
Electron 10.1.5
linux 5.8.0-31-generic
Locale: en-US

**Comment by dusansimic** [comment] 2020-12-13 10:26
Duplicate of #1439

**Closed by dusansimic** 2020-12-13 10:26 UTC
