### ISSUE TITLE
Taskbar icon does not change when there are new unread messages

### ISSUE THREAD

**Issue by Naimad1CZ** [sindresorhus/caprine#1939] opened 2022-10-16 01:34 UTC
I decided to switch back to Caprine today from Messenger destop (rather non-working inserting of images, website warning when clicking on links leading outsite of Facebook, ...).
However, when I receive a message (assuming I have active/open chat with someone else than the person that sends me the message), I hear the sound of a new message, but the taskbar's icon of Caprine doesn't change (on Messenger desktop, you get a red circle with number of chats with new messages in white).

Tried to restart the PC, tried with Caprine minimized and (I don't have Caprine in tray btw.) windowed, didn't help.

---
Caprine 2.56.1
Electron 20.0.3
win32 10.0.19043
Locale: en-US

Additional:
Windows 10 Pro, Version 21H1, OS build 19043.2075
Using dark mode (maybe important?)

**Comment by dusansimic** [comment] 2022-10-16 09:55
Caused by #1825. Even the solution we had in place was a workaround and not a real fix so it will be prone to breaking until we work out a real solution or Messenger website decides to send browser notifications like it did on the old design 😅. I'll close this now since it's essentially a duplicate but post a comment in the other issue and change the title.

**Closed by dusansimic** 2022-10-16 09:55 UTC
