### ISSUE TITLE
Version 2.59.3 Chat Bubbles White, Can't See Text

### ISSUE THREAD

**Issue by kgarrett67** [sindresorhus/caprine#2151] opened 2024-03-20 14:51 UTC
When I was using Caprine last night everything was fine. This morning when I opened Caprine, all messages from my friends are in white bubbles and white or very light gray text. You can't read the text. I am using dark mode. I can't find any settings to correct or change this. Changing themes only changes my message bubble color.

Not sure if this is enough information. Advise if more is needed.

Thank you

---

Caprine 2.59.3
Electron 25.9.8
linux 5.14.21-150500.55.52-default
Locale: en-US

**Comment by lephiloux** [comment] 2024-03-20 15:40
Have the same issue 
Caprine 2.59.3
Ubuntu 22.04 
Linux 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mquevill** [comment] 2024-03-20 15:54
Duplicate of #2148

**Closed by mquevill** 2024-03-20 15:54 UTC
