### ISSUE TITLE
Unable to paste & send images.

### ISSUE THREAD

**Issue by borowyalan** [sindresorhus/caprine#999] opened 2019-07-15 23:21 UTC
App version: `2.34.0`
OS: `Windows 10 x64, 1903`
Locale: `pl`

`Can't open the editor` message is shown instead of the message box when trying to upload an image using the icon or pasting it from the clipboard. 

![image](https://user-images.githubusercontent.com/38703820/61254822-4fde9200-a766-11e9-866e-5f226fa6ba3d.png)

I'm unable to close it in any way. Alert disappears after a relaunch and it's possible to send messages again but the problem with images persists.

**Comment by CvX** [comment] 2019-07-16 00:00
See #997

**Comment by sindresorhus** [comment] 2019-07-21 15:40
Duplicate of #997

**Closed by sindresorhus** 2019-07-21 15:40 UTC
