### ISSUE TITLE
End-to-end encryption rollout seems to break Caprine

### ISSUE THREAD

**Issue by jaymzh** [sindresorhus/caprine#2211] opened 2024-08-08 21:40 UTC
I don't see any messages in any threads that FB has converted to E2E.

I see the related preferences to enable E2E under `Profile -> Privacy and Safety -> End-to-end encrypted chats -> Secure storage`, but it's set to "off: and clicking on that doesn't do anything.

**Comment by nutuxedo** [comment] 2024-08-18 01:43
Hello, suffering this issue too.

**Comment by eoryb** [comment] 2024-08-22 08:57
Same problem here :-(
_(With the current latest version 2.60.1 )_

**Comment by mquevill** [comment] 2024-08-22 15:19
Duplicate of #2167.

**Closed by mquevill** 2024-08-22 15:19 UTC
