### ISSUE TITLE
Windows titlebar not themed

### ISSUE THREAD

**Issue by tomgacz** [sindresorhus/caprine#1106] opened 2019-10-12 10:52 UTC
Hello, I have a problem. My header is not displayed correctly. This is how it's displayed: <a href="https://imgur.com/7ksQj8W"><img src="https://i.imgur.com/7ksQj8W.jpg" title="source: imgur.com" /></a>
And this is correctly displayed on other apps:
<a href="https://imgur.com/6sVEKNc"><img src="https://i.imgur.com/6sVEKNc.jpg" title="source: imgur.com" /></a>
The second problem is not themed Windows Titlebar. In dark mode titlebar is still white and this not looking good. I found some website about customize titlebar, but i cant do anything with this. Here: https://www.npmjs.com/package/custom-electron-titlebar
Thanks!

**Comment by lucasriondel** [comment] 2019-10-20 17:31
Custom title bar would be awesome.

**Comment by lucasriondel** [comment] 2019-10-20 17:35
Maybe a duplicate of #955 for the title bar tho

**Comment by dusansimic** [comment] 2020-11-01 10:19
Regarding the header, it's meant to look that way. Caprines custom style includes removing the profile icon, "Chat" word and settings button.

Regarding the title bar suggestion, I think it's very interesting and worth exploring. It would be nice to have a title bar of the same color as Caprine background. I'd like to ask @sindresorhus opinion on this.

**Comment by CoreyVidal** [comment] 2021-07-24 20:48
Would really love the titlebar to be dark. I use Caprine maximized. On a very large screen, and everything is dark mode. The light-themed title bar is blinding.

**Comment by MrScottyTay** [comment] 2021-08-18 11:32
This is literally the one thing stopping me from using this app, can't be having a half-assed dark theme that keeps the title bar and scroll bar blidingly white.

**Comment by lefterisgar** [comment] 2022-08-06 07:27
Closing, as it will be fixed in the next release.

**Closed by lefterisgar** 2022-08-06 07:27 UTC
Labels: enhancement
