### ISSUE TITLE
Dark mode malfunctioning

### ISSUE THREAD

**Issue by DNM1008** [sindresorhus/caprine#1738] opened 2021-12-01 02:17 UTC
Dark mode now just made the conversation background white, including the text, making it quite hard (impossible) to read. the background  of the date is still black though
![image](https://user-images.githubusercontent.com/54259825/144159941-67afdc5b-52dc-4280-aac2-7e386daf6740.png)

---

Caprine 2.55.0
Electron 10.4.7
win32 10.0.19043
Locale: en-GB

**Comment by vanastasis** [comment] 2021-12-01 07:38
Same

Caprine 2.55.0
Electron 10.4.7
linux 5.14.0-kali4-amd64
Locale: en-GB

**Comment by pernielsentikaer** [comment] 2021-12-01 08:49
Duplicate of #1737

**Comment by FunkyJustin** [comment] 2021-12-01 10:23
Same case here

**Comment by spyd3r-b0y** [comment] 2021-12-01 10:59
how to solve?

**Comment by PixsaOJ** [comment] 2021-12-01 12:14
Duplicate of #1737

Close this one to help maintainers.

**Closed** 2021-12-02 14:50 UTC
