### ISSUE TITLE
Linux AppImage 2.14 is broken

### ISSUE THREAD

**Issue by ljubacanoa** [sindresorhus/caprine#486] opened 2018-06-07 13:48 UTC
1) Your today image can't start.
2) You should to change AppImage to generic name caprine.AppImage (not like now with build number in image) as it with update became useless by replacing previous AppImage as it is not anymore connected to previous caprine.desktop (name/path is not anymore same). So, every time you update application, it will not start until we don't delete xxx.desktop in local/share/applications as well for startup in config/applications. However, it is not connected with fact that your 2.114 build is broken.

**Comment by sindresorhus** [comment] 2018-06-07 14:59
Duplicate of #485

**Closed by sindresorhus** 2018-06-07 14:59 UTC
