### ISSUE TITLE
Dark mode is not working

### ISSUE THREAD

**Issue by jaworski-pawel** [sindresorhus/caprine#1472] opened 2020-12-11 16:32 UTC
Launch Caprine.
Select menu View -> Dark Mode
Dark mode is not working.

---

Caprine 2.51.2
Electron 10.1.5
linux 5.4.0-56-generic
Locale: pl

**Comment by dusansimic** [comment] 2020-12-11 16:32
Duplicate of #1439

**Closed by dusansimic** 2020-12-11 16:32 UTC
