### ISSUE TITLE
Proxy support??

### ISSUE THREAD

**Issue by DeltaSporos** [sindresorhus/caprine#1253] opened 2020-01-25 07:14 UTC
Been using caprine for a while now and I really like it. However, 50% of the time I'm unable to use it. (At work)

My only question is, do you have any intention of implementing http proxy support? Thank you for all your hard work.

**Comment by lefterisgar** [comment] 2022-08-05 17:07
Duplicate of #1399.

**Closed** 2022-08-05 17:08 UTC
