### ISSUE TITLE
[UI SUGGEST] An option to remove Title Bar

### ISSUE THREAD

**Issue by Shnxxx** [sindresorhus/caprine#1615] opened 2021-04-22 01:56 UTC
The UI is great and snappy and I love it! It's just, the title bar bothers me. Hahaha
![image](https://user-images.githubusercontent.com/48496678/115644284-e9ca6a00-a350-11eb-8aa2-11dbcfaf5111.png)

Anw, Thank you again!

**Comment by dusansimic** [comment] 2021-04-22 12:46
Duplicate of #1604

**Closed by dusansimic** 2021-04-22 12:46 UTC

**Comment by Shnxxx** [comment] 2021-04-22 14:34
I think it is not a duplicate. I was talking about the "title bar", not the empty space :D 
It would be much cleaner if the title bar is somehow blended to the UI or maybe an option to remove it

**Comment by dusansimic** [comment] 2021-04-22 14:52
@Shnxxx sorry about that 😅. I believe that [this](https://github.com/sindresorhus/caprine/issues/1106) is what you're talking about then. Currently it's not being worked on because Caprine is already quite hard to maintain and there are not plans for adding major features to the app. If there are any updates regarding this, they will be posted to the issue I mentioned. I would like something like that too but currently the priority is fixing known issues.

**Comment by Shnxxx** [comment] 2021-04-22 15:44
I see. No worries! It is still a great app! Thank you again! Much appreciated your response :D
