### ISSUE TITLE
Chat Not Updating

### ISSUE THREAD

**Issue by wadesmart** [sindresorhus/caprine#1434] opened 2020-11-03 13:39 UTC
When I turn on the app, if I post a message to a person or group it is seen but if I post from fb directly it is not showing up, nor the replies to the app. Ive tried restarting. I deleted the app, reinstalled and after a few posts the same thing is happening. 

---

Caprine 2.50.0
Electron 10.1.1
linux 4.15.0-122-generic
Locale: en-US

**Comment by dusansimic** [comment] 2020-11-05 11:13
So if I understand it correctly, when you send a message from Caprine, it shows up. But when you send a message from facebook.com, it doesn't show up in Caprine? If that is correct, does the message sent from fb.com show up in mobile apps and is it sent from the website at all? You can see that by looking at the little circle next to your message. If it's white circle with a gray check mark, it's sent. If it's a gray circle with a white check mark, it's sent and delivered and if it has a profile pic of a user, then it's seen. The problem would be if it's only a white circle without a check mark.

**Comment by wadesmart** [comment] 2020-11-05 12:24
When I post from either, my post shows up. I'm not getting the responses.
On fb I can see the response, but they are not coming through on the app. I
can see the person responding typing in the app but their response does not
show up - but I go to fb - its right there.

I have since originally posting this problem, logged out and in,
uninstalled and reinstalled an the problem has finally mostly gone away.
I am still seeing a post or two where the person is responding and I go to
fb and see the response and I then respond back - through the app - and
when they respond again, the second response will come thru. This seems
like more of a fb issue and not the app.
-- 
Registered Linux User: #480675
Registered Linux Machine: #408606
Linux since June 2004

**Comment by dusansimic** [comment] 2020-11-05 14:18
I agree. This type of issue has never occurred in Caprine AFAIK and I can't reproduce it on my machine either. If this continues to happen or worsen, please let me know but I think it could be any number of factors (bad internet, high computer resource usage, facebooks bug, websocket connection problems...).

I also see that you're running Linux kernel 4.15. What distro and version are you running, it might be nothing but it's good to know that info.

I'll close this anyway since it looks like a messenger.com issue and not Caprine issue.

**Closed by dusansimic** 2020-11-05 14:18 UTC

**Comment by wadesmart** [comment] 2020-11-07 13:25
Dusan, Ive attached two screen shots of what is going on.
Its more just so you can see what is happening --
Bottom right of the screen you can see the app next to the
fb conversation - we are talking about the Manchester United
game going on. The next image you can see where on fb the
post showed but on the app - nothing is there. You can see in
the first one where the little typing indicators are seen.

After finding this app I suggested it and installed it on a lot of my
clients computers for their offices. I was checking emails this
morning it seems some issues that I thought was user error is
now in fact .. this. The responses are now showing up.

Wade
-- 
Registered Linux User: #480675
Registered Linux Machine: #408606
Linux since June 2004

**Comment by dusansimic** [comment] 2020-11-09 15:10
Seems like those screenshots aren't showing up in the thread. I can see you're responding from email but it seems that GitHub won't upload any attached files. I'd recommend responding from the GitHub web ui so you could upload the screen shots.

**Comment by wadesmart** [comment] 2020-11-09 15:38
Ok... I edited the screen shots to make them smaller and focus just on the area.

![Messaging_issues](https://user-images.githubusercontent.com/16748667/98562073-42a8b900-226f-11eb-9142-4e74f6b28a77.png)
