### ISSUE TITLE
Caprine menu didn't work.

### ISSUE THREAD

**Issue by KeHongYing** [sindresorhus/caprine#1491] opened 2020-12-17 14:11 UTC
I can't change any setting after I login. Such as logout, switch to the dark mode. I can only click debug and delete all data, but it would still raise a js error:

```
Uncaught Exception:
TypeError: Cannot restructure property 'isMaximized' if 'config_1.default.get(...)' as undefined.
    at A[[.<anonymous> (/usr/lib/caprine/dist-js/index.js:478:17)
    at App.emit (events.js:315:20)
    at click (/usr/lib/caprine/dist-js/menu.js:674:32)
    at MenuItem.click (electron/js2c/browser_init.js:73:1683)
    at Object.a._executeCommand (electron/js2c/browser_init.js:71:2343)
```
I still can work after I click `ok`, and I would log out. When I'm on the login page. I can use the menu successfully. Once I log in, it will be broken.

And my caprine has no notification, but it seems that there are some notification sound when there is a new message.

---

Caprine 2.51.2
Electron 11.1.0
linux 5.9.14-arch1-1
Locale: en-US

**Comment by dusansimic** [comment] 2020-12-17 14:15
Duplicate of #1439

**Closed by dusansimic** 2020-12-17 14:15 UTC
