### ISSUE TITLE
1.2.2 Zip File missing folders and Icon.png

### ISSUE THREAD

**Issue by cwilli34** [sindresorhus/caprine#79] opened 2016-04-20 14:01 UTC
There seems to be no /app/ folder in the /resources/ directory in the zip file.  I cannot find a Icon.png file in the zip file.  Also, trying to install from AUR on my arch linux, I get an error during the file validation check stops the build that says the Icon.png file ....FAILED.

**Comment by sindresorhus** [comment] 2016-04-21 13:36
The app is packaged with [asar](https://github.com/electron/asar):

```
~/Downloads/Caprine-linux-1.2.2/resources
❯ asar list app.asar 
/.DS_Store
/.editorconfig
/.gitattributes
/.gitignore
/.travis.yml
/browser.css
/browser.js
/index.js
/license
/media
/media/IconTray.png
/media/IconTray@2x.png
/media/IconTray@4x.png
/menu.js
/node_modules
/node_modules/electron-debug
/node_modules/electron-debug/index.js
/node_modules/electron-debug/license
/node_modules/electron-debug/node_modules
/node_modules/electron-debug/node_modules/electron-is-dev
/node_modules/electron-debug/node_modules/electron-is-dev/index.js
/node_modules/electron-debug/node_modules/electron-is-dev/license
/node_modules/electron-debug/node_modules/electron-is-dev/package.json
/node_modules/electron-debug/node_modules/electron-is-dev/readme.md
/node_modules/electron-debug/node_modules/electron-localshortcut
/node_modules/electron-debug/node_modules/electron-localshortcut/index.js
/node_modules/electron-debug/node_modules/electron-localshortcut/license
/node_modules/electron-debug/node_modules/electron-localshortcut/package.json
/node_modules/electron-debug/node_modules/electron-localshortcut/readme.md
/node_modules/electron-debug/package.json
/node_modules/electron-debug/readme.md
/node_modules/electron-dl
/node_modules/electron-dl/index.js
/node_modules/electron-dl/license
/node_modules/electron-dl/package.json
/node_modules/electron-dl/readme.md
/package.json
/readme.md
/storage.js
/tray.js
```

**Comment by cwilli34** [comment] 2016-04-22 17:34
So what are you saying?  I need to now get asar and unpackage all the asar archives? What is the proper way to build and install on Linux now?

**Comment by sindresorhus** [comment] 2016-04-22 18:05
I'm saying it's as intended. Electron supports reading asar archives. Think of it just as a replacement for the folder.

https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md

**Comment by cwilli34** [comment] 2016-04-22 18:49
Ok, I am not sure how to run the program then.  I don't know anything about Electron, or how to build this on Linux.  So I installed asar through npm, extracted all the asar files and then installed it.  It didn't work as inspected.  Do I need electron installed?

I am not sure who handles the AUR repository for Arch, but the 1.2.2 version is there to be installed but I get errors on the Icon.png file sha256sum not matching up at the URL https://raw.githubusercontent.com/sindresorhus/caprine/v{$pkgver}/media/Icon.png, because Icon.png obviously doesn't exist anymore since the icons where renamed to IconTray*.png.  So I change the URL in the package build to https://raw.githubusercontent.com/sindresorhus/caprine/v{$pkgver}/media/IconTray@4x.png, recomputed the sha256sum for it, and then it installed fine then.  Whomever packaged it for AUR needs to edit the build file and correct it.

**Comment by cwilli34** [comment] 2016-04-22 18:52
And for some reason the tray icon does not stay in the tray anymore.  After about a minute, it just disappears.  Can you think of why it would do that, or should I open another issue for that?

**Comment by sindresorhus** [comment] 2016-04-22 19:13
> So I installed asar through npm, extracted all the asar files and then installed it. It didn't work as inspected. Do I need electron installed?

You don't need to deal with asar directly. Electron handles all that.

> I am not sure who handles the AUR repository for Arch

According to https://github.com/sindresorhus/caprine/issues/78#issuecomment-212279390, it's @forivall.

> And for some reason the tray icon does not stay in the tray anymore. After about a minute, it just disappears.

No idea. Probably not this app though as it's just using the Electron API directly. You're free to open issues, but I don't use Linux, so they won't get any support/work from me.

**Comment by forivall** [comment] 2016-04-22 19:59
My bad, I didn't bother to re-download after i tweaking the urls. In the future, report issues for the aur package on the aur page: https://aur.archlinux.org/packages/caprine-bin/

**Comment by sindresorhus** [comment] 2017-04-03 10:00
Fixed in https://github.com/sindresorhus/caprine/releases/tag/v2.0.0

**Closed by sindresorhus** 2017-04-03 10:00 UTC
