### ISSUE TITLE
Caprine 2.57.0 Crashed When Doing Video Chat

### ISSUE THREAD

**Issue by markn1974** [sindresorhus/caprine#1981] opened 2023-01-16 00:07 UTC
Sirs:  Caprine 2.56.1 and 2.57 crash each time I try to do a video chat. Using 2.56.0 works. 
My system information as follows.  If this has been reported, I apologize for the duplication. Thank you for your work!

System:
  Kernel: 5.15.0-58-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.6
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Hewlett-Packard product: 500-314 v: N/A serial: <superuser required>
    Chassis: type: 3 serial: <superuser required>
  Mobo: Hewlett-Packard model: 2B17 v: 1.0 serial: <superuser required> UEFI: AMI v: 80.04
    date: 03/26/2014
CPU:
  Info: quad core model: AMD A8-7600 Radeon R7 10 Compute Cores 4C+6G bits: 64 type: MT MCP
    arch: Steamroller rev: 1 cache: L1: 256 KiB L2: 4 MiB
  Speed (MHz): avg: 3094 min/max: 1400/3100 boost: enabled cores: 1: 3094 2: 3094 3: 3094
    4: 3094 bogomips: 24753
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Kaveri [Radeon R7 Graphics] vendor: Hewlett-Packard driver: radeon v: kernel
    ports: active: VGA-1 empty: DVI-D-1 bus-ID: 00:01.0 chip-ID: 1002:1313
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: ati,radeon
    unloaded: fbdev,modesetting,vesa gpu: radeon display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1280x1024 s-dpi: 96
  Monitor-1: VGA-0 mapped: VGA-1 model: HP vs19b res: 1280x1024 dpi: 86 diag: 482mm (19")
  OpenGL: renderer: AMD KAVERI (LLVM 13.0.1 DRM 2.50 5.15.0-58-generic) v: 4.5 Mesa 22.0.5
    direct render: Yes
Audio:
  Device-1: AMD Kaveri HDMI/DP Audio vendor: Hewlett-Packard driver: snd_hda_intel v: kernel
    bus-ID: 00:01.1 chip-ID: 1002:1308
  Device-2: AMD FCH Azalia vendor: Hewlett-Packard driver: snd_hda_intel v: kernel
    bus-ID: 00:14.2 chip-ID: 1022:780d
  Device-3: Microsoft LifeCam VX-3000 type: USB driver: snd-usb-audio,sonixj bus-ID: 4-1:2
    chip-ID: 045e:00f5
  Sound Server-1: ALSA v: k5.15.0-58-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Hewlett-Packard
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: e000 bus-ID: 01:00.0
    chip-ID: 10ec:8168
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Qualcomm Atheros AR9485 Wireless Network Adapter
    vendor: Hewlett-Packard AR9485/HB125 802.11bgn 1×1 Wi-Fi driver: ath9k v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 bus-ID: 04:00.0 chip-ID: 168c:0032
  IF: wlp4s0 state: up mac: <filter>
Repos:
  Packages: 2159 apt: 2149 flatpak: 10
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com vera main upstream import backport
    2: deb http: //mirror.genesisadaptive.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //mirror.genesisadaptive.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //mirror.genesisadaptive.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 250 Uptime: 16m Memory: 6.71 GiB used: 2.79 GiB (41.6%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11 Client: Cinnamon v: 5.6.6 inxi: 3.3.13

---

Caprine 2.56.0
Electron 20.0.2
linux 5.15.0-58-generic
Locale: en-US

**Comment by dusansimic** [comment] 2023-01-19 11:44
Could you try it on the latest Caprine version (v2.57.0)?

**Comment by billybhaub** [comment] 2023-02-12 23:03
> Could you try it on the latest Caprine version (v2.57.0)?

I have the same issue on v2.57.0

**Comment by andrewmeyer** [comment] 2023-02-26 18:34
I have the same issue on caprine 2.57.0
OS: Linux Mint 21.1 x86_64 
Kernel: 5.15.0-60-generic

**Comment by andrewmeyer** [comment] 2023-03-14 22:11
duplicate of #1964 too

**Comment by andrewmeyer** [comment] 2023-05-03 15:57
This appears to be fixed in 2.57.3 for me

**Closed** 2023-05-03 18:56 UTC
