### ISSUE TITLE
Some emoji's are not in the font used in the input box 

### ISSUE THREAD

**Issue by Haroenv** [sindresorhus/caprine#12] opened 2015-09-20 17:15 UTC
For example `☺️` shows as a rectangle, sent and on messenger.com it behaves correctly however.

**Comment by sindresorhus** [comment] 2015-09-21 04:19
I assume you used Safari on messenger.com. Chrome, which is what Electron and this app uses to render the app, seem to not support that emoji. Probably because it's using a variation selector: http://unicodelookup.com/#☺️/1

It's an issue with Chrome and out of my hands. I couldn't find a Chrome issue for this, but this seems related: https://github.com/nwjs/nw.js/issues/3489

Will keep this open until it's fixed in Chrome.

**Comment by Haroenv** [comment] 2015-09-21 04:42
Ah, I assumed so, naughty Chrome then!

**Comment by sindresorhus** [comment] 2016-03-14 11:01
Can no longer reproduce this in https://github.com/sindresorhus/caprine/releases/tag/v1.2.0.

**Closed by sindresorhus** 2016-03-14 11:01 UTC
