### ISSUE TITLE
Buttons without working Functions

### ISSUE THREAD

**Issue by CybernetiX-S3C** [sindresorhus/caprine#2229] opened 2024-09-17 17:17 UTC
Unable to get Caprine to click the "sync now" button in order for the messages to sync properly. It clicks as a hyperlink, but nothing happens. 

![Screenshot from 2024-09-17 13-15-00](https://github.com/user-attachments/assets/4afa6fd8-ad51-4f85-8d8c-aabe96d261ed)

Same for "Messenger Settings".

![Screenshot from 2024-09-17 13-42-14](https://github.com/user-attachments/assets/d58669fd-c39c-4367-8f99-5a9980cbe956)

Thank you kindly!

---
System:

Linux S3C 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux

Caprine Ver:

Caprine 2.60.1
Electron 29.0.1
linux 6.8.11-amd64
Locale: en-US

**Comment by CybernetiX-S3C** [comment] 2024-09-17 19:50
https://github.com/sindresorhus/caprine/issues/2167#issuecomment-2089402948

I found the fix!! F12, removing hide-preferences-window worked.

**Comment by mquevill** [comment] 2024-11-29 22:48
Duplicate of #2167.

**Closed by mquevill** 2024-11-29 22:48 UTC
