### ISSUE TITLE
Dark Mode Not Working

### ISSUE THREAD

**Issue by Ansari-Abdul** [sindresorhus/caprine#1510] opened 2020-12-24 00:32 UTC
Clicking "View" in the Menu Bar on the Caprine window and then clicking "Dark Mode" (or pressing the shortcut keys CTRL+D) changes nothing. 

---

Caprine 2.51.2
Electron 11.1.1
linux 5.9.14-arch1-1
Locale: en-US

**Comment by tenpaiyomi** [comment] 2020-12-24 01:33
Duplicate of #1439

**Closed** 2020-12-24 09:11 UTC
