### ISSUE TITLE
icon is not displayed

### ISSUE THREAD

**Issue by skud110** [sindresorhus/caprine#1424] opened 2020-10-11 10:11 UTC
![dock caprime](https://user-images.githubusercontent.com/72689489/95675914-eba1bc80-0bba-11eb-8cba-05d9e3c20e8b.png)
After my installation of the application, in the gnome menu and in the dock there is no icon just a white square.
sorry for my google english translation.
ubuntu 20.04

Caprine 2.50.0
Electron 10.1.1
linux 5.4.0-48-generic
Locale: fr

**Comment by AggelosM** [comment] 2020-10-19 21:32
Mine is being displayed like that.
![Capture](https://user-images.githubusercontent.com/16342124/96514036-c3295a80-126b-11eb-8481-4208435775de.PNG)

---

Caprine 2.51.0
Electron 10.1.3
win32 10.0.19041
Locale: en-US

**Comment by dusansimic** [comment] 2020-10-28 08:23
@AggelosM, your issue is related to https://github.com/sindresorhus/caprine/issues/1429 since it's on Windows, so we'll track it there.

@skud110, how did you install Caprine? Deb, AppImage or Snap? If it's deb file, then this issue is already known and it is caused by Electron and this issue is a duplicate of https://github.com/sindresorhus/caprine/issues/782.

**Comment by dusansimic** [comment] 2020-11-19 12:15
@skud110 this issue was fixed in one of last releases. Please update Caprine to the latest version.

**Closed by dusansimic** 2020-11-19 12:15 UTC
