### ISSUE TITLE
It's unusable

### ISSUE THREAD

**Issue by wildcard-f8** [sindresorhus/caprine#1950] opened 2022-10-19 06:20 UTC
I open it up and it works for about a few minutes then I'll put it in the background. When I get back to it I click on my messages and nothing happens. I can click on the menu bar items. I can minimize it to the system bar and open it again, but the I can't click on the chats. I click on the chats and nothing happens. It doesn't go to that chat. I have to quit the app and open it again for it to work again and then a few minutes later the same problem happens.

**Comment by dusansimic** [comment] 2022-10-19 06:55
Duplicate of #1878

**Closed by dusansimic** 2022-10-19 06:55 UTC
