### ISSUE TITLE
Regression - taskbar icon not displaying indicator when receiving new messages

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#1495] opened 2020-12-17 21:56 UTC
Started today. Taskbar icon (not tray icon) normally displays an indicator when there are pending, unread new messages received. Now it's not displaying the indicator.

Windows 7.

**Comment by dusansimic** [comment] 2020-12-18 08:03
Duplicate of #1439

**Closed by dusansimic** 2020-12-18 08:03 UTC
