### ISSUE TITLE
Dark mode impossible to show

### ISSUE THREAD

**Issue by clementlecerf** [sindresorhus/caprine#1470] opened 2020-12-11 07:43 UTC
Since last update I guess, dark mode is impossible and there is a problem in the responsivness in my messages sent to friends (my chat bubbles) are glued to the right border of the app.

![Screen Shot 2020-12-11 à 08 42 58](https://user-images.githubusercontent.com/33632936/101876580-e649f980-3b8c-11eb-827f-de9cc3a1f42b.png)

Thanks for the app :)
---

Caprine 2.51.1
Electron 10.1.5
darwin 20.1.0
Locale: fr

**Comment by DavidGereb** [comment] 2020-12-11 08:05
https://github.com/sindresorhus/caprine/issues/1459#issuecomment-743040481

**Comment by taylor85345** [comment] 2020-12-11 16:24
> [#1459 (comment)](https://github.com/sindresorhus/caprine/issues/1459#issuecomment-743040481)

Having the same issue, which was somewhat fixed by the referenced HTML tweak. However I wanted to add that custom CSS functionality also seems to be broken at this time, which is not resolved by applying the fb dark mode.

**Comment by dusansimic** [comment] 2020-12-11 23:44
Duplicate of #1439

**Closed by dusansimic** 2020-12-11 23:44 UTC
