### ISSUE TITLE
Notification 

### ISSUE THREAD

**Issue by kamilm24** [sindresorhus/caprine#1756] opened 2021-12-05 17:52 UTC
Hello, There is a problem with notifications on MacOS Monterey. 
---

Caprine 2.55.1
Electron 10.4.7
darwin 21.2.0
Locale: en-US

**Comment by dusatvoj** [comment] 2021-12-07 11:36
I can't see notifications maybe for maybe half a year.
caprine 2.55.1-1
electron 16.0.4-1

```
# lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
I'm using i3wm with dunst and notifications from FF / thunderbird / ... works.

IDK if I'm doing something wrong

**Comment by robinsrk** [comment] 2021-12-10 03:27
> I can't see notifications maybe for maybe half a year. caprine 2.55.1-1 electron 16.0.4-1
> 
> ```
> # lsb_release -a
> LSB Version:	1.4
> Distributor ID:	Arch
> Description:	Arch Linux
> Release:	rolling
> Codename:	n/a
> ```
> 
> I'm using i3wm with dunst and notifications from FF / thunderbird / ... works.
> 
> IDK if I'm doing something wrong

Same here. I also can't see notification. i am also in linux, awesomewm.

**Comment by huoi** [comment] 2021-12-10 07:00
Same issue here. The notification sound works but there are no notifications.
OS: Arch
DE: KDE Plasma
Caprine: 2.55.2

Here's my `config.json` just in case:
```
{
	"theme": "system",
	"privateMode": false,
	"showPrivateModePrompt": true,
	"vibrancy": "none",
	"zoomFactor": 1,
	"lastWindowState": {
		"x": 0,
		"y": 32,
		"width": 1600,
		"height": 820,
		"isMaximized": true
	},
	"menuBarMode": false,
	"showDockIcon": true,
	"showTrayIcon": true,
	"alwaysOnTop": false,
	"showAlwaysOnTopPrompt": true,
	"bounceDockOnMessage": false,
	"showUnreadBadge": true,
	"showMessageButtons": true,
	"launchMinimized": true,
	"flashWindowOnMessage": true,
	"notificationMessagePreview": true,
	"block": {
		"chatSeen": false,
		"typingIndicator": false,
		"deliveryReceipt": false
	},
	"emojiStyle": "facebook-3-0",
	"useWorkChat": false,
	"sidebar": "default",
	"autoHideMenuBar": false,
	"notificationsMuted": false,
	"callRingtoneMuted": false,
	"hardwareAcceleration": true,
	"quitOnWindowClose": true,
	"keepMeSignedIn": true,
	"autoplayVideos": false,
	"isSpellCheckerEnabled": false,
	"spellCheckerLanguages": []
}
```

**Comment by dusansimic** [comment] 2021-12-10 09:28
Duplicate of #1562

**Closed by dusansimic** 2021-12-10 09:28 UTC
