### ISSUE TITLE
Removing Notification Centre alerts when read?

### ISSUE THREAD

**Issue by wiffleman** [sindresorhus/caprine#1316] opened 2020-03-27 22:52 UTC
Thanks for all of the work on Caprine thus far.

Just wondering - is there a setting somewhere to remove Notification Centre alerts when a message has been read (without directly clicking the notification itself?)

Thanks.

**Comment by dusansimic** [comment] 2022-11-06 09:51
Duplicate of #1329

**Closed by dusansimic** 2022-11-06 09:51 UTC
