### ISSUE TITLE
"Hide names and avatars" Problem

### ISSUE THREAD

**Issue by AyonSahaa** [sindresorhus/caprine#1985] opened 2023-01-21 21:28 UTC
"Hide names and avatars" does not hide names and avatars.

---

Caprine 2.57.0
Electron 21.2.3
win32 10.0.22621
Locale: en-US

**Comment by dusansimic** [comment] 2023-01-21 22:11
Duplicate of #1984

**Closed by dusansimic** 2023-01-21 22:11 UTC
