### ISSUE TITLE
Chat Window

### ISSUE THREAD

**Issue by patefoniq** [sindresorhus/caprine#2040] opened 2023-07-28 10:39 UTC
Chat is not filling the window. Please, do not advise me to reinstall Windows, everything else is working perfectly.

![2023-07-28;;12_38_33--Capture2309](https://github.com/sindresorhus/caprine/assets/11136688/9f2506de-1c7b-4803-bd66-1ada4fbb7223)

---

Caprine 2.57.0
Electron 21.2.3
win32 6.3.9600
Locale: en-US

**Comment by patefoniq** [comment] 2023-07-28 11:40
I found something. Caprine is probably misreading the resolution:

![image](https://github.com/sindresorhus/caprine/assets/11136688/fcc3fe46-fd09-41f7-b05f-a5251d5547a2)

When I manually changed it in "dev tools" it started working correctly. I've checked many messenger desktop apps and everyone has the same issue. What is interesting, this happens on one PC but on the second one (with the same configuration) not. What should I check?

**Comment by patefoniq** [comment] 2023-07-28 13:35
I have another interesting observation. Well, when I expand all the submenus in chat information, suddenly the chat windows resize:

![image](https://github.com/sindresorhus/caprine/assets/11136688/e04cbe9b-6e64-42fa-b50b-c8279867cbf8)

What is all about here?

**Comment by CubicReg** [comment] 2023-07-30 11:23
I have the same issue, was wondering what was happening. I have the portable version from portableapps.io, same version 57.0

**Comment by NonVideri** [comment] 2023-08-02 08:32
I have a similar issue in NixOS Linux 23.11 with GNOME 44.3 (Wayland), with Caprine version 2.55.5.
![image](https://github.com/sindresorhus/caprine/assets/26414014/845feb16-ccb5-4715-8bf8-8338cf8ddf53)
The above is with conversation information expanded. If I close it, the chat window becomes almost completely hidden:
![image](https://github.com/sindresorhus/caprine/assets/26414014/ae40b0c6-292a-4b42-a699-0b58e672e7e4)
It seems to improperly detect my screen size:
![image](https://github.com/sindresorhus/caprine/assets/26414014/20bde5fa-aa87-42cf-a64e-4685113b0559)

**Comment by dusansimic** [comment] 2023-08-02 12:07
Duplicate of #2039. This should work on the latest version of Caprine.

**Closed by dusansimic** 2023-08-02 12:07 UTC
