### ISSUE TITLE
Dark mode not being persistent

### ISSUE THREAD

**Issue by Just-Knight** [sindresorhus/caprine#1571] opened 2021-03-02 18:21 UTC
Open caprine first time after install
Log into messenger with remember me ticked
In View drop down select dark mode.
(It becomes dark mode)
go to file and press quit
open it again 
Its light mode But the dark mode in the drop down view for dark mode is still ticked
---
//It used to work like normal but now with the "new" messenger look it looks like it broke the dark mode trigger of the app.

Caprine 2.52.0- 1
Electron 11.3.0
linux 5.10.18-1-MANJARO
Locale: en-GB

**Comment by dusansimic** [comment] 2021-03-03 07:06
Duplicate of #1525

**Closed by dusansimic** 2021-03-03 07:06 UTC
