### ISSUE TITLE
Dark Mode Suddenly Gone

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#2036] opened 2023-07-26 06:51 UTC
At least when Google Search does Dark Mode when I have  it configured to Light Mode I just have to toggle the two Modes to get it right again.
Toggling did not work with Caprine that now suddenly has no more Dark Mode.

---

Caprine 2.57.6
Electron 22.3.16
win32 6.1.7601
Locale: en-US

**Comment by lebjortvedt** [comment] 2023-07-26 07:50
Seems to be gone here as well, running latest Caprine as a snap on Ubuntu 23.04.

**Comment by ienzo** [comment] 2023-07-26 08:20
Running Caprine on Linux Mint as an appimage. Can confirm as well that dark mode disappeared. The option to toggle it is still there but it does nothing.

**Comment by kovacslt** [comment] 2023-07-26 08:56
For me too. I bet Facebook messed something with their CSS again, as I had the same problem some time ago and it was fixed once. This time increase/decrease text size doesn't work either.

**Comment by Koko2110** [comment] 2023-07-26 09:37
It seems like no options work in general, not just dark mode or the text size.

**Comment by dusansimic** [comment] 2023-07-26 09:40
Root of the issue is preload script not being loaded.

```
Unable to load preload script: /home/dusan/Dev/caprine/dist-js/browser.js
```

If you have the same issue, please use reactions, don't spam the issue with +1 comments.

**Comment by joaomcarlos** [comment] 2023-07-26 15:16
Pretty much sure this is a widespread issue.

**Comment by PreachJohn** [comment] 2023-07-26 16:26
Sorry, but this is a NEW issue. Based on an old longstanding one for
context. But it definitely constitutes a NEW issue.
Please don't accuse me of 'spam'. Not appreciated.

**Closed** 2023-07-26 19:11 UTC
