### ISSUE TITLE
Dark mode stopped working

### ISSUE THREAD

**Issue by CaptainMazda** [sindresorhus/caprine#1465] opened 2020-12-10 15:51 UTC
I was using an earlier version of Caprine (2.34.0) for a while without issues. Last night dark mode all of a sudden stopped working. Only the background of the context menu at the very top of the window is dark now, everything else is white. Tried toggling dark mode and installing to the latest Caprine but it makes no difference.

---

Caprine 2.51.2
Electron 10.1.5
win32 10.0.18363
Locale: en-US

**Comment by CaptainMazda** [comment] 2020-12-10 15:53
![ag3yh](https://user-images.githubusercontent.com/37168362/101795460-edfa9700-3ad5-11eb-924b-895db806f8fb.jpg)

**Comment by gincio** [comment] 2020-12-10 15:57
Same issue on Manjaro. I think that facebook updated their messenger web app, so custom CSS injected by Caprine's dark mode doesn't work.

**Comment by AggelosM** [comment] 2020-12-10 15:59
Same issue.

---

Caprine 2.51.2
Electron 10.1.5
win32 10.0.19041
Locale: en-US

**Comment by hyperxpizza** [comment] 2020-12-10 16:06
Same issue here

Ubuntu 18.04.5
Caprine 2.51.2

just downloaded through snap

**Comment by dusansimic** [comment] 2020-12-10 16:13
Duplicate of #1439

**Closed by dusansimic** 2020-12-10 16:13 UTC
