### ISSUE TITLE
Dark mode is not working

### ISSUE THREAD

**Issue by filesmuggler** [sindresorhus/caprine#1498] opened 2020-12-18 11:31 UTC
I downloaded the Appimage, because of promised dark mode. I tried to change both 'Ctrl+D' and through menu list and none worked. Any tips?

---

Caprine 2.51.2
Electron 10.1.5
linux 5.4.0-58-generic
Locale: en-US

**Comment by MrCaira** [comment] 2020-12-18 11:45
It's due to some recent changes in the way facebook handles dark mode. 
How the current AppImage is setup, all it does is to add **.dark-mode** to the HTML tag's class...

This used to work before, but now facebook changed from using **.dark-mode** to **.__fb-dark-mode** instead.
For now you can manually add that class by rightclicking the header of any conversation and press inspect element and add it.

Note to developer, new dark-mode class is **__fb-dark-mode**

**Comment by dusansimic** [comment] 2020-12-18 12:30
The `dark-mode` classname is added by Caprine in order to enable custom dark mode which was used before new Messenger design was released. Now Messenger enables dark mode by adding `__fb-dark-mode` classname which is unrelated to Caprine. I'm currently working on dark mode for new Messenger UI so it's a work in progress.

**Comment by dusansimic** [comment] 2020-12-18 12:30
Duplicate of #1439

**Closed by dusansimic** 2020-12-18 12:30 UTC
