### ISSUE TITLE
macOS: Window size and position goes back to default

### ISSUE THREAD

**Issue by stevek123** [sindresorhus/caprine#1148] opened 2019-10-27 15:56 UTC
Every time I start the app on macOS, the window size and position goes back to the default, instead of remembering the last setting.

I'm running version 2.40.0 (2.40.0.1662), on macOS Catalina (10.15)

**Comment by dusansimic** [comment] 2023-05-06 16:57
Can't reproduce the issue. Closing...

**Closed by dusansimic** 2023-05-06 16:57 UTC
