### ISSUE TITLE
Annoying and illogical top-padding when dark mode is applied (just below the status bar)

### ISSUE THREAD

**Issue by vladspatariu** [sindresorhus/caprine#1608] opened 2021-04-15 07:15 UTC
The title kind says is it all. Seems like a quick, css fix. 

![image](https://user-images.githubusercontent.com/11179331/114829198-73b78780-9dd3-11eb-8b63-f7e7f7ccc8cf.png)

---

Caprine 2.52.3
Electron 10.1.5
win32 10.0.19042
Locale: en-US

**Comment by RDKRACZ** [comment] 2021-04-15 07:21
#1604 
>Seems like a quick, css fix.

Indeed, it’s included in the original issue.

**Comment by dusansimic** [comment] 2021-04-15 07:31
Duplicate of #1604

**Closed by dusansimic** 2021-04-15 07:31 UTC
