### ISSUE TITLE
[manjaro, xfce] No notification, only sound

### ISSUE THREAD

**Issue by Lolis4TheWin** [sindresorhus/caprine#1782] opened 2022-01-29 17:42 UTC
Installed via gui pacman. I didn't find another package, so... 
![image](https://user-images.githubusercontent.com/50179148/151671422-82d29f47-df74-4f6f-919c-67a4f40389e2.png)
Any idea what could i do about it?

**Comment by dusansimic** [comment] 2022-01-30 09:00
Duplicate of #1562

**Closed by dusansimic** 2022-01-30 09:00 UTC
