### ISSUE TITLE
Issue with Window 10, Ver. 2004, OS build 21277.1000

### ISSUE THREAD

**Issue by nityesha** [sindresorhus/caprine#1475] opened 2020-12-13 06:55 UTC
When choosing Dark Mode in the menu, only the menu turns dark, the rest of the application, e.g. the chat area, remains light. This did not happen in another earlier build of Windows 10.
![Caprine](https://user-images.githubusercontent.com/8200988/102005324-4a4cf900-3d18-11eb-9028-ab806de46f3b.jpg)

**Comment by dusansimic** [comment] 2020-12-13 09:10
Duplicate of #1439

**Closed by dusansimic** 2020-12-13 09:10 UTC
