### ISSUE TITLE
Global shortcut to toggle main window

### ISSUE THREAD

**Issue by zakius** [sindresorhus/caprine#874] opened 2019-04-26 12:12 UTC
Not sure how it should interact with `Quit on Window Close` and what should be the default shortcut (I'd like to use `` Super+` `` for that but that may collide with other persistent apps, notably other messengers)

References #873

I may be able to implement the basic feature and test it against Windows, but configuration and polishing for other platforms is out of my reach most likely

**Comment by sindresorhus** [comment] 2019-04-29 07:16
Duplicate of #827

**Closed by sindresorhus** 2019-04-29 07:16 UTC
