### ISSUE TITLE
white screen when i  open caprine

### ISSUE THREAD

**Issue by rhysinku** [sindresorhus/caprine#1348] opened 2020-04-29 04:45 UTC
every time i open caprine, this issue alwasy come up and the only way i can fix this is when i restart may pc... please fix this issue .. i really love this app
---
![image](https://user-images.githubusercontent.com/54741996/80561421-05898180-8a17-11ea-9814-5d193f486517.png)

Caprine 2.45.0
Electron 8.2.1
win32 6.1.7601
Locale: en-US

**Comment by MrGKanev** [comment] 2020-05-01 20:24
@rhysinku try deleting app data. Login again. Restart the computer and see if the issue still occurs.

**Comment by rhysinku** [comment] 2020-05-02 03:40
tnx i will try that but i did try chance the compatibility of the software
to window vista service pack 2 and it work just fine now

**Comment by dusansimic** [comment] 2020-10-30 21:43
Duplicate of #1404

**Closed by dusansimic** 2020-10-30 21:43 UTC
