### ISSUE TITLE
Dark mode doesn't work after FB interface update

### ISSUE THREAD

**Issue by BloodRaven0** [sindresorhus/caprine#1450] opened 2020-11-21 09:16 UTC
For some reason, my installation of caprine is now using the new UI style of facebook and it's stuck in light mode, dark mode or custom styles doesn't seem to do anything.
I've updated to the latest 2.51.1 version and am using Windows 10 Pro x64

**Comment by dusansimic** [comment] 2020-11-21 10:27
Hi! Could you please send me a screenshot of the new UI? What do you mean by "new UI style of facebook"?

**Comment by Syndamia** [comment] 2020-11-21 10:37
Messenger has updated their UI, probably following the "new facebook look". Try to reload the page (`F5`) or just log in from a browser, it should show up. It seems that a lot of the Caprine functionality is broken.

Here, a screenshot of a part of it (obviously blacked out the personal bits):
![2020-11-21_12-30](https://user-images.githubusercontent.com/46843671/99875136-f6a62e80-2bf5-11eb-91f1-c511c97097e2.png)

**Comment by dusansimic** [comment] 2020-11-21 20:51
Yeah, seems like Facebook has change the UI quite a lot. I haven't received the update so far so it'll be hard to update anything. Anyhow this issue is a duplicate of #1439

**Closed by dusansimic** 2020-11-21 20:51 UTC
