### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#2000] opened 2023-03-26 05:05 UTC
After mentioning that Delete/Remove Buttons don't work, I notice my React Icons no longer load/appear properly as well.
Not aware of too much activity from any associated source since 257.0 launch; very quiet.
That's why I ask if Caprine is Deprecated? I sure hope not.

---

Caprine 2.57.0
Electron 21.2.3
win32 6.1.7601
Locale: en-US

**Comment by kacnje** [comment] 2023-03-27 05:04
I just came to this "Issues" site with the same question. Caprine is a lovely client but has some bugs (described in other themes).

**Comment by dusansimic** [comment] 2023-04-16 17:15
Duplicate of #2004

**Closed by dusansimic** 2023-04-16 17:15 UTC
