### ISSUE TITLE
caprine just goes and gets arounmd 30gb if ram memory our of nowhere

### ISSUE THREAD

**Issue by angaratosurion** [sindresorhus/caprine#1654] opened 2021-06-06 01:09 UTC
just leave it open in the background 

---

Caprine 2.53.0
Electron 10.1.5
win6410.0.19042
Locale: el

**Comment by dusansimic** [comment] 2021-06-06 07:44
Does that happen often or is it just a one time thing. For how long is Caprine open before that happens? Is there a video or an animation playing and how many pictures are usually there in your chats (a large amount or not a large amount, a large amount would be over 100). Does restart of Caprine help?

**Comment by angaratosurion** [comment] 2021-06-06 11:14
I think around 12 hours and no images or video . I did not send anything

Στις Κυρ, 6 Ιουν 2021, 10:44 ο χρήστης Dušan Simić ***@***.***>
έγραψε:

**Comment by mquevill** [comment] 2021-06-07 01:47
Had you tried to open any windows/pop-ups that did not appear (preferences, etc.)? These might be unknowingly be taking up memory since they are not actually showing up for the user.

@dusansimic I'm wondering if this is related to the localization issues pertaining to `hide-preferences-window` (#1646), since those modal windows are still opened, but not displayed. In my testing, if you try to open it again, it will add _another_ element instead of reusing the element that is already "open", which could easily use up a lot of RAM.

**Comment by dusansimic** [comment] 2021-06-07 12:23
That might cause a bit more ram usage that usual but I really doubt that just by adding new html elements it can somehow go all the way to 30 GB. AFAIK modals are opened only when user tries to open it (either manually or through some option in the menu bar) so I don't really think this could be the cause of the issue. Messenger.com has been known to use large amounts of ram before, especially with Caprine and to this date (at least for the new design of messenger) I don't know what's the cause of the issue. Nevertheless I'd like to keep an eye on these kind of issues. We could have a memory leak somewhere.

**Comment by CaptainYesz** [comment] 2021-06-08 18:46
I used caprine for years but memory leaks like 6-10 months ago happened and it started being an issue so I had to switch to the official messenger desktop app... not as good functionality wise (like SEEN timestamps) but this is how bad it is.

You guys definitely have some sort of resource issue going on, no ill will - just stating facts.

**Comment by ritchielrez** [comment] 2021-08-01 06:50
Also hight memoey usage in idle times. Like about 300 mb.

**Comment by lefterisgar** [comment] 2022-08-06 13:17
Closing, as it will probably be fixed in the next release.

**Closed by lefterisgar** 2022-08-06 13:17 UTC
