### ISSUE TITLE
after a reboot, caprine opens blank

### ISSUE THREAD

**Issue by 639me** [sindresorhus/caprine#1339] opened 2020-04-17 19:48 UTC
completely white! restarting caprine it's still blank

---

Caprine 2.45.0
Electron 8.2.1
darwin 19.4.0
Locale: en-GB

**Comment by rhysinku** [comment] 2020-04-29 04:46
same here.. but sometimes restarting my pc help for me

**Comment by dusansimic** [comment] 2020-10-30 21:46
Duplicate of #1404

**Closed by dusansimic** 2020-10-30 21:46 UTC
