### ISSUE TITLE
FIX changing text size menuoptions nor keyboard shortcuts do not work

### ISSUE THREAD

**Issue by allanlaal** [sindresorhus/caprine#1463] opened 2020-12-09 18:50 UTC
1. open caprine
2. click on  View→"increase/decrease text size" menuoptions

nothing happens

---

Caprine 2.51.2
Electron 10.1.5
linux 5.8.0-29-generic
Locale: en-US

prolly not a reappearance of https://github.com/sindresorhus/caprine/issues/926 since a normal single click on a menu option does not work

**Comment by dusansimic** [comment] 2020-12-09 19:28
Hi! Do any other Caprine features work (dark mode, other shortcuts) or is it just the increase/decrease text size feature?

**Comment by n3a9** [comment] 2020-12-10 01:02
Same thing here – keyboard short cuts (conversation switching, text size change) don't work. Neither does dark mode or vibrancy. 

---
Caprine 2.51.1
macOS Big Sur

**Comment by mattnoir** [comment] 2020-12-10 06:59
Same here, dark mode gone this morning, keyboard shortcuts doing nothing, text resize doing nothing, sidebars doing nothing.
I get that messenger needs to update their UI, but why won't they at least stop sucking so much. Caprine has many superior features

Caprine 2.51.2
Windows 10
(not that these matter atm)

**Comment by dusansimic** [comment] 2020-12-10 07:33
Since this issue is related to the messenger ui update, it's a duplicate of #1439

**Closed by dusansimic** 2020-12-10 07:33 UTC
