### ISSUE TITLE
Feature Request: Proxy Settings

### ISSUE THREAD

**Issue by reece146** [sindresorhus/caprine#1302] opened 2020-03-14 18:48 UTC
Just discovered this app. It works quite nice; looks good on my Linux box. 

Would it be possible to incorporate a proxy setting menu in File -> Caprine Settings ?

This way it would be possible to route the Caprine Messenger traffic through a local VPN proxy or similar.

In the meantime does Caprine respect http[s]_proxy environment variables? I could wrap it in a shell script for now.

Thanks.

**Comment by lefterisgar** [comment] 2022-08-05 17:06
Duplicate of #1399.

**Closed by lefterisgar** 2022-08-05 17:06 UTC
