### ISSUE TITLE
General interface bugs

### ISSUE THREAD

**Issue by djvar94** [sindresorhus/caprine#1516] opened 2021-01-03 19:24 UTC
Oh goodness, where do I start?
Right ok, I am on Ubuntu MATE 20.04.1 and in Caprine (snap) the Dark mode doesn't work anymore....also selecting any options like increase/decrease text size or reset text size doesn't do anything at all, as well as hide names and avatars, and toggle chat buttons.
Overall the app feels very messy at the moment and it definitively needs a lot of improvements on these regards.

Please fix, thank you very much.

---

Caprine 2.51.2
Electron 10.1.5
linux 5.4.0-53-generic
Locale: en-GB

**Comment by dusansimic** [comment] 2021-01-04 11:57
Duplicate of #1439

**Closed by dusansimic** 2021-01-04 11:57 UTC
