### ISSUE TITLE
Open links in a default browser

### ISSUE THREAD

**Issue by Lastaapps** [sindresorhus/caprine#2010] opened 2023-04-29 22:26 UTC
Hi, would it be please possible to open links in the default system browser and not in Caprine (a new window opens with the page)? Or could you add an option to turn it on? When I click on a link in a chat I want to use my main browser fully (e.g. if I am logged into a service, I can go straight in, use dark mode, ...).

This used to work for me but stopped ~half a year ago.

Arch Linux
Gnome 43

Thank you for your effort and great project!

**Comment by dusansimic** [comment] 2023-04-29 22:27
Duplicate of #1982

**Closed by dusansimic** 2023-04-29 22:27 UTC
