### ISSUE TITLE
Blank Window Upon Launch

### ISSUE THREAD

**Issue by pissywissygal** [sindresorhus/caprine#1402] opened 2020-08-21 16:10 UTC
It launches just fine but doesn't load anything. Just a blank window. Killed the processes related to Caprine, restarted the computer, uninstalled/reinstalled. Can't seem to fix it with the usual approaches. 

---

Caprine 2.48.0
Electron 9.0.5
linux 5.4.0-42-generic
Locale: en-US

**Comment by dusansimic** [comment] 2020-10-29 23:26
Duplicate of #1404

**Closed by dusansimic** 2020-10-29 23:26 UTC
