### ISSUE TITLE
Intermittent problem with notifications [Mac OS Mojave 10.14.3]

### ISSUE THREAD

**Issue by jpanak** [sindresorhus/caprine#780] opened 2019-02-13 16:59 UTC
I have a problem with notifications overall, not sure where the problem is yet. When I choose 'alerts' instead of 'banners' it seems it's working for now

**Comment by CvX** [comment] 2019-02-13 20:36
The issues you’re having maybe be caused by a bug described in https://github.com/sindresorhus/caprine/pull/726#issuecomment-457942388. These will be solved when #726 is merged.

**Closed** 2022-11-05 09:42 UTC
