### ISSUE TITLE
Block seen indicator didn't work.

### ISSUE THREAD

**Issue by Perzot** [sindresorhus/caprine#1469] opened 2020-12-11 02:12 UTC
Anyone know how to fix this? Dark Mode has also stopped working.

**Comment by rhysinku** [comment] 2020-12-11 13:17
same here dude i try downgrading it and still dont work

**Comment by dusansimic** [comment] 2020-12-11 16:21
This is probably due to Messenger redesigning their UI. If those issues still occur once we fix those issues, please report it again.

**Comment by dusansimic** [comment] 2020-12-11 16:21
Duplicate of #1439

**Closed by dusansimic** 2020-12-11 16:21 UTC
