### ISSUE TITLE
Empty white window

### ISSUE THREAD

**Issue by marekop** [sindresorhus/caprine#1401] opened 2020-08-21 15:18 UTC
After latest update i can see wite empty Caprine window only. I'm using Ubuntu 20.04 system.

---

Caprine 2.48.0
Electron 9.0.5
linux 5.4.0-42-generic
Locale: en-US

**Comment by dusansimic** [comment] 2020-10-29 23:29
Duplicate of #1404

**Closed by dusansimic** 2020-10-29 23:29 UTC
