### ISSUE TITLE
Broken options in "View"

### ISSUE THREAD

**Issue by SirAnxious** [sindresorhus/caprine#2016] opened 2023-05-01 16:33 UTC
View > Show Active Contacts
View > Show Message Requests
View  > Show Hidden Threads

First and last ones open links to external browser.
Show Message Requests dims the screen and shows "Give feedback to Messenger"

> Caprine 2.57.3
> Electron 24.1.3
> win32 10.0.19044
> Locale: en-US

**Comment by dusansimic** [comment] 2023-05-06 07:48
Duplicate of #1984

**Closed by dusansimic** 2023-05-06 07:48 UTC
