### ISSUE TITLE
Dark Mode Not Working

### ISSUE THREAD

**Issue by Zhurama** [sindresorhus/caprine#1501] opened 2020-12-18 23:19 UTC
Ctrl+D and also Menu bar>View>Dark Mode only enables a black menu bar or disables. The main window no longer switches

---

Caprine 2.51.2
Electron 10.1.5
win32 10.0.19042
Locale: en-US

**Comment by dusansimic** [comment] 2020-12-18 23:27
Duplicate of #1439

**Closed by dusansimic** 2020-12-18 23:27 UTC
