### ISSUE TITLE
Emoji popup window does not close

### ISSUE THREAD

**Issue by thagorastos** [sindresorhus/caprine#689] opened 2018-12-22 17:19 UTC
There are times when the emoji pop-up window does not automatically close whether you insert an emoji or click elsewhere in the app. This does not happen when firstly opening the app but after a lot of sleep-wake cycles. Refreshing by Cmd+R seems to fixe the issue.

---

Caprine 2.22.1
Electron 3.0.9
darwin 18.2.0
Locale: en-GB

**Comment by dotpointer** [comment] 2019-02-06 16:44
This has happened to me as well, several times in 2.22.1 but also in 2.27.1 in Debian 9 today.

To me it is like the button is somewhat inverted in the way it reacts and should react. The emoji popup does not appear when the smiley-icon is clicked. Then it appears after focusing and typing in the text field. Emojis can be selected after the appearance, but then the emoji popup is stuck.

**Comment by dusansimic** [comment] 2019-02-08 10:06
Also happens on Ubuntu 18.10 with Gnome 3.30.1. Seems like it happens only when I use `Ctrl`+`E` shortcut to open emoji popup window.

**Comment by derekhendrickx** [comment] 2019-03-05 16:15
This happens to me as well on macOS Mojave 10.14.3.

**Comment by jishaal** [comment] 2019-03-26 07:59
Is this a Facebook/Messenger bug rather than that a bug in Caprine? I find I have the same issue on messenger.com sometimes

**Comment by whitecrownclown** [comment] 2019-06-24 22:02
Duplicate of https://github.com/sindresorhus/caprine/issues/831

**Comment by whitecrownclown** [comment] 2019-06-24 22:23
We've recently merged a fix for https://github.com/sindresorhus/caprine/issues/831 . I think it might be the same issue.

**Closed** 2019-07-01 00:28 UTC
Labels: bug
