### ISSUE TITLE
Proposal : ⌘R to refresh

### ISSUE THREAD

**Issue by tristanlepachyderme** [sindresorhus/caprine#143] opened 2016-11-29 15:43 UTC
Hello,

It would be so lit if we could have a option to refresh the interface because when the computer wake up from sleep mode, it doesn't synchronise anymore. And why not automatise this refresh ?

Thanks :)

#103

**Comment by sindresorhus** [comment] 2016-11-29 15:50
I've noticed this too, but I would rather fix the sync problem than adding refresh. Help welcome.

**Comment by sander85** [comment] 2017-01-19 16:21
I've submitted a pull request ( #160 ) to have such option until the real problem is fixed. Lack of such option makes me consider other projects as the problem is becoming really annoying.

**Comment by sindresorhus** [comment] 2017-01-19 17:11
Forgot to close this. Cmd/Ctrl+R works in the latest version.

**Closed by sindresorhus** 2017-01-19 17:11 UTC
Labels: bug, help wanted

**Comment by SofusA** [comment] 2017-02-02 14:55
I have basically no experience in coding so please excuse me if this is stupid.
Could this problem be solved by using something like: 
If systemresume then refresh?

It might be possible with [powerMonitor](electron powerminotor)

**Comment by danhp** [comment] 2017-02-02 18:09
It's not that easy since the app depends on having an internet connection.
