### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [sindresorhus/caprine#1262] opened 2020-01-30 21:35 UTC
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Caprine on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by sindresorhus** [comment] 2020-01-31 03:59
Duplicate of https://github.com/sindresorhus/caprine/issues/577

**Closed by sindresorhus** 2020-01-31 03:59 UTC
