### ISSUE TITLE
Desktop notifications, and Messenger Settings don't show

### ISSUE THREAD

**Issue by Skivster** [sindresorhus/caprine#911] opened 2019-05-27 07:57 UTC
Like in the title, desktop notifications, and Messenger Settings don't show, and there is no way to make them working.
Can't find a setting to turn on/off notifications. 
Shortcut `ctrl + ,` doesn't do anything, nor clicking "Messenger Settings" in the dropdown menu.
Caprine 2.31.1
Windows 7 x64.. Dont know what more should I post here..

**Comment by reganlawton** [comment] 2019-05-28 01:54
Confirm that is the case on Mac OS 10.14.5 as well

**Comment by jonyroda97** [comment] 2019-05-28 02:15
same with the message requests, archived threads, etc.

**Comment by reganlawton** [comment] 2019-05-28 04:39
I have a change to restore settings and read badge, code was commented out in the last version but the notifications still aren't triggering 🤔

**Comment by eexit** [comment] 2019-05-28 11:34
Confirmed as well on macOS 10.14.4.

**Comment by minhkhuong2404** [comment] 2019-05-28 14:52
confirmed on macOS 10.14.2

**Comment by reganlawton** [comment] 2019-05-30 04:09
There is a PR #908 which ended up being very close / basically the same to the fixes I made to my local compiled version. 

Upvote it 👍

**Comment by reganlawton** [comment] 2019-05-30 04:34
Settings menu should be resolved in my PR #916 my testing found that it was due to a messing selector. My desktop notifications issue was due to them being disabled, as I was in do not disturb mode 🤦‍♂

**Comment by sindresorhus** [comment] 2019-05-30 05:32
Notifications were fixed in #893.

**Comment by reganlawton** [comment] 2019-05-30 05:36
@sindresorhus Im taking that was the Version 2.31.1 release? Either way they were working for me in 2.31.1, once I disabled DND mode. The PR I submitted is just a selector change to fix menu.

**Comment by sindresorhus** [comment] 2019-05-30 05:55
> The PR I submitted is just a selector change to fix menu.

The Settings menu is already working with the new design.

**Comment by reganlawton** [comment] 2019-05-30 06:02
@sindresorhus I have the update to support both.

**Comment by sindresorhus** [comment] 2019-05-30 06:08
I'm not interested in supporting both. Most users are on the new design now.

**Comment by CvX** [comment] 2019-05-30 15:00
> Most users are on the new design now.

Are they? 🙂 I'm still on the old design, so are some people from my contacts list I've asked. Facebook is taking a multi-month rollout approach on this one. 😛

**Comment by jonyroda97** [comment] 2019-05-30 21:00
the problems still exist on <code>v2.31.2</code>

**Comment by reganlawton** [comment] 2019-05-30 21:07
@jonyroda97 it’ll continue regardless of the version it’s not a app issues, Facebook are rolling out different version of HTML with different selectors so the new selector trigger doesn’t work for people that Facebook hasn’t rollouts the new design out too yet, which seems to be quite a few people. 

It most likely a region based rollout so hopefully everyone should be switched over in the next week or so.

**Comment by Skivster** [comment] 2019-05-30 21:09
So wait, let me get this straight. Messenger setting not showing, nor desktop notifications, are because of the HTML/UI changes that are not yet rolled out in my region?

**Comment by reganlawton** [comment] 2019-05-30 21:14
More or less but notifications were fixed in #893 so mentioned above.

**Comment by Skivster** [comment] 2019-05-30 21:17
Good news. So, how should I know that FB finally updated messenger in my region? What are the symptoms, and whatnot? Notifications should start showing?
Im simply curious :)

**Comment by CvX** [comment] 2019-05-30 21:20
@Skivster Here's a side-by-side comparison of both old and new design: [commit 15fc43b](https://github.com/sindresorhus/caprine/commit/15fc43b1e5fa8bb64771c923993fe09a7e56726b?diff=unified&short_path=a49b5ad#diff-a49b5adb5b6b0ae6e07009d11c23f220)

**Comment by Skivster** [comment] 2019-05-30 21:24
:O Thanks for the screens ;)
So, Full Colour "phone" icons, Bold Icons on the left, and User Name moved to the left. Thanks, I'll watch when it changes, and I'll make an update when time comes. Thanks!

**Closed** 2019-06-14 11:28 UTC

**Comment by Skivster** [comment] 2019-06-14 14:03
Can confirm, new update fixed a lot of bugs. ctrl+ , notifications, forwarding messages and everything else. 
Also, the notifications are better looking and working than in Messenger for Desktop. Thank you all for your hard work :)

**Comment by erikstorli** [comment] 2019-11-29 11:40
I'm sorry to comment on this old issue, but I'm not able to open settings at all. Version 2.4.1.
It works with my work iMac (late 2015) 10.15.1, but not with a brand new MacBook Pro 16-inch 10.15.1. Any suggestions on how to debug this? Tried the menu and shortcut. No go.
