### ISSUE TITLE
Tray Icon

### ISSUE THREAD

**Issue by davidian-sk** [sindresorhus/caprine#1818] opened 2022-04-16 10:16 UTC
Hello, would it be possible to add new message notifications also to the tray icon?

**Comment by ThePhOeNiX810815** [comment] 2022-04-16 12:33
Hello.
It would be great to show different tray icon which indicates unread message(s) / missed call(s).
The point is to immediately notify user of missed stuff, without need of any action on desktop.

**Comment by lefterisgar** [comment] 2022-08-24 13:07
Closing as duplicate of #1823.

**Closed by lefterisgar** 2022-08-24 13:07 UTC
