### ISSUE TITLE
unseen feature is not working!!

### ISSUE THREAD

**Issue by github-raiyan** [sindresorhus/caprine#1561] opened 2021-02-16 16:02 UTC
These features are not working.
* Block seen.
* Block delivery.

---

Caprine 2.52.0
Electron 10.1.5
linux 5.4.0-62-generic
Locale: en-US

**Comment by dusansimic** [comment] 2021-02-17 09:38
Duplicate of #1503

**Closed by dusansimic** 2021-02-17 09:38 UTC
