### ISSUE TITLE
app refuses to "Sync now" regardless of my many attempts

### ISSUE THREAD

**Issue by gregmbrown** [sindresorhus/caprine#2200] opened 2024-07-06 04:11 UTC
I have tried repeatedly to sync at least 2 conversation streams that I have, and they have failed to sync. The app keeps telling me to "Sync now". I'm ready to uninstall your app and install something else if this can't be rectified. Please help.

---

Caprine 2.59.3
Electron 25.9.8
linux 6.8.0-36-generic
Locale: en-US

**Comment by mquevill** [comment] 2024-07-08 17:58
Duplicate of #2167

**Closed by mquevill** 2024-07-08 17:58 UTC
