### ISSUE TITLE
Cannot launch Snap

### ISSUE THREAD

**Issue by yerbestpal** [sindresorhus/caprine#1077] opened 2019-09-05 19:57 UTC
The Snap build currently will not launch on my desktop. When I run it through the terminal, I get the following output:

```
(caprine:22613): Gtk-WARNING **: 20:53:47.276: Failed to parse /home/ross/snap/caprine/28/.config/gtk-3.0/settings.ini: Permission denied
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/ross/snap/caprine/28/.config/Caprine/config.json.293450316'
    at Object.chownSync (fs.js:1104:3)
    at Function.writeFileSync [as sync] (/snap/caprine/28/resources/app.asar/node_modules/conf/node_modules/write-file-atomic/index.js:196:27)
    at ElectronStore.set store [as store] (/snap/caprine/28/resources/app.asar/node_modules/conf/index.js:277:19)
    at ElectronStore.set (/snap/caprine/28/resources/app.asar/node_modules/conf/index.js:152:14)
    at updateVibrancySetting (/snap/caprine/28/resources/app.asar/dist-js/config.js:155:15)
    at migrate (/snap/caprine/28/resources/app.asar/dist-js/config.js:165:5)
    at Object.<anonymous> (/snap/caprine/28/resources/app.asar/dist-js/config.js:168:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[22613:0905/205348.390727:FATAL:memory.cc(22)] Out of memory. size=131072
Trace/breakpoint trap

```

and if I run with elevated privileges, I get the following:

`mkdir: cannot create directory '/run/user/0': Permission denied
`

**Comment by dbisk** [comment] 2019-09-07 23:58
I think this is a duplicate of #1062 .

**Comment by sindresorhus** [comment] 2019-09-09 10:56
Duplicate of #1062

**Closed by sindresorhus** 2019-09-09 10:56 UTC
