### ISSUE TITLE
Caprine features have stopped working

### ISSUE THREAD

**Issue by BorisitoT** [sindresorhus/caprine#1490] opened 2020-12-17 13:05 UTC
Hello, this morning I have noticed several issues with Caprine desktop client (Windows 10, 64-bit), probably the side effect of the latest update.
![2020-12-17 13_55_32-Window](https://user-images.githubusercontent.com/76165480/102491087-00de1000-4070-11eb-9d34-e66b9d712029.png)
As you can see in the picture, the Dark mode deosn't work, font size has reverted back to the default value and cannot be changed, no keayboard shortcut works anymore (Ctrl + Tab, Ctrl + Shift + Tab, Ctrl + G, Ctrl + S etc.) and the systray icon doesn't turn blue upon receiving a new message. I am hoping for some feedback from your team regarding the issue (if replying is your standrad practice, that is) and when we can expect it to get fixed.

Thanks,

Boris
---

Caprine 2.51.2
Electron 10.1.5
win32 10.0.18363
Locale: en-US

**Comment by dusansimic** [comment] 2020-12-17 14:16
Duplicate of #1439

**Closed by dusansimic** 2020-12-17 14:16 UTC
