### ISSUE TITLE
notification stays

### ISSUE THREAD

**Issue by 639me** [sindresorhus/caprine#1322] opened 2020-04-04 17:56 UTC
when i've read and even answered a message, that's not pushed to notifications. the notification stays. i would expect the same as with apple messages, where the notification disappears

---

Caprine 2.44.0
Electron 8.0.0
darwin 19.3.0
Locale: en-GB

**Comment by dusansimic** [comment] 2022-11-06 09:49
Duplicate of #1329

**Closed by dusansimic** 2022-11-06 09:49 UTC
