### ISSUE TITLE
removed, forward, ignore, mute, nickname button not working and not view images 

### ISSUE THREAD

**Issue by shobuj-das** [sindresorhus/caprine#1758] opened 2021-12-07 14:37 UTC
I'm using caprine 2.55.1 in ubuntu and it's removed, forward, ignore, mute, nickname button not working, and not view images
---

Caprine 2.55.1
Electron 10.4.7
linux 5.11.0-41-generic
Locale: en-US

**Comment by dusansimic** [comment] 2021-12-08 08:40
Duplicate of #1753

**Closed by dusansimic** 2021-12-08 08:40 UTC
