### ISSUE TITLE
System Tray Icon Inert

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1593] opened 2021-03-20 15:48 UTC
The System Tray Icon neither gives Visual or Audio Notification.
And Video Autoplays. Can live with 2nd issue, but not 1st one.
Thank you for your kind attention. Ciao.
Caprine 2.52.2
Electron 10.1.5
win32 6.1.7601
Locale: en-US

**Comment by dusansimic** [comment] 2021-03-24 08:38
Notifications issue is a duplicate of #1562.

We are aware of autoplay issue (https://github.com/sindresorhus/caprine/issues/1439#issuecomment-769858462) but it's not being worked on right now.

**Closed by dusansimic** 2021-03-24 08:38 UTC
