### ISSUE TITLE
[Manjaro] app just stops working.

### ISSUE THREAD

**Issue by wildcard-f8** [sindresorhus/caprine#1915] opened 2022-09-16 11:53 UTC
Open the app, send a few messages then it just stops working.

**Comment by PixsaOJ** [comment] 2022-09-16 12:02
Does it freeze? Can you access the top menu? Does it happen after you receive a message?

**Comment by PixsaOJ** [comment] 2022-09-16 13:45
> Same issue, happens after receiving a message and the message will not appear, top menu is still functional, just the messenger part is frozen.

That would be a duplicate of #1878

**Comment by wildcard-f8** [comment] 2022-09-17 06:19
It works fine for a few minutes then it just freezes. I can't access anything. The only thing I can do is minimize the app to the panel by clicking on the x button. I can show the app again by clicking on the panel icon and clicking toggle. I can click on the panel icon and click quit and quits normally. but the rest of the app just becomes unclickable.

**Comment by wildcard-f8** [comment] 2022-09-17 08:29
I have an update. So i tried tinkering around with the the settings and i eventually tried NOT auto hiding the menu bar. I'm not sure but turning this feature off seems to have stopped the crashing. So far it seems to be the case.

**Comment by PixsaOJ** [comment] 2022-09-17 08:31
> I have an update. So i tried tinkering around with the the settings and i eventually tried NOT auto hiding the menu bar. I'm not sure but turning this feature off seems to have stopped the crashing. So far it seems to be the case.

I think that's false positive. Wait for another 4 hours.

**Comment by wildcard-f8** [comment] 2022-09-17 08:37
> > I have an update. So i tried tinkering around with the the settings and i eventually tried NOT auto hiding the menu bar. I'm not sure but turning this feature off seems to have stopped the crashing. So far it seems to be the case.
> 
> I think that's false positive. Wait for another 4 hours.

Yeah it could be. By the way, I forgot. I also turned off hardware acceleration.

**Comment by PixsaOJ** [comment] 2022-09-17 08:37
I tried both of those, but no results.

**Comment by wildcard-f8** [comment] 2022-09-17 08:51
> I tried both of those, but no results.

Sorry about that. Mine still seems to be working now. I'll keep monitoring if it freezes again.

**Comment by dusansimic** [comment] 2022-09-17 10:39
Duplicate of #1878

**Closed by dusansimic** 2022-09-17 10:39 UTC

**Comment by PixsaOJ** [comment] 2022-09-17 10:40
@dusansimic It might not be, he did not say it's on message received.
