### ISSUE TITLE
Notifications no longer are working

### ISSUE THREAD

**Issue by LinuxFanboy745** [sindresorhus/caprine#1506] opened 2020-12-22 19:09 UTC
I'm not longer getting notifications nor the message preview pop-up. Just the sound. 

Fedora 33, running the latest version of Caprine deb converter to rpm using alien, its not my rpm converter, I know that for a fact.

**Comment by dusansimic** [comment] 2020-12-22 20:12
Duplicate of #1439

**Closed by dusansimic** 2020-12-22 20:12 UTC
