### ISSUE TITLE
Minor issue: control enter

### ISSUE THREAD

**Issue by tjanos2000** [sindresorhus/caprine#1508] opened 2020-12-23 09:01 UTC
Dear People,

<Control> <enter> does not work anymore withe the new installation:
caprine_2.51.2_amd64.deb

Please let me know if there is a solution.

Kind regards
Janos

---

Caprine 2.48.0
Electron 9.0.5
linux 5.4.0-53-generic
Locale: en-GB

**Comment by dusansimic** [comment] 2021-01-30 17:48
Hi! I'm not sure what you mean by "control enter". If you mean that you can't send messages by clicking control enter, it is working for me on the latest version (v2.52). If you mean you can create a new line in the message, it is done by clicking Shift+Enter. If you mean "control center" instead of "control enter", notifications are not implemented on messenger website for the new design. This is a flaw of the new design which we can fix since we just pass the notifications from the website to the operating system.

**Comment by tjanos2000** [comment] 2021-01-31 06:10
Hi Dušan
Thank you for your response.
I had no problem sending messages, just inserting a new line without sending them.  Your answer Shift+Enter is the solution I was after.  Mind you Control+Enter used to work in older versions.
Thanks again!
Best regardsJanos
---    On Sunday, 31 January 2021, 04:48:38 am AEDT, Dušan Simić <notifications@github.com> wrote:  
 
 


Hi! I'm not sure what you mean by "control enter". If you mean that you can't send messages by clicking control enter, it is working for me on the latest version (v2.52). If you mean you can create a new line in the message, it is done by clicking Shift+Enter. If you mean "control center" instead of "control enter", notifications are not implemented on messenger website for the new design. This is a flaw of the new design which we can fix since we just pass the notifications from the website to the operating system.

**Comment by dusansimic** [comment] 2021-01-31 10:45
I probably did work on old messenger design however I think it's expected behaviour for Ctrl+Enter to send a message and Shitf+Enter to create a new line. That's what my experience is (it's like that on Slack, Microsoft Teams and may other messaging platforms).

Since this is resolved, I'll close the issue.

**Closed by dusansimic** 2021-01-31 10:45 UTC
