### ISSUE TITLE
Can't view images

### ISSUE THREAD

**Issue by yanazPL** [sindresorhus/caprine#1748] opened 2021-12-03 14:42 UTC
After clicking image (from conversation) I can't see anything
There is similar issue here: https://github.com/sindresorhus/caprine/issues/1449
I don't think it's on fb's side - I have no problems with viewing images if I open facebook using firefox 
![obraz](https://user-images.githubusercontent.com/7052262/144620134-0fc12719-0ba2-4e65-abf3-3a4ee3d70a71.png)

Linux Mint 20.2 Uma
Caprine 2.55.1

**Comment by tinmanjk** [comment] 2021-12-05 04:46
Same here on Windows, unfortunately. Must have been something from 2.55 > 2.55.1

**Comment by dusansimic** [comment] 2021-12-07 08:36
Duplicate of #1751

**Closed by dusansimic** 2021-12-07 08:36 UTC
