### ISSUE TITLE
Can't delete msgs

### ISSUE THREAD

**Issue by tcamp17** [sindresorhus/caprine#2057] opened 2023-09-05 14:26 UTC
---

Caprine 2.58.0
Electron 24.1.3
linux 5.4.0-162-generic
Locale: en-US

**Comment by tcamp17** [comment] 2023-09-05 14:26
prior msgs will not be deleted

**Comment by dusansimic** [comment] 2023-09-06 10:33
Duplicate of #2055

**Closed by dusansimic** 2023-09-06 10:33 UTC
