### ISSUE TITLE
Messenger preferences and Notifactions option not pop up

### ISSUE THREAD

**Issue by ookangzheng** [sindresorhus/caprine#924] opened 2019-06-01 08:42 UTC
https://want2.be/caprine-problem.mp4
Example ~~

**Comment by reganlawton** [comment] 2019-06-05 23:17
This is a dupe of #911 which is because like myself your Facebook isn't updated to the new UI change yet.

**Closed** 2019-06-06 13:35 UTC

**Comment by ookangzheng** [comment] 2019-06-29 15:03
Hmm, since It works for couple days, but starting from yesterday, I cant use cmd+, again to open up "Preferences" dialog window

**Comment by CvX** [comment] 2019-06-29 15:07
2.33.1?
