### ISSUE TITLE
"Block Seen Indicator" doesn't work.

### ISSUE THREAD

**Issue by shmishkat** [sindresorhus/caprine#1675] opened 2021-07-31 07:09 UTC
The privacy feature especially the "Block Seen Indicator" doesn't work. 
The other two privacy features seem to work fine. 
Any possible solution?

Caprine v2.53.0
macOS Big Sur 11.5.1

**Comment by dusansimic** [comment] 2021-07-31 09:32
Duplicate of #1503

**Closed by dusansimic** 2021-07-31 09:32 UTC
