### ISSUE TITLE
Dark-mode glitching; white background

### ISSUE THREAD

**Issue by dantveita** [sindresorhus/caprine#1809] opened 2022-04-08 10:41 UTC
Yesterday, darkmode started acting up (see screenshot). It "fixes itself" if I scroll up and back down. But once I send a new chat bubble (or receive one), the background goes white. Tried reinstalling, to no avail (2.55.4). Lightmode works correctly.
![Untitled-1](https://user-images.githubusercontent.com/13351909/162420081-32ce4332-9f9a-4bff-85c6-5f867afd8ad3.jpg)

**Comment by brian-perlego** [comment] 2022-04-08 14:24
While this is getting fixed, you can press the emoji icon to fix the current viewport

**Comment by fleetwoodmac** [comment] 2022-04-19 00:52
just wanted to echo that I am also having this issue.

**Comment by RaiGal** [comment] 2022-04-24 11:39
This is happening to me as well on Linux Mint 20.1 (2.52.4 - latest version from snap store)

**Comment by huy-vuong** [comment] 2022-05-01 20:07
I'm seeing this on macOS as well on 2.55.4.

**Comment by RaiGal** [comment] 2022-05-02 09:09
I would like to point out that this issue was fixed on version v2.55.4 (for ubuntu linux). However, the current version on snap store (which hasn't been updated) is 2.52.4 which still has this issue. Therefore, any users who download the version from the snap store will have this issue.

**Comment by cosmincrihan** [comment] 2022-05-03 11:36
The issue arose at some point after version 2.55.4 has been released, so the version alone could not contain the fix.
At least for me, version 2.55.4 (latest) still has the dark mode glitches.

**Comment by lefterisgar** [comment] 2022-05-09 11:30
Hi! Could you please test [my fork](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-5) and see if this issue persists (I can't reproduce it)? If the issue is fixed then the fix will likely be included in the next official release.

**Comment by drewclauson** [comment] 2022-05-10 19:45
> Hi! Could you please test [my fork](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-5) and see if the issue persists? I can't reproduce it. If the issue is fixed then the fix will likely be included in the next official release.

I pulled this down and the white background issue is fixed for me!

**Comment by Botspot** [comment] 2022-06-17 15:52
Same problem here.
![2022-06-17-104744_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/174332905-fd8f736a-366a-44aa-b6b2-1f7b50af2cd4.png)
When can this be looked into, @sindresorhus @mquevill?
@lefterisgar, would you consider opening a pull request to fix this on main?

**Closed** 2022-06-17 16:04 UTC

**Comment by Botspot** [comment] 2022-06-17 16:27
> I believe this should have been fixed as of version 2.55.5. Please check which version you are using, and upgrade if necessary. (Current released version is v2.55.6.)
> 
> Unfortunately, Messenger makes quite a few backend changes that end up breaking current versions. Reverting to older versions of Caprine won't fix them since we cannot force an older backend version.

That would explain it. I've been using version 2.55.0.
