### ISSUE TITLE
Menu bar doesn't work

### ISSUE THREAD

**Issue by MaciejWitkowskiDev** [sindresorhus/caprine#1519] opened 2021-01-06 08:51 UTC
I installed Caprine using pacman -S caprine.
The menu bar does not seem to do anything. It doesn't even allow me to logout.
The native functions work - so I am able to go into Caprine settings, but the messenger website itself does not seem to respond to other options.

---

Caprine 2.51.2
Electron 11.1.0
linux 5.4.85-1-MANJARO
Locale: en-US

**Comment by dusansimic** [comment] 2021-01-06 12:19
Duplicate of #1439

**Closed by dusansimic** 2021-01-06 12:19 UTC

**Comment by charrion** [comment] 2025-01-15 23:15
It's 2025 and this issue has obviously never even been looked at.
