### ISSUE TITLE
Caprine stops showing new messages after a few days. Maybe add an auto refresh to fix this.

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sindresorhus/caprine#1370] opened 2020-05-31 21:56 UTC
After being open for a couple of days, Caprine stops showing new messages. See attached screenshot. The messages I sent in Caprine sent, but they have hollow check marks instead of solid check marks. And the reply that the person sent was not displayed at all.

I believe the connection to Facebook Messenger times out after awhile, and the whole page simply needs a refresh. An easy fix for this would be to just have Caprine silently and automatically refresh every 24 hours.

Messenger For Desktop, the Facebook Messenger program for PC that I used before I switched to Caprine, had the same issue.

![2020-05-31_144529](https://user-images.githubusercontent.com/43397938/83363313-6c1ef980-a34d-11ea-81f5-fb3452fa319f.png)

---

Caprine 2.46.0
Electron 8.2.5
win32 6.1.7601 (Windows 7)
Locale: en-US

**Comment by yllekz** [comment] 2020-06-02 12:09
I've also been having this problem for a while. Also an issue with unread messages never being marked as read but supposedly that was fixed in the latest release.

**Comment by dusansimic** [comment] 2020-10-30 21:33
To avoid accidental refreshing of Caprine during the user writing a message for example, this is avoided. I would recommend refreshing Caprine manually since any other other unexpected behavior (automatic refresh) could result in bad experience.

**Closed by dusansimic** 2020-10-30 21:33 UTC

**Comment by RedDragonWebDesign** [comment] 2020-12-17 21:32
@dusansimic Would you be willing to reconsider? I think the messenger quietly failing after 1 day of being open is a worse experience than internally or externally restarting once a day. No other major messengers quietly fail after 1 day, i.e. Skype, Slack, Discord, etc.

**Comment by dusansimic** [comment] 2020-12-17 21:55
Caprine is not in it self a messenger. It is a wrapper around messenger.com website. This is a messenger.com issue and should be resolved there.

Reason why we won't auto restart after some period of time is described [here](https://github.com/sindresorhus/caprine/issues/103) and also in my comment in this issue. If user is writing a message and it restarts in that moment it results in a bad user experience. Event worse, the user is for example offline an is writing a message, the message draft is not saved without internet connection and if app is restarted it will result in losing everything that was written. This will make more problems than it solves and that's why we don't plan on doing that.

I understand your frustration but we don't want to make more problems that might be more fatal than this one. Compare losing message with ~1000 words to Messenger not showing new messages which can be fixed by using 'Relaunch Caprine' option in file menu. It's not a perfect solution but currently it's the best one we have since this is a problem in Messenger website.
