### ISSUE TITLE
Dark mode disabling after Caprine reboot

### ISSUE THREAD

**Issue by chuy19312** [sindresorhus/caprine#1564] opened 2021-02-23 01:53 UTC
Dark mode disabling after app reboot

Well, after closing and opening Caprine, dark mode option is still enabled but messenger is not on dark mode, i need to disable dark mode and enable dark mode again to make it work, it only happens when closing and opening Caprine again, or when rebooting it, it doesn't happen on anything else

---

Caprine 2.52.0
Electron 10.1.5
win32 6.3.9600
Locale: es

**Comment by dusansimic** [comment] 2021-02-23 08:30
Duplicate of #1525

**Closed by dusansimic** 2021-02-23 08:30 UTC
