### ISSUE TITLE
Rec'd Messages Blank

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1740] opened 2021-12-01 22:58 UTC
Load Caprine. Messages themselves have turned White from Dark Setting.
All Received Messages are blank. Sent by me are normal.

---

Caprine 2.55.0
Electron 10.4.7
win32 6.1.7601
Locale: en-US

**Comment by mquevill** [comment] 2021-12-01 23:08
Duplicate of #1737

**Comment by PreachJohn** [comment] 2021-12-01 23:17
#1737 only mention Colors Broken.
I mention also Received Messages blank.
Overlap, yes. Duplicate, no?

**Comment by mquevill** [comment] 2021-12-01 23:19
Are the messages actually blank? Or white text on white background? Try highlighting where the text should be and the message should still be there. The dark theme normally has light text, but on a light background it's nearly impossible to see.

**Comment by PreachJohn** [comment] 2021-12-01 23:27
Actually blank.
![Screen Shot 12-01-21 at 04 24 PM](https://user-images.githubusercontent.com/31393296/144330529-fdc635ec-ce52-4423-b864-dfafea4e7ca8.PNG)
Cheers

**Comment by dusansimic** [comment] 2021-12-01 23:31
@PreachJohn I think that's actually what Michael was talking about. The messages are not blank, they are just the same color as the background. This issue is caused by colors being broken.

You could select the text of the message, it's there but the color makes it invisible.

**Closed** 2021-12-02 14:50 UTC
