### ISSUE TITLE
New messages not appearing after waking up from sleep

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/caprine#673] opened 2018-12-09 19:25 UTC
I got a message while my laptop was closed (saw the notification on my phone). After over an hour I opened my laptop and the chat with the sender was open, but the new message was not shown, even after waiting a while or switching chats back and forth. Hitting Cmd+R to reload made it show up, but this shouldn't be needed in a native app.

**Comment by sindresorhus** [comment] 2019-02-18 04:38
Duplicate of #103

**Closed by sindresorhus** 2019-02-18 04:38 UTC
