### ISSUE TITLE
Automatic creates video room at startup time

### ISSUE THREAD

**Issue by shobuj-das** [sindresorhus/caprine#1858] opened 2022-07-16 15:43 UTC
it creates a video room every time I open caprine.
on the other hand the option 'Messenger Settings' also creates the video room while clicked.
how to fix it? is there any option to stop creating room while starting?

---

Caprine 2.55.4
Electron 10.4.7
linux 5.15.0-41-generic
Locale: en-US

**Comment by lefterisgar** [comment] 2022-08-06 13:20
Duplicate of #1863.

**Closed by lefterisgar** 2022-08-06 13:20 UTC
