### ISSUE TITLE
Black space above the chat 

### ISSUE THREAD

**Issue by sugat009** [sindresorhus/caprine#1610] opened 2021-04-16 03:27 UTC
![Screenshot_20210416_091136](https://user-images.githubusercontent.com/30311933/114967275-dd976600-9e93-11eb-8ca9-07063a0767e0.png)

---

Caprine 2.52.2
Electron 11.3.0
linux 5.9.16-1-MANJARO
Locale: en-US

**Comment by dusansimic** [comment] 2021-04-16 07:39
Duplicate of #1604

**Closed by dusansimic** 2021-04-16 07:39 UTC
