### ISSUE TITLE
Vibrancy issue, gray sidebar

### ISSUE THREAD

**Issue by hieuhuynh93** [sindresorhus/caprine#712] opened 2019-01-10 02:18 UTC
I didn't use Dark mode and Vibrancy mode, but the sidebar is look like dark mode. Please check my screenshot. Thank you.
![Screenshot](https://i.imgur.com/V8dwnZZ.jpg)

**Comment by dscos** [comment] 2019-01-10 19:53
I am experiencing this same issue, but in reverse: Main window is obeying my dark area selection but the sidebar is light with light text.

**Comment by cocoJambon01** [comment] 2019-01-11 13:01
I have a similar issue I might say. Turning Dark Mode on will neglect the sidebar and only the message box will be black: http://prntscr.com/m5ttm7

**Comment by filipruisl** [comment] 2019-01-11 20:24
same here, however the Sidebar is a Dark vibrant theme with dark text on it.

**Comment by ggrelet** [comment] 2019-01-12 06:03
I have a similar issue, however I don't even have Drak Mode enabled. The white mode's white is simply different in the side bar.
<img width="1072" alt="screenshot_2019-01-12 15-02-25 2x" src="https://user-images.githubusercontent.com/10114131/51069883-263f9380-167b-11e9-96cd-bf73fd74221a.png">

**Comment by cocoJambon01** [comment] 2019-01-14 09:01
Just installed version 2.26 - Issue persists.

**Comment by jackwilsdon** [comment] 2019-01-14 09:22
Yeah I can confirm this is still broken on `master`. This patch seems to fix it but vibrancy mode still doesn't look right with dark mode enabled;

```diff
diff --git dark-mode.css dark-mode.css
index 570862b..344a1f2 100644
--- dark-mode.css
+++ dark-mode.css
@@ -764,8 +764,7 @@ html.os-darwin.dark-mode ._673w {
 }
 
 /* Styles for vibrancy in dark mode */
-html.os-darwin.dark-mode body,
-html.os-darwin.dark-mode ._4sp8 {
+html.os-darwin.dark-mode body {
 	background: transparent !important;
 }
 ```

*Dark Mode*
![Dark Mode](https://user-images.githubusercontent.com/1843197/51104343-d3322180-17dd-11e9-9ae9-5f10b5bfe4db.png)

*Dark Mode + Full-Window Vibrancy*
![Dark Mode + Full-Window Vibrancy](https://user-images.githubusercontent.com/1843197/51104342-d3322180-17dd-11e9-9455-eebc3c8adaf5.png)

**Comment by sindresorhus** [comment] 2019-01-14 09:47
// @CvX

**Comment by hieuhuynh93** [comment] 2019-01-16 08:40
I confirmed that the issue is still not solve yet. (2.26.0)
![Screenshot](https://i.imgur.com/P6oE4le.png)

**Comment by CvX** [comment] 2019-01-16 15:37
I've submitted PR #727 which allows to completely disable vibrancy in case you have any issues with vibrancy or if you just prefer the vibrancy-less look.

@ggrelet, @hieuhuynh93 – the app in your screenshots looks correct, that was the default look since Caprine 2.24.0. After #727 is merged and released you'll be able to go back to pre-2.24 look if you wish (by selecting "View -> Vibrancy -> No Vibrancy")

I'll continue to work on the original issue, I'm currently knee deep in Electron/Chromium code… 😅

**Comment by hieuhuynh93** [comment] 2019-01-19 03:34
Thanks @CvX 
The issue has been solved.
[Imgur](https://i.imgur.com/KvuUqrO.png)

**Comment by rachelyhe** [comment] 2019-03-02 15:18
> This patch seems to fix it but vibrancy mode still doesn't look right with dark mode enabled;

It seems that vibrancy grays out (and is essentially the same gray as vibrancy in Light mode) everything except links at the moment.

![image](https://user-images.githubusercontent.com/32414721/53683887-5ba84b00-3cd4-11e9-82ed-705899bb0430.png)

**Closed** 2019-09-08 17:28 UTC
Labels: bug, waiting for Electron
