### ISSUE TITLE
No notification and no access to preferences

### ISSUE THREAD

**Issue by maximemhd** [sindresorhus/caprine#168] opened 2017-03-02 15:06 UTC
Hello,
I'm on windows 10, and I have no access to preferences, and I don't receive notification. I only have the sound when I get a message.
Is that normal?
Thanks

**Comment by sindresorhus** [comment] 2017-03-02 21:02
Duplicate of https://github.com/sindresorhus/caprine/issues/161.

**Closed by sindresorhus** 2017-03-02 21:02 UTC
