### ISSUE TITLE
"Messages are missing. Sync now." does nothing

### ISSUE THREAD

**Issue by ohshitgorillas** [sindresorhus/caprine#2167] opened 2024-04-23 17:58 UTC
For end-to-end encrypted chats, which require the new Facebook Messenger pin number to be entered to view the chats, the "Sync now" feature does not work--nothing happens when I click it. As a result, all encrypted chats are missing up to the point at which Caprine was installed.

Caprine 2.60.1
Pop!_OS 22.04 LTS
Linux 6.8.0-76060800daily20240311-generic

**Comment by KabaleTech** [comment] 2024-04-26 08:55
Same issue

Fedora Linux 40 (Workstation Edition)
kernel : 6.8.7-300.fc40.x86_64
Caprine 2.60.1

**Comment by TheMightyPengu** [comment] 2024-04-27 20:53
Same issue
Manjaro Linux x86_64 (unstable branch)
Kernel 5.15.156-1-MANJARO
Caprine 2.60.1 (flatpak and AUR)

**Comment by forestcall** [comment] 2024-05-01 00:10
I am able to get the 1-time code but where to enter the 1-time code? Seems we need a UI with a form field to add the 'security code'.

**Comment by mquevill** [comment] 2024-05-02 01:59
This is due to the `hide-preferences-window` class that has been used, since it also ends up hiding the PIN window (and other windows like "Security Alerts", etc.). When Facebook makes backend changes, this is often one part of Caprine that breaks. And when that class doesn't get removed as expected, it prevents any of these types of pop-up windows from showing.

_A temporary workaround:_ If you access the developer tools via F12, you can edit the main `<html>` element to remove the `hide-preferences-window` class from the list within `class="..."`.

**Comment by dcargonaut** [comment] 2024-07-31 17:28
Same issue with Windows port.

**Comment by vampyre2000** [comment] 2024-10-05 05:17
> This is due to the `hide-preferences-window` class that has been used, since it also ends up hiding the PIN window (and other windows like "Security Alerts", etc.). When Facebook makes backend changes, this is often one part of Caprine that breaks. And when that class doesn't get removed as expected, it prevents any of these types of pop-up windows from showing.
> 
> _A temporary workaround:_ If you access the developer tools via F12, you can edit the main `<html>` element to remove the `hide-preferences-window` class from the list within `class="..."`.

This worked for me as well. Thank you so much you have saved my sanity

**Comment by ShadowDrakken** [comment] 2024-10-17 19:05
hide-preferences-window seems to serve no purpose. It blocks the "Messenger Preferences" menu item as well as the PIN input, and doesn't seem to provide any real benefit. If the project ever comes back to life it would be nice to see it removed.

**Comment by Zennwah** [comment] 2024-11-15 01:32
Deleting `hide-preferences-window` used to be permanent for me. For some time now it comes back after restarting Caprine. What could be the issue?

**Comment by semikolon** [comment] 2024-11-15 20:44
How can I help with this? What needs to be changed?

**Comment by SilverSaw** [comment] 2024-11-16 13:50
@semikolon 
![Capture](https://github.com/user-attachments/assets/118db71c-1fe6-4a98-a488-870d5fa6970a)

Click F12 to see this `hide-preferences-window` from the main <html> element `class="..."` Caprime must be forced to remove it permanently on start because when we remove it manually, it comes back after restarting the caprine. It blocks the sync function and historical messages from other devices are not available, also it blocks pin authentication. We do not see any purpose of `hide-preferences-window`

**Comment by mquevill** [comment] 2024-11-30 17:59
Seems like this is not fully fixed in v2.60.2, due to localization issues, so I am reopening the issue.

**Closed** 2024-12-01 19:14 UTC
Labels: bug

**Comment by mquevill** [comment] 2024-12-01 19:40
This issue should be fixed as of v2.60.3, across all locales. The `hide-preferences-window` class should be automatically removed now.

**Comment by Sp3EdeR** [comment] 2024-12-01 20:44
> This issue should be fixed as of [v2.60.3](https://github.com/sindresorhus/caprine/releases/tag/v2.60.3), across all locales. The `hide-preferences-window` class should be automatically removed now.

I can confirm, it's working correctly now, @mquevill! Well done and thanks! :)

**Comment by phirephoto** [comment] 2024-12-13 03:55
I just installed 2.60.3 on Linux Mint. Pressing the "Messages are missing <Restore Now>" link does nothing. Installed from AppImage.

**Comment by jcogilvie** [comment] 2024-12-21 22:21
2.60.3 on windows 11 installed via choco today.  The class isn't automatically removed for me.

**Comment by jimmypoulsen** [comment] 2025-02-01 12:30
`caprine_2.60.3_amd64.deb` installed on Ubuntu 24.04.1 today. The class is not automatically removed so I had to toggle the developer console and remove it.

**Comment by kongming819** [comment] 2025-02-02 03:52
Also not automatically removed for me, 2.60.3 on Windows 11. Had to do the workaround described above.

**Comment by tfoedy** [comment] 2025-02-15 13:12
Not fixed on version 2.60.3 with Polish language, installed through Flatpak on Fedora Linux.
I had to execute the following command:
`document.documentElement.classList.remove('hide-preferences-window')`
which made the window to input end-to-end encryption code appear and resolved the issue.

**Comment by PurpleHel** [comment] 2025-06-05 00:29
Kubuntu 25.04, installed caprine from flatpack at https://flathub.org/apps/com.sindresorhus.Caprine, also had to f12 and manually delete hideprefs. Is that flatpack page not the right place to download from?

**Comment by Bleksak** [comment] 2025-06-05 15:16
not removed in 2.60.3 on cachyos installed via AUR

**Comment by penzur** [comment] 2025-06-17 05:54
not removed in 2.60.3 on windows 11

**Comment by DanielHammerin** [comment] 2025-11-24 11:32
> This issue should be fixed as of [v2.60.3](https://github.com/sindresorhus/caprine/releases/tag/v2.60.3), across all locales. The `hide-preferences-window` class should be automatically removed now.

Still a problem on the appimage v2.60.3
Arch linux, KDE Plasma, Electron 29 bin.
