### ISSUE TITLE
Missing message icon does not disappear

### ISSUE THREAD

**Issue by Silver360** [sindresorhus/caprine#514] opened 2018-07-02 05:55 UTC
The red icon (missing message) Is still on task bar after reading. After reload app it disappears but app need to be reload which is annoying.

Windows 10

**Comment by rtpHarry** [comment] 2018-07-09 02:46
Yeah I get this a lot as well. It is minor but annoying.

Caprine 2.8.0
Electron 1.7.9
win32 x64 10.0.17134

**Comment by rtpHarry** [comment] 2018-07-09 02:49
Looks like this is a dupe of #499

**Comment by Borinius** [comment] 2018-08-10 14:59
I have the same issue aswell.

**Comment by rtpHarry** [comment] 2018-08-11 07:05
Looks like it might be fixed in an upcoming version? https://github.com/sindresorhus/caprine/pull/531

**Comment by dusansimic** [comment] 2021-08-17 21:30
Afaik, this work with no problems now and the issue seems stale. I'll close it now.

**Closed by dusansimic** 2021-08-17 21:30 UTC
