### ISSUE TITLE
Running snap package results in setuid_sandbox_host (SUID) error & core dump

### ISSUE THREAD

**Issue by PiotrDabrowskey** [sindresorhus/caprine#894] opened 2019-05-08 09:05 UTC
Snap version: `2.38.1`
```bash
piotr@dab:~$ snap --version
snap    2.38.1
snapd   2.38.1
series  16
ubuntu  18.04
kernel  4.18.0-18-generic
```

Caprine package version: `2.31.0`
```bash
piotr@dab:~$ sudo snap info caprine
name:      caprine
summary:   Caprine
publisher: Sindre Sorhus (sindresorhus)
license:   unset
description: |
  Caprine is an unofficial and privacy-focused Facebook Messenger app with many useful features.
commands:
  - caprine
snap-id:      UluDLd64Rry6IYTesGapYwu8sfuZmwbu
tracking:     stable
refresh-date: 12 days ago, at 08:32 CEST
channels:
  stable:    2.31.0 2019-04-26 (22) 133MB -
  candidate: ↑                            
  beta:      ↑                            
  edge:      ↑                            
installed:   2.31.0            (22) 133MB -
```

Output:
```bash
piotr@dab:~$ caprine
[31136:0508/110039.128720:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/caprine/22/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

Same happens on two different devices with the same OS. Reinstalling the app does not help. 

Error basically makes this app unusable - nothing is displayed as the app crashes immediately after lunch.

**Comment by SimonLegros** [comment] 2019-05-08 15:00
Same error here!

**Comment by SimonLegros** [comment] 2019-05-08 15:16
Duplicate of 876#
https://github.com/sindresorhus/caprine/issues/876#issuecomment-487304765

**Comment by CvX** [comment] 2019-06-30 15:25
#876 has been closed. Closing this one too. 🚀 (please let us know if the issue is still present in the latest version)

**Closed by CvX** 2019-06-30 15:25 UTC

**Comment by PiotrDabrowskey** [comment] 2019-07-02 14:54
I confirm the problem has been fixed for me. Thanks!
