### ISSUE TITLE
Show tray icon not work

### ISSUE THREAD

**Issue by dondolarson** [sindresorhus/caprine#1241] opened 2020-01-18 20:53 UTC
"Show tray icon" in settings doesn't work and haven't any impact after update to 2.42. Tray icon is always visible and can't be hidden as in 2.41

---

Caprine 2.42.0
Electron 7.1.9
win32 10.0.18363
Locale: sv

**Comment by sindresorhus** [comment] 2020-01-19 06:30
// @JBudny

**Comment by JBudny** [comment] 2020-01-30 00:05
> "Show tray icon" in settings doesn't work and haven't any impact after update to 2.42. The tray icon is always visible and can't be hidden as in 2.41
> 
> Caprine 2.42.0
> Electron 7.1.9
> win32 10.0.18363
> Locale: sv

Are you sure it was working on 2.41.0? Because I've picked this issue on 2.41.1 and back then for me it wasn't.  I believe I fixed this issue on #1215.

**Comment by dondolarson** [comment] 2020-01-30 10:22
Yes, I'm completely sure about it, 100%. I haven't had this icon in tray and always opened Caprine by pinned icon om my taskbar. Otherwise, I should notice it. It automatically appeared in tray with upgrading to 2.42 and no way to disable it since the option to show/hide doesn't work.

Maybe it has something to do with lack of notifications when received a message. I don't get any notification, hear only a "pling" and the icon changes it's colour from gray to blue. I was getting Action Center notifications/popups on 2.41 and no tray icon.

**Comment by JBudny** [comment] 2020-01-30 15:46
Thank you for detailed feedback, I think I get it right now. 
If I am right it's related to this issue #1217.

The tray icon wasn't showing when 'Show tray icon' and 'Quit on Window Close' was on.
In this case, the tray icon wasn't created after the application restart (but it should due to the 'Show tray icon' setting being on). The 'Show tray icon' toggle functionality, in contrast, wasn't warking yet. I fixed it on #1215 and it should work when my changes get accepted.

**Comment by dondolarson** [comment] 2020-01-31 11:00
'Quit on Window Close' as well as 'Show Tray Icon' are both set to off. Strange, I started to receive notifications about new messages near the date & time but they aren't visible in Action Center, (without Caprine update and changing any setting), though they're set to be visible in Action Center on my Windows 10 1909 updated machine.

**Comment by JBudny** [comment] 2020-02-03 12:15
I dug up a little into that issue and it looks like as I said before it's related to #1217, but I didn't describe it well enough when I was opening the issue. That fix not only applies when 'Show Tray Icon' and 'Quit on Window Close' are on but also when 'Launch Minimized' is on or app window is open as hidden. Do you use 'Launch Minimized' or any similar feature hiding the main app window? 
I guess the problem is that the caprine app doesn't have an option to launch it minimized into the taskbar icon and the pinned taskbar shortcut you were using was kind of workaround for it (without using the shortcut, the application was running in the background but not giving any default opportunity to maximize it). I solved that issue using a tray icon instead. 

On the other hand, I fixed tray icon toggle functionality on #1215 (not released yet), but I locked the possibility to hide tray icon along with 'launch minimized' setting on because I considered these settings mutually exclusive (hidden tray icon and launching minimized = no default way to maximize the window). Right now you can't use 'launch minimized' setting along with hidden tray icon, but if #1215 will get accepted and merged you'll be able to use tray icon instead.

Tell me please what do you think of that solution. If something isn't user-friendly in your opinion I'll try to fix it.

**Comment by dondolarson** [comment] 2020-02-04 00:34
See attached picture. These are my settings and always been since I've started to use this application back in September/October 2019. I pinned the Caprine icon just because I can open and use it by hitting it once, no matter if there wasn't any tray icon before or there's one, like now. I can't see an active window inside of the pinned icon but a tray icon instead when Caprine autostarts with the system. When hitting that tray icon/pinned icon, there's 4 active processes in task manager. When all 4 processes has been automatically started and then killed in task manager and application has been re-opened by hitting pinned icon or a start shortcut, then all four Caprine processes are back and a blank window is popping up and then closing by itself, but a tray icon stays. There's some delay when killed and re-opened. When application has been opened from tray or from a pinned icon after killing it and re-opening then a 5th process starts. It is how it works for me.
![Caprine](https://user-images.githubusercontent.com/49354563/73700353-a1407580-46e6-11ea-8f81-21e8f7f2620a.png)

**Comment by JBudny** [comment] 2020-02-04 15:00
I've managed to reproduce the 5th processes issue in the task manager.  It's probably because the pinned icon is a shortcut to run the application and instead maximizing it's opening the app again. I couldn't reproduce the issue for the tray icon.

**Comment by Kryszak** [comment] 2020-02-12 07:54
Tray icon is not present on Linux systems since version v2.44.
I tested it on Ubuntu 18.04 and Manjaro Linux.

**Comment by JBudny** [comment] 2020-02-13 02:32
It looks like it's related to the updated `electron `from `^7.1.10` to `^8.0.0`. At this point, I am not sure how we should fix that issue. More info [here](https://github.com/vladimiry/ElectronMail/issues/250#issuecomment-585385351)

**Comment by vladimiry** [comment] 2020-02-13 03:43
> At this point, I am not sure how we should fix that issue. More info here

See summary [here](https://github.com/electron/electron/issues/21445#issuecomment-565710027).

**Comment by sebastianpaweska** [comment] 2020-02-28 23:07
> KDE (Kubuntu): tray icon displayed out of the box, no tuning needed.
I can't agree with this point of the summary. Tray icon is missing as well (Manjaro 19.0.1, Plasma 5.17.5)

**Comment by yermulnik** [comment] 2020-03-04 14:05
Tray icon is missing for me on latest caprine 2.44.0-1790 but works on 2.43.0-1772

**Comment by vladimiry** [comment] 2020-03-04 14:39
> KDE (Kubuntu): tray icon displayed out of the box, no tuning needed.

@sebastianpaweska, I've authored above message. So according to the original message `KDE (Kubuntu)` it's not the Manjaro+KDE was tested but Kubuntu. See the system info the testing was happening on:

![tray](https://user-images.githubusercontent.com/1560781/75890035-d7d0f380-5e3e-11ea-917d-c73ad9c6ab73.png)

**Comment by JBudny** [comment] 2020-05-27 07:36
I've just found out that Electron is restoring an old implementation of tray icons that Chromium removed with Electron v8.

PR: [23674](https://github.com/electron/electron/pull/23674)

**Comment by yermulnik** [comment] 2020-06-03 08:42
https://github.com/electron/electron/pull/23674 has been merged

**Comment by HaroldBarrel** [comment] 2020-06-11 08:08
I'm using Manjaro XFCE and the tray icon is nowhere to be found as shown in the screenshot below. My Caprine version is 2.46.0-1.

![Screenshot_2020-06-11_10-05-17](https://user-images.githubusercontent.com/38738346/84360961-3b4f8780-abcb-11ea-9371-087a5342fadc.png)

**Comment by GiORdANio** [comment] 2020-06-11 12:50
> I'm using Manjaro XFCE and the tray icon is nowhere to be found as shown in the screenshot below. My Caprine version is 2.46.0-1.
> 
> ![Screenshot_2020-06-11_10-05-17](https://user-images.githubusercontent.com/38738346/84360961-3b4f8780-abcb-11ea-9371-087a5342fadc.png)

Same here.

**Comment by dusansimic** [comment] 2020-10-30 00:14
This is related to the missing icon due to Chromium but and as that is fixed and icon is present again I will close this issue.

**Closed by dusansimic** 2020-10-30 00:14 UTC
