### ISSUE TITLE
Caprine is "stealing" clipboard (copy/paste) content from shortcut on MacOS

### ISSUE THREAD

**Issue by vitalykorolev** [sindresorhus/caprine#261] opened 2017-07-25 05:48 UTC
Open Google Chrome.
Copy and paste text in one of the tabs. (with ⌘+C  ⌘+V) --> works fine.
Open Caprine.
Copy something in Chrome and attempt to paste.
Nothing gets pasted in Chrome, but if you switch to Caprine, you'll see that text got pasted there in the background.

-

Caprine 2.5.0
Electron 1.6.7
darwin x64 16.7.0

**Comment by kevva** [comment] 2017-07-25 06:53
Duplicate of https://github.com/sindresorhus/caprine/issues/258.

**Closed by kevva** 2017-07-25 06:53 UTC

**Comment by sindresorhus** [comment] 2017-07-27 01:05
New release is out that disables the problematic code: https://github.com/sindresorhus/caprine/releases/tag/v2.6.0
