### ISSUE TITLE
Dark Mode is not working properly

### ISSUE THREAD

**Issue by stonevil** [sindresorhus/caprine#1460] opened 2020-12-08 18:25 UTC
macOS 11.0.1 (20B29)

Follow System Appearance enabled.
Dark Mode is enabled automatically and grayed.

Caprine shows in Light Mode.

![1](https://user-images.githubusercontent.com/129196/101525068-a3dfad00-393f-11eb-9832-8c6fab38ac33.png)

---

Caprine 2.51.2
Electron 10.1.5
darwin 20.1.0
Locale: en-GB

**Comment by igniushka** [comment] 2020-12-08 18:35
Doesn't work on Manjaro either.

**Comment by dusansimic** [comment] 2020-12-08 20:01
Duplicate of #1439

**Closed by dusansimic** 2020-12-08 20:01 UTC
