### ISSUE TITLE
Dark mode no longer works

### ISSUE THREAD

**Issue by baq-86** [sindresorhus/caprine#1447] opened 2020-11-18 10:40 UTC
Something changed on messenger.com code and Caprine's dark mode no longer works :( 

---

Caprine 2.51.1
Electron 10.1.5
linux 4.15.0-123-generic
Locale: pl

**Comment by baq-86** [comment] 2020-11-18 21:53
Actually, most of (or all) functionalities added by Caprine to messenger.com service no longer works...

**Comment by dusansimic** [comment] 2020-11-19 00:34
Hi! Is there some error message displayed? Are you using custom styles? Is there a specific way that I can reproduce this since I'm running latest version of Caprine and I have no problems whatsoever. Also, how did you install Caprine?

**Comment by dusansimic** [comment] 2020-11-19 12:06
Duplicate of #1439

**Closed by dusansimic** 2020-11-19 12:06 UTC
