### ISSUE TITLE
New messenger.com update

### ISSUE THREAD

**Issue by kqrmo** [sindresorhus/caprine#1464] opened 2020-12-10 08:27 UTC
After the last messenger.com update, most of the features aren't working.. Ex. Dark theme, compact mode (because of the new sidebar update, idk) and probably any more. I've seen only dark mode & compact mode not working and those are most needed, I assume. :D

**Comment by rivenirvana** [comment] 2020-12-10 08:29
Referring this to #1439

**Comment by dusansimic** [comment] 2020-12-10 08:50
Duplicate of #1439

**Closed by dusansimic** 2020-12-10 08:50 UTC
