### ISSUE TITLE
Adjusting size of font doesn't work

### ISSUE THREAD

**Issue by Kryszak** [sindresorhus/caprine#1467] opened 2020-12-10 19:28 UTC
Increasing/decresing font size doesn't work anymore on Linux - it seems like something on Messenger itself was changed

**Comment by Simao-Santos** [comment] 2020-12-14 04:41
The same happens to me.
Also can't change to dark mode.

**Comment by dusansimic** [comment] 2020-12-14 11:40
Duplicate of #1439

**Closed by dusansimic** 2020-12-14 11:40 UTC
