### ISSUE TITLE
Doesn't send notification.

### ISSUE THREAD

**Issue by rjlad** [sindresorhus/caprine#1656] opened 2021-06-13 06:29 UTC
I am on ubuntu 20.04 LTS. Caprine doesn't show any notification when I receive a message. Tried reinstalling as well but didn't fix the issue.

**Comment by rjlad** [comment] 2021-06-13 06:30
Notification Issue on Ubuntu 20.04 LTS

**Comment by dusansimic** [comment] 2021-06-16 20:06
Duplicate of #1562

**Closed by dusansimic** 2021-06-16 20:06 UTC
