### ISSUE TITLE
No Push notification from Caprine on Windows 10 21H2

### ISSUE THREAD

**Issue by pftmclub** [sindresorhus/caprine#1783] opened 2022-01-30 06:41 UTC
I tried everything and it's just won't work. Anyway to fix that?
![image](https://user-images.githubusercontent.com/19551146/151689583-3f524cdf-a126-45e7-b172-11bf6a9cb9cd.png)
![image](https://user-images.githubusercontent.com/19551146/151689591-dfd9aa4f-9c01-476e-bc61-8f39af1fbd1b.png)

**Comment by dusansimic** [comment] 2022-01-30 09:00
Duplicate of #1562

**Closed by dusansimic** 2022-01-30 09:00 UTC
