### ISSUE TITLE
darkmode not appear correctly

### ISSUE THREAD

**Issue by nqa112** [sindresorhus/caprine#1527] opened 2021-01-15 06:55 UTC
---
![image](https://user-images.githubusercontent.com/75834609/104691647-2d517e80-5739-11eb-97d0-c4514ffcba5b.png)

Caprine 2.51.2
Electron 10.1.5
win32 10.0.18363
Locale: en-US

**Comment by dusansimic** [comment] 2021-01-15 07:55
Duplicate of #1526

**Closed by dusansimic** 2021-01-15 07:55 UTC
