### ISSUE TITLE
Icons missing after lock screen

### ISSUE THREAD

**Issue by kerozoli** [sindresorhus/caprine#1358] opened 2020-05-14 10:20 UTC
Hi Caprine also affected by this electron/chromium issue :
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/228
https://github.com/electron/electron/issues/22443

There's maybe a workaround for this issue described here:
https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150

**Comment by dusansimic** [comment] 2020-10-30 21:35
Duplicate of #1331

**Closed by dusansimic** 2020-10-30 21:35 UTC
