### ISSUE TITLE
Not getting notified after latest update

### ISSUE THREAD

**Issue by LogX7** [sindresorhus/caprine#905] opened 2019-05-24 03:30 UTC
Hello, i updated caprine to the latest version (2.31.0)

and now i don't get notified when i receive a new message, i'm on linux mint 19.1

**Comment by tamassengel** [comment] 2019-05-24 08:57
Same on macOS 10.14.5. Also, the whole Messenger UI is changed and the layout is now somewhat broken.

**Comment by pkuczynski** [comment] 2019-05-25 18:08
Duplicate of #893?

**Comment by sindresorhus** [comment] 2019-05-28 15:07
Duplicate of #893

**Closed by sindresorhus** 2019-05-28 15:07 UTC
