### ISSUE TITLE
Blank when image clicked

### ISSUE THREAD

**Issue by Lanthanariel** [sindresorhus/caprine#1751] opened 2021-12-04 09:02 UTC
Clicking on an image displays a blank screen instead of the image itself, so for now I just copy the image link and open it on a browser. Videos are fine, for the most part. :/
---

Caprine 2.55.1
![blank](https://user-images.githubusercontent.com/53405083/144703851-fb2f88ea-3744-4eb2-aa4f-d67d77d8d77e.png)

Electron 10.4.7
linux 5.15.5-76051505-generic
Locale: en-US

**Comment by FunkyJustin** [comment] 2021-12-04 20:33
I'm having the same problem as well, hopefully it gets fixed soon

**Comment by Rykee** [comment] 2021-12-05 20:32
Same issue on Windows, with both 2.55.0 and 2.55.1

**Comment by leventelist** [comment] 2021-12-05 22:14
Same issue on Debian stable. v2.55.1

**Comment by kacnje** [comment] 2021-12-06 04:41
Same issue on Windows and Linux Mint.

**Comment by mirenradia** [comment] 2021-12-06 16:33
I am also having this problem on Ubuntu 20.04 (so deb version) with v2.55.1.

> I have the same issue. For now, my workaround has been opening Developer tools (Command + Option + I on mac, probably Control+Alt+I for windows) and removing the `hide-preferences-window` class from the `<html>` tag.
> 
> Works until you close Caprine and open it again.
> 
> ![ScreenShot 2021-12-06 at 11 01 45@2x](https://user-images.githubusercontent.com/15897093/144879634-be4eee24-3d76-40c4-80b0-2951b1bb6c93.png)

Thanks for the workaround. This fixed it for me too.

**Comment by spyd3r-b0y** [comment] 2021-12-06 18:10
facing same problem v 2.55.1 on ubuntu.

**Comment by dusatvoj** [comment] 2021-12-07 11:42
Problem even with "file  -> messenger settings" window

**Comment by maxoku** [comment] 2021-12-08 09:52
That workaround actually work. What that class is doing there in the first place? It affects a lot of things besides media, but they are just don't appear. Are there styles that affect this class? If so then maybe workaround could be with css and then more persistent?

**Comment by dusansimic** [comment] 2021-12-08 09:59
@maxoku the class is used to hide preferences modal, but the side effect is that it hides all modals (remove chat, archive chat) and also the image and video viewer. The class is added if there is no need to display the preferences modal (e.g. on app startup when the user configured settings are applied) and after that operation is done it's removed. The problem is that some classes in the messenger ui have changed (it happens from time to time) and that breaks queries that are looking for some elements which results in the `hide-preferences-windows` class not being removed. It's fixed now with the pr I've sent out, it just needs to be merged.

Once I find some free time, I'll look into improving the default settings code to errors are handled more gracefully and class is removed event if something changes in the ui.

**Comment by profucius** [comment] 2021-12-08 14:03
> my workaround has been opening Developer tools probably Control+Alt+I for windows

For me, it was Ctrl + Shift + i

**Comment by SkrowRepap** [comment] 2021-12-09 04:40
> > my workaround has been opening Developer tools probably Control+Alt+I for windows
> 
> For me, it was Ctrl + Shift + i

thanks

**Closed** 2021-12-09 18:18 UTC

**Comment by orucky** [comment] 2022-04-12 17:07
This regresses repeatedly, what about https://github.com/sindresorhus/caprine/issues/1811#issuecomment-1096977599?
