### ISSUE TITLE
No icon in Ubuntu 18.04

### ISSUE THREAD

**Issue by vanushwashere** [sindresorhus/caprine#462] opened 2018-05-18 20:32 UTC
System: Ubuntu 18.04 x64
There is no icon in GNOME
![image](https://user-images.githubusercontent.com/24995381/40256618-1b740c5a-5afc-11e8-8bc6-a7035c54aef2.png)

**Comment by vanushwashere** [comment] 2018-05-18 20:35
As a workaround I suggest to manuly download svg icon to `/opt/Caprine/` folder, edit `/usr/share/applicaitons/caprine.desktop/` file and provide full path to svg icon in Icon= field

**Comment by sindresorhus** [comment] 2018-05-19 06:58
Duplicate of #416

**Closed by sindresorhus** 2018-05-19 06:58 UTC
