### ISSUE TITLE
Dark mode messages are white on white, therefore invisible

### ISSUE THREAD

**Issue by colmoni** [sindresorhus/caprine#2152] opened 2024-03-20 17:52 UTC
In Dark mode, messages from other person are white text on a white background, therefore unreadable. This forces use of light background, with an uncomfortable white app background.

---

Caprine 2.59.3
Electron 25.9.8
linux 6.5.0-26-lowlatency
Locale: en-GB

**Comment by mquevill** [comment] 2024-03-20 17:56
Duplicate of #2148.

**Closed** 2024-03-20 17:56 UTC
