### ISSUE TITLE
Taskbar badge not always updated

### ISSUE THREAD

**Issue by petko** [sindresorhus/caprine#499] opened 2018-06-19 21:04 UTC
The badge showing the unread messages in the taskbar icon of Caprine on Windows is not always correct. Sometimes it will show 1 unread message, although there are none. 

The icon in the traybar though always shows the proper status (red dot showing when there are any unread messages).

**Comment by Silver360** [comment] 2018-07-02 10:40
Oh I have the same this is really annoying

**Comment by dusansimic** [comment] 2021-08-17 21:31
Duplicate of #514

**Closed by dusansimic** 2021-08-17 21:31 UTC
