### ISSUE TITLE
Please align application window borders with Dark Modes (for Windows)

### ISSUE THREAD

**Issue by a-dzik** [sindresorhus/caprine#987] opened 2019-07-04 19:08 UTC
Steps to reproduce:
1. Swtich Caprine to Dark Mode.
2. The Top navigation bars remain white (light) 

![Screenshot_1](https://user-images.githubusercontent.com/5823038/60684627-276db280-9e9f-11e9-9577-d4792e3b3465.png)

Please also note that this bar also does not align with Windows themes. For inspiration how to style this view, please see Windows settings window or Chrome:
![Screenshot_2](https://user-images.githubusercontent.com/5823038/60684712-a4009100-9e9f-11e9-8eab-715afad4fc0c.png)
![Screenshot_3](https://user-images.githubusercontent.com/5823038/60684713-a4009100-9e9f-11e9-8ae5-1278605fe020.png)

---

Caprine 2.32.1
Electron 5.0.4
win32 10.0.17134
Locale: pl

**Comment by CvX** [comment] 2019-07-04 21:51
Duplicate of #652 🙂

**Closed by CvX** 2019-07-04 21:51 UTC
