### ISSUE TITLE
Bottom text field gets replaced with "Could not display composer." if its input is not active

### ISSUE THREAD

**Issue by the4kman** [sindresorhus/caprine#316] opened 2017-11-02 15:04 UTC
I am using Caprine 2.7.1 on Mac. If the text input on the bottom is not in focus and I press an alphanumeric key on my keyboard, the input gets replaced with an area that says "Could not display composer." and it does not recover from that state until I refresh Caprine (Cmd+R). It does not disappear either when I switch between conversations.

<img width="507" alt="screen shot 2017-11-02 at 16 00 25" src="https://user-images.githubusercontent.com/6132647/32333149-6ce02bec-bfe7-11e7-8bd4-a2b60eed18eb.png">

BTW, you can blur the text input by opening an image in a conversation and dismissing it by clicking on the area where the right sidebar is behind the black overlay.

**Comment by hckuo** [comment] 2017-11-07 20:26
+1

**Comment by massayoshi** [comment] 2017-11-07 21:37
Here usually happens when I press CMD

**Comment by happyearmuffs** [comment] 2017-11-13 19:47
I've been able to reproduce by follow these steps:
- Click a link in a thread, focus is drawn to browser
- click back into thread body
- press any key

**Comment by emileber** [comment] 2017-11-13 19:49
I confirm that with these steps, I got the problem on my end as well.

**Comment by effektsvk** [comment] 2017-11-13 20:55
I can confirm as well but with a little note. You have to click back into thread body when Caprine window is not in focus (don't CMD-Tab back into it). That click into thread body will activate focus on the window.

**Comment by emileber** [comment] 2017-11-13 21:01
- Opening an image, 
- closing it 
- and typing 

will also cause the problem.

**Comment by emileber** [comment] 2017-11-13 21:06
It looks like the focus is always in the _composer_ box by default, and when the focus isn't on a valid element (search box, composer box, etc.), like when you open a link or an image and get back, it fails.

**Comment by Vilscon** [comment] 2017-11-16 09:24
Yet.. there isn't a solution for this? :s

**Comment by effektsvk** [comment] 2017-11-16 09:25
Except refreshing Caprine when it happens, no. :(

**Comment by Vilscon** [comment] 2017-11-16 09:26
Hm, I can live with that. Normally I force-quit the app and restart it. Apparently CMD+shift+R works as well.

**Comment by effektsvk** [comment] 2017-11-16 09:27
Just CMD + R should work ;)

**Comment by veniversum** [comment] 2017-11-18 03:41
This seems to have been fixed on FB's end -- is it still reproducible?

**Comment by hron84** [comment] 2017-12-05 14:36
Not with Caprine, but with MessengerForDesktop, but sometimes this still happens. I guess this is something that Facebook should improve.

**Closed** 2018-02-01 06:40 UTC
Labels: bug, help wanted

**Comment by notflip** [comment] 2018-05-30 03:03
Has anyone been able to reproduce this?
