### ISSUE TITLE
Vibrancy not working on Caprine Version 2.52.0 (MacOS Big Sur 11.1)

### ISSUE THREAD

**Issue by nguyenngocduy20** [sindresorhus/caprine#1534] opened 2021-01-26 03:26 UTC
Vibrancy feature is not working on Caprine Version 2.52.0 (MacOS Big Sur 11.1)

**Comment by dusansimic** [comment] 2021-01-26 08:22
Please try adding [this](https://github.com/sindresorhus/caprine/issues/1488#issuecomment-752692595) into the custom css file (File > Caprine Settings > Advanced > Custom Styles). Let me know about the results.

**Comment by nguyenngocduy20** [comment] 2021-01-26 08:59
It seem to work, but not much like vibancy effect in previous Messenger UI.
![image](https://user-images.githubusercontent.com/18401853/105822283-7da8c600-5fee-11eb-9418-35f7ff56a858.png)

**Comment by dusansimic** [comment] 2021-01-28 14:20
This issue is a duplicate of #1504 since the bug was not fixed in new release in the first place. We will track the issue there. Thanks for the report!

**Closed by dusansimic** 2021-01-28 14:20 UTC
