### ISSUE TITLE
No notifications in Action Center, nor pop-up, just pling sound

### ISSUE THREAD

**Issue by dondolarson** [sindresorhus/caprine#1275] opened 2020-02-13 13:49 UTC
I'm not getting any visual information about new incoming messages in Action Center if they're income and not read, nor pop-ups when they just arrive, just a standard Messenger "pling" sound and the status of tray icon changes from gray to blue. Is it only me having this issue? Some setting? It looks to be properly set in Windows 10 settings - everything is activated, except the "hide content when screen is locked" setting. Running latest Windows 10 1909.

**Comment by dondolarson** [comment] 2020-02-26 23:13
I'm along about this?

**Comment by gpeter12** [comment] 2021-01-03 19:31
@dondolarson no you are not, I have almost the same issue on Ubuntu 20.04.1 LTS
I also have only just "pling sound" but the status tray icon doesn't change and I'm not getting any system notification from Caprine through GNOME.

**Comment by dusansimic** [comment] 2021-01-04 11:56
Duplicate of #1439

**Closed by dusansimic** 2021-01-04 11:56 UTC
