### ISSUE TITLE
No notification on Windows

### ISSUE THREAD

**Issue by gehdfkhj** [sindresorhus/caprine#915] opened 2019-05-29 14:43 UTC
- With this update (2.31.1) there isn't any notifications anymore on the taskbar icon.
- There isn't any notifications on the little icon in the notification area too. This is a problem since around Electron v2 for me. It is just a grey icon.
- It would be great to have an auto update OFF option, so that I can stay on 2.31.0.

Sindre and all contributors, THANK YOU for the amazing work on this program!
---
Caprine 2.31.1
Electron 5.0.2
win32 10.0.17134
Locale: en-US

**Comment by pkuczynski** [comment] 2019-05-29 16:15
Is this a duplicate of #893?

**Comment by gehdfkhj** [comment] 2019-05-29 17:42
Could be, but my issues started at different times.

**Comment by pkuczynski** [comment] 2019-05-29 17:46
Your issues are most likely caused by a new version of Messenger rollout. It was initially rolled out to some users and recently to either more or all. My friend started to have this issue yesterday for example, while I was affected for around 2 weeks.

There is a PR #908 waiting for approval, so you might want to vote/comment it and observe the status.

You can also top up the issue hunt https://issuehunt.io/r/sindresorhus/caprine/issues/893 to get it maybe resolved faster...

**Comment by sindresorhus** [comment] 2019-05-30 05:31
Duplicate of #893

**Closed by sindresorhus** 2019-05-30 05:31 UTC
