### ISSUE TITLE
Downloading files doesn't work

### ISSUE THREAD

**Issue by babaliaris** [sindresorhus/caprine#1976] opened 2023-01-04 09:29 UTC
Hello.

I'm not sure if it's implemented or not, but downloading files doesn't seem to work. 
Any suggestions on how to provide more feedback?

All I see now is that, when I click on a **.pdf**  for example, nothing happens.
Also the option `file->messenger settings` does not do anything either.

I'm not getting any errors on `journalctl -p 3 -b`

Thank you for your time.

---

Caprine 2.57.0
Electron 20.3.8
linux 6.1.2-arch1-1
Locale: en-US

**Comment by dusansimic** [comment] 2023-04-16 17:13
Since this is a wrapper around messenger.com website, it is implemented but probably a bug of some sort is preventing it from happening. I'll mark it as a bug for now and when able look into the cause of the issue. Help is welcome!

**Comment by grzegorj8** [comment] 2023-04-30 11:50
Caprine is recommended as a better alternative for the genuine Messenger and this would be an excellent idea. Unfortunately, Caprine does not seem to be able to download anything. The only option that it offers is to open a browser and to download with the help of it.

It is not what a user expects. The program should save files directly, without the help of anything, exactly as Messenger does. As long as it cannot do it, you should not term it a replacement of the genuine Messenger.

So, please do something with it...

**Comment by dusansimic** [comment] 2023-04-30 12:16
Caprine _is_ able to download files, as you've said, via browser. All files on messenger website are actually links and the default behavior of Caprine is to open links in a browser.

Please open a new issue describing the behavior you've explained here so we can start a discussion about a solution 😁. Reason for that is simple, this bug report is about files not downloading, not files being downloaded through a browser.

I'll close this issue because the original author is unresponsive.

**Closed by dusansimic** 2023-04-30 12:16 UTC
Labels: bug, help wanted
