### ISSUE TITLE
No longer automatically logs in

### ISSUE THREAD

**Issue by kingmustard** [sindresorhus/caprine#1061] opened 2019-08-21 16:14 UTC
Since updating from v2.35 to v2.36 (Windows), when the program auto-runs after an OS restart, I am presented with the sign in screen.

![eb_236signin-1](https://user-images.githubusercontent.com/1947304/63449029-208f0500-c437-11e9-9290-0aceddc03188.png)

**Comment by zdenekvecera** [comment] 2019-08-21 19:12
I confirm the same problem.

**Comment by af4ro** [comment] 2019-08-21 23:24
I confirm the same on MacOS (v10.14.6)

**Comment by af4ro** [comment] 2019-08-21 23:33
Refer to the solution on #1044

**Comment by Mattrak** [comment] 2019-08-26 01:18
Which is :
https://github.com/sindresorhus/caprine/issues/1044#issuecomment-524573614

**Comment by Mattrak** [comment] 2019-08-26 01:19
"I think uninstalling Caprine was an unnecessary step. Just removing the directory with the app closed should be effective as well.

If you want to try the same, the directory I mentioned is:

%APPDATA% on Windows
$XDG_CONFIG_HOME or ~/.config on Linux
~/Library/Application\ Support on macOS"

**Comment by dusansimic** [comment] 2020-11-01 10:00
I'll close this issue since it's a duplicate of #1044 and you can use [this](https://github.com/sindresorhus/caprine/issues/1044#issuecomment-521925982) solution to fix the issue.

**Closed by dusansimic** 2020-11-01 10:00 UTC
