### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by mikigal** [sindresorhus/caprine#653] opened 2018-11-13 01:12 UTC
An error occurs sometimes while opening app.
Problem exists on macOS Mojave (10.14) and macOS High Sierra (10.13.3).
After reopen Caprine everything is fine and app start normally. 

<img width="520" alt="mb0zpwmlnv" src="https://user-images.githubusercontent.com/10632503/48384191-79cc4a00-e6e9-11e8-84ae-747592f9e479.png">

**Comment by titaniumbones** [comment] 2018-11-13 16:43
I think this is a dupe of #609  and #573. I see the same thing on Gnome. Looks like it's appearing on several platforms?

**Closed** 2022-08-05 17:24 UTC
