### ISSUE TITLE
Caprine prevents default autocomplete 

### ISSUE THREAD

**Issue by nchanged** [sindresorhus/caprine#818] opened 2019-03-15 08:13 UTC
Hi, it's an amazing app! it looks great! I love the dark mode. But one thing that puts me off is that the autocomplete is off. I have a great amount of keyboard settings, like emoji and stuff, but it's all prevented. Is it possible to optionally enable a default OS behaviour? I am running it on MacOSX `10.14.2`

**Comment by sindresorhus** [comment] 2019-03-15 10:10
Duplicate of #14

**Comment by sindresorhus** [comment] 2019-03-15 10:10
Caprine is not preventing. It's just not implemented.

**Closed by sindresorhus** 2019-03-15 10:10 UTC
