### ISSUE TITLE
Caprine loses connection after windows sleep

### ISSUE THREAD

**Issue by eris-price** [sindresorhus/caprine#1039] opened 2019-08-12 00:03 UTC
When i let my PC go idle and enter sleep mode, and then wake it up, caprine will lose connection to FB messenger. I'm still able to send new messages, but messages received won't appear in caprine. I have to either close and reopen caprine, or press F5 to refresh. It's not the end of the world, but it can be frustrating when i don't realize caprine isn't updating and i have messages waiting for me that i don't know about.

---

Caprine 2.35.0
Electron 6.0.1
win32 10.0.18362
Locale: en-US

**Comment by sindresorhus** [comment] 2019-08-12 00:04
Duplicate of #103

**Closed by sindresorhus** 2019-08-12 00:04 UTC
