### ISSUE TITLE
Javascript error on exit

### ISSUE THREAD

**Issue by Jebiel** [sindresorhus/caprine#856] opened 2019-04-13 14:17 UTC
Hi folks 👋

I'm on the ver. 2.30.2, and keeps getting an error message when quitting the application.
Have been searching in the issues already open, and some looks a bit similar, but not with the same stacktrace, as far as I can see.

![javascript_error](https://user-images.githubusercontent.com/22646197/56080924-714a7d80-5e07-11e9-9e65-5c66f3463a56.png)

I'm not sure if this is already covered. Just thought to post in case it wasen't.

- Best regards Jebiel

**Comment by sindresorhus** [comment] 2019-04-17 06:46
Duplicate of #809

**Closed by sindresorhus** 2019-04-17 06:46 UTC
