### ISSUE TITLE
Tray icon, functionality

### ISSUE THREAD

**Issue by aleksandarcajic** [sindresorhus/caprine#610] opened 2018-10-11 09:11 UTC
Hi!
Issue which I've found while I'm using this app is that tray icon is not acting fine.
1. Caprine app is up and running
2. Caprine window is closed, by clicking Close button.
3. New message arrived, by clicking tray icon (which is blue at that moment) Caprine window is not shown (toggled). Instead, context menu is shown and user needs to choose Toggle menu option to get Caprine window at the top of other windows. Beside this issue, in some cases Caprine window is not shown or brought at the top of other windows.

Best regards!
Alex

---

Caprine 2.19.0
Electron 3.0.2
linux x64 4.15.0-36-generic

**Comment by dusansimic** [comment] 2018-10-28 16:44
What You described is absolutely normal. I suspect You're running Gnome as Your desktop manager. That is the behavior of the Gnome DM. When you click on tray icon, app doesn't pop up but the context menu with options for that app. This cannot be changed since it's built into the system. Concerning the second issue that Caprine window is not brought up on toggle click, make sure that Caprine isn't already open since if it is toggle option actually closes the window.
Hope this helps 😁.

**Comment by dotpointer** [comment] 2018-11-26 16:47
I have a similar problem on Debian 9.6 with MATE Desktop 1.16.2 and Caprine 2.22.1.

I cannot left click nor  double-left-click on the icon in the tray anymore to open the main window. Both left and right mouse buttons now act as if I right-click - I get a the context menu with Toggle and Quit.

This is a regression after upgrading Caprine. It worked to click or double click on the icon to show the main window in the previous version of Caprine I had installed.

**Comment by dusansimic** [comment] 2018-11-26 18:03
Duplicate of https://github.com/sindresorhus/caprine/issues/468

**Closed** 2020-11-01 10:28 UTC
