### ISSUE TITLE
Some buttons doesn't do anything

### ISSUE THREAD

**Issue by G6jviYg1LwtP4sD** [sindresorhus/caprine#1914] opened 2022-09-15 08:16 UTC
OS: Windows 10 Pro
Caprine 2.56.1

Buttons that doesn't do anything or malfunctions:
- Messenger Settings button
- All buttons (except "Change photo" and "Search in Conversation")  in Customize Chat Dropdown from any group chat with group admin access
- Messenger Preferences Button

Steps:
A. Messenger Settings Button
1. Launch Caprine 2.56.1
2. Login
3. Click File > Messenger Settings (Ctrl + Comma)

B. Customize Chat Dropdown Buttons
1. Launch Caprine 2.56.1
2. Login
3. Join a Group Chat with Admin Access
4. Click 3 dot icon on top right
5. Click Customize Chat
6. Click all dropdown buttons

C. Messenger Preferences Button
1. Launch Caprine 2.56.1
2. Login
3. Click your profile photo on below left
4. Click Preferences

**Comment by dusansimic** [comment] 2022-09-15 09:43
This is caused by #1906 (it will be fixed once #1910 is merged). The search in conversation issue is probably another thing but it's tracked in #1913. Thanks for reporting tho.

**Closed by dusansimic** 2022-09-15 09:43 UTC
