### ISSUE TITLE
Window Vibrancy Options in Dark Mode

### ISSUE THREAD

**Issue by Curbsidecollection** [sindresorhus/caprine#541] opened 2018-07-23 03:46 UTC
This is not really an 'issue' in the usual sense. Just a query.

I remember when I first downloaded this application, when in dark mode, there was a 'Vibrancy' toggle in the View menu, and one of the options was a semi-transparent window with no color value. I liked this aesthetic a lot and would always toggle to it, despite it reverting on every launch. The current Dark Mode is good, but I am wondering if there was anything to say about this other option? 

Is it potentially coming back and why was it removed?

Thank you for the magnificent application.

**Comment by sindresorhus** [comment] 2018-07-23 05:47
There are bugs with the framework we use, Electron, that makes it impossible to use vibrancy at the moment. It will be brought back when it's fixed here.

**Comment by sindresorhus** [comment] 2018-07-23 05:47
Duplicate of #463

**Closed by sindresorhus** 2018-07-23 05:47 UTC
