### ISSUE TITLE
Dark Mode works when toggled but does not persist when relaunched

### ISSUE THREAD

**Issue by avidianity** [sindresorhus/caprine#1574] opened 2021-03-05 11:12 UTC
I installed caprine from the snap store, when I turn on dark mode it works but it goes back to light mode if I relaunch it.

---

Caprine 2.52.0
Electron 10.1.5
Ubuntu 20.04

**Comment by dusansimic** [comment] 2021-03-05 11:15
Duplicate of #1525

**Closed by dusansimic** 2021-03-05 11:15 UTC
