### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by rosoau** [sindresorhus/caprine#782] opened 2019-02-13 20:26 UTC
The application icon shows a blank icon.
The icon was installed into a very "unusual" location: /usr/share/icons/hicolor/0x0/apps/
I had never seen an icon folder called "0x0" before! Please keep to the established conventions!
the icon-cache updater somehow does not work on that location
putting a copy of the icon into the root icon folder: /usr/share/icons/
makes it show up in the menu without using the cache updater

**Comment by CvX** [comment] 2019-02-13 20:31
Caprine doesn’t do anything out of ordinary with its app icon. The issue you’re seeing could be a bug in electron-build.

**Comment by rosoau** [comment] 2019-02-14 23:15
Ok, thanks. I resized the icon into various sizes: 16x16 24x24 32x32 48x48 64x64 128x128 256x256 and 512x512
With their proper destinations inside the "data" folder that can then be merged with the Debian
[data.tar.gz](https://github.com/sindresorhus/caprine/files/2867137/data.tar.gz)
 build

**Comment by rosoau** [comment] 2019-02-19 21:28
Linux 4.15.0-45 Caprine 2.29.0
Electron stuffed up again on the Debian version
Icons are again in folder 0x0 which mathematically speaking is: Nothing times Nothing
It should have created icons in following sizes:
16x16 24x24 32x32 48x48 64x64 96x96 128x128 256x256 and 512x512
We need to keep an eye on Electron and act accordingly (correct mistakes)
Also the icon on your webpage and on caprine startup page have 
not been modifed to your new design which is more roundish

**Comment by dusansimic** [comment] 2019-02-19 22:14
This also happened on Ubuntu 18.10 Gnome 3.30.2. I use AppImage and icon doesn't show, just a default app icon.

**Comment by rosoau** [comment] 2019-02-20 01:38
dusansimic you can download the icons from here: caprine-icons.zip
[caprine-icons.zip](https://github.com/sindresorhus/caprine/files/2882616/caprine-icons.zip)
then copy the icon folders to their destinations
then do an icon update: **sudo gtk-update-icon-cache /usr/share/icons/hicolor**
and also: **sudo update-icon-caches /usr/share/icons/hicolor**
see if that works. I use the .deb file on Ubuntu 16.04

**Comment by elcanux** [comment] 2019-02-21 07:25
I have also this bug on ubuntu 16.04 LTS with lastest version deb.
I have extract icons and that's works now, thanks

**Comment by dusansimic** [comment] 2019-02-21 09:41
This method doesn't seem to work with AppImage.

**Comment by rosoau** [comment] 2019-02-21 20:33
Sorry dusansimic; I was afraid that it may not work with the appimage. If you allowed it to create a desktopfile then that file could be modified. It resides most likely in ~/.local/share/applications as: caprine.desktop. You can use one of the resized icons and point towards it on the line: Icon=
Like: Icon=/usr/share/icons/hicolor/32x32/apps/caprine.png
It is best to open the desktop file in the terminal: gedit ~/.local/share/applications/caprine.desktop
Instead of gedit use the name of your text-editor

**Comment by pols12** [comment] 2019-02-23 23:09
Seems to be electron-userland/electron-builder#2577 or electron-userland/electron-builder#3609 (see these issues to see workarounds). However the second one is older than Caprine v2.0.19 which worked properly for me.

**Comment by mquevill** [comment] 2019-07-02 19:39
Issue still exists with the 2.33.1 `.deb` installed onto Linux Mint 19.1 with Cinnamon 4.0.10.

The only icon is located at `/usr/share/icons/hicolor/0x0/apps/caprine.png`. In fact, it's the only entry in the `0x0/` directory, which makes me think that something is going wrong with the `.deb.` packaging.

**Comment by dusansimic** [comment] 2019-08-15 14:52
I found a solution that works on latest Caprine (2.36) for AppImage. The problem is that when desktop file is generated automatically it sets icon to be `appimagekit-caprine`. Just change the icon variable to be `caprine`.

Usually the desktop file is located in `.local/share/applications`. For AppImage it'll be named `appimagekit-caprine.desktop`.

**Comment by keelnar** [comment] 2020-03-29 20:56
Running into this issue with the 2.44.0 `.deb`. on Ubuntu 18.04.4. It seems some folks have a workaround for this, but I'm unclear from this thread what the workaround is. Can anyone clarify?

**Comment by pols12** [comment] 2020-03-29 21:20
> Running into this issue with the 2.44.0 `.deb` on Ubuntu 18.04.4. It seems some folks have a workaround for this, but I'm unclear from this thread what the workaround is. Can anyone clarify?

You can download [rosoau’s icon file](#issuecomment-466155656).
Then, extract it in your file system following archive-included hierarchy. (you have to consider the `usr` directory in the .zip matches with `/usr`).
Then execute both following command in a terminal as root (sudo them):
```sh
gtk-update-icon-cache /usr/share/icons/hicolor
update-icon-caches /usr/share/icons/hicolor
```

**Comment by dusansimic** [comment] 2020-11-28 12:40
This issue is fixed now since icons of all sizes are included into the build. Just download the latest version of Caprine to have this fix.

**Closed by dusansimic** 2020-11-28 12:40 UTC
