### ISSUE TITLE
can't move Caprine window on OSX Mojave

### ISSUE THREAD

**Issue by karltate** [sindresorhus/caprine#1509] opened 2020-12-23 19:20 UTC
Hi, versions prior to this one worked fine, but I can't grab the title bar of the window on this latest version. No way to move the window. I can resize it and "walk" it around the screen that way, but not properly move it.

---

Caprine 2.51.1
Electron 10.1.5
darwin 18.2.0
Locale: en-US

**Comment by dusansimic** [comment] 2020-12-24 09:11
Duplicate of #1488

**Closed by dusansimic** 2020-12-24 09:11 UTC
