### ISSUE TITLE
Blank screen when using voice/video call feature !

### ISSUE THREAD

**Issue by DucKhaiTong** [sindresorhus/caprine#1304] opened 2020-03-15 17:47 UTC
---

Caprine 2.44.0
Electron 8.0.0
linux 5.3.0-40-generic
Locale: en-US

**Comment by radekjuthner** [comment] 2020-03-26 18:06
I have the same problem, Caprine 2.44.0

**Comment by 1nikolas** [comment] 2020-03-30 14:16
duplicate of #1189

**Closed** 2020-03-30 14:18 UTC
