### ISSUE TITLE
Caprine blocking shortcuts on Ubuntu/Linux since 2.6.0

### ISSUE THREAD

**Issue by hakur0** [sindresorhus/caprine#266] opened 2017-08-01 20:31 UTC
This bug was introduced on 2.4.0, but was fixed on 2.5.0. It's back on 2.6.0, and I'm using 2.5.0 again for now. Caprine blocks some keys and shortcuts when "minimized" on tray, like F5, F12 and Ctrl + Shift + C.

Sadly, I don't have time to learn how to build and try to fix this, but if it helps, I'm afraid it have something to do with electron-localshortcut and [this update](https://github.com/sindresorhus/caprine/compare/v2.5.0...v2.6.0#diff-168726dbe96b3ce427e7fedce31bb0bc).

**Comment by aude** [comment] 2017-08-03 11:20
This seems to be related to #258

**Comment by sindresorhus** [comment] 2017-08-05 12:24
Duplicate of #258

**Closed by sindresorhus** 2017-08-05 12:24 UTC
Labels: bug
