### ISSUE TITLE
Cannot loading media 

### ISSUE THREAD

**Issue by Kritiqual** [sindresorhus/caprine#1745] opened 2021-12-03 05:27 UTC
When I clicked on some picture or videos I received, the screen turn black, and not thing is shown

**Comment by spinalgr1990** [comment] 2021-12-03 07:18
that happens to me also ...

**Comment by ictnmd** [comment] 2021-12-03 12:23
Me too

**Comment by mattnoir** [comment] 2021-12-03 22:06
same here. When I try to reload with ctrl+r, it shows the picture, but with no option to close it, only to click on messenger logo to return back. Only started happening this evening

**Comment by mirenradia** [comment] 2021-12-06 16:41
I think this is a duplicate of #1751 which provides a bit more information.

**Comment by dusansimic** [comment] 2021-12-07 08:36
Duplicate of #1751

**Closed by dusansimic** 2021-12-07 08:36 UTC
