### ISSUE TITLE
The About dialog produces a JS error

### ISSUE THREAD

**Issue by mmatyas** [sindresorhus/caprine#1308] opened 2020-03-19 14:30 UTC
Clicking *Help -> About Caprine* produces the following error message:

![image](https://user-images.githubusercontent.com/4354863/77077648-cae30100-69f5-11ea-9254-b74d4a3ac40d.png)

I'm using v2.44.0 on Ubuntu 18.04, installed from the DEB package.

**Comment by sindresorhus** [comment] 2020-03-21 15:48
Caused by https://github.com/sindresorhus/electron-util/issues/19.

**Comment by wereii** [comment] 2020-04-10 19:02
Going thru Electron's code of that [`aboutPanel`](https://github.com/electron/electron/blob/b724fbc0ed816828ece7bdcfb10583123c56e78c/shell/browser/browser_linux.cc#L203) (for linux), it does not really seem there is any logic for reading the image from asar files, it goes straight to `gdk_pixbuf_new_from_file_at_size` (let's say, reading a image file:) ).

So the `iconPath` option in has to be a direct path to file.

**Comment by wereii** [comment] 2020-04-10 22:13
Base idea is to move the `Icon.png` out of `app.asar`.

Solutions:
- `asarUnpack` - ~moves~ copies (the file will be in both `.unpacked` dir and `app.asar`) selected files into `app.asar.unpacked`, path module should resolve paths to the file in this directory, not in `app.asar` file - **does not  work**.
  - Works only in conjuction with aditional module `hazardous` - 3 years old, but works everywhere.
  - Increases size (the file is in two locations).

- `extraResources` - places selected file directly into `resources/` folder, files there aren't getting packed into `app.asar`.
  - Breaks development, direct `path.process.resourcesPath` is then used as base path, instead of joining `__dirname` and relative path to that.
  - We can work even with the above with few ifs (`!is.development` mainly).
  - Does not add additional modules:)

<details>
<summary></summary>
First issue about using asar paths and the problems around them is from 11th May 2016.

`https://github.com/electron-userland/electron-builder/issues/390`
`https://github.com/electron/electron/issues/6262`
`https://github.com/electron-userland/electron-builder/issues/1120`

And one still needs an external module to solve it's discrepancies, someone in electron basically agreed that instead of fixing/making it usable they will let others make a module for it, and then why not just use the code in that module to fix the problems in a first place?

I really wonder how much lifeticks have problems with asar already eaten. (As, don't even expect official docs to specify anything like this.)

</details>

**Closed** 2021-07-29 09:48 UTC
Labels: bug, help wanted
