### ISSUE TITLE
Alt+Tab opens "File" menu.

### ISSUE THREAD

**Issue by orestarod** [sindresorhus/caprine#454] opened 2018-05-15 11:57 UTC
I am using Caprine on Manjaro Cinnamon edition from AUR.
I have two languages that I use, changing between them by pressing Alt+Shift.
Whenever I do that while using Caprine, as in writing on a chat and wishing to write the next sentence, word etc in the other langugage, pressing Alt+Shift results, apart from changing input language, in opening the "File" menu of Caprine, and it must be closed to transfer the focus on the chat again and allow me to keep writing.

**Comment by MarosPlsik** [comment] 2018-05-25 21:17
I have the same issue on my Linux Mint 18.3 with Cinnamon, except I am changing the keyboard language with Alt+Shift. I think, though, the issue is related to Electron, not the Caprine itself.
My solution for the time being is to use Alt+Shift in reverse order (first Shift, then Alt). Took me a while to get used to it, but it's fine now.

**Comment by orestarod** [comment] 2018-06-19 12:11
Yes right, I wrote that wrong. I change language with Alt+Shift too. Changing the original comment.

**Comment by dusansimic** [comment] 2020-11-05 16:03
I can't replicate this issue. Now the files are being attached using `Ctrl+T` so this should be fixed.

**Closed by dusansimic** 2020-11-05 16:03 UTC
