### ISSUE TITLE
Missing location icon

### ISSUE THREAD

**Issue by luanmuniz** [sindresorhus/caprine#215] opened 2017-05-22 17:40 UTC
When facebook ask for a location, it sends a button, but the icon is missing.

See screenshot.
![screen shot 2017-05-22 at 14 39 29](https://cloud.githubusercontent.com/assets/3428149/26321277/8bddefe6-3efc-11e7-8255-8a4cb826eeed.png)

Caprine 2.3.1
Electron 1.6.7
darwin x64 16.5.0

**Comment by veniversum** [comment] 2017-05-23 02:52
Seems like an issue with the static resources not being on `messenger.com`. Do you get the missing icon on Messenger in a web browser as well?

**Comment by luanmuniz** [comment] 2017-05-23 04:35
No, just inside Caprine

**Comment by veniversum** [comment] 2017-05-23 17:33
It shouldn't work on web browser either, since the resource at `https://www.messenger.com/images/messenger_commerce/location_action.png` can't be found. 

This is caused by relative urls in react components reused from Facebook's built in messenger, the resources are only on the `facebook.com` host, and not `messenger.com`.

@sindresorhus Should we do anything about this, and the other icon loading issues? Or just wait for a fix on FB's end?

**Comment by sindresorhus** [comment] 2017-05-23 19:03
If it's broken on messenger.com too, we can just wait for them to fix it.

**Comment by luanmuniz** [comment] 2017-05-24 01:48
Just tested. It is broken on `messenger.com`!

**Comment by veniversum** [comment] 2017-06-25 12:15
Seems to be fixed on `messenger.com` as of now.

**Closed by veniversum** 2017-06-25 12:15 UTC
