### ISSUE TITLE
Caprine Freezes

### ISSUE THREAD

**Issue by davidian-sk** [sindresorhus/caprine#2053] opened 2023-08-20 12:59 UTC
On both of my Windows 11 machines (Pro & Enterprise) the Caprine Window freezes, and I am not able to reply to any message anymore, nor switch to another chat. I am still able to minimize and then toggle the window back, but still in the beforementioned state. When I restart the app, I can write a couple of messages, and then it freezes again. Etc.
---

Caprine 2.58.0
Electron 24.1.3
win32 10.0.22621
Locale: en-US

**Comment by kacnje** [comment] 2023-08-23 04:50
I have the similar problem (once or twice a day).

**Comment by jallphin** [comment] 2023-08-25 19:39
Can confirm this same behavior on Linux - Fedora 38 Kinoite flat-pak (on Flathub). Caprine window randomly freezes, no input, no updates and requires a hard restart of the application.

**Comment by stonefrango** [comment] 2023-08-28 00:56
Same behavior on Windows 11 (64-bit), 2.58.0. Perhaps something caused this on Facebook's side?

**Comment by stonefrango** [comment] 2023-08-28 00:57
Looks to be the same issue also as #2052

**Comment by VonAdder** [comment] 2023-08-28 12:30
Same issue here. Windows 11. Funnily enough it started happening around the same time as the 'official' windows messenger app started crashing. The faulting module there is Windows.UI.Xaml.dll.

**Comment by vanastasis** [comment] 2023-08-30 10:58
Same here

Caprine 2.58.0
Electron 24.1.3
linux 6.4.0-kali3-amd64
Locale: en-GB

**Comment by neutronJK** [comment] 2023-08-31 13:43
Me too.
Caprine 2.5.8 (installed via Snap)
Ubuntu 22.04LTS (kernel 5.15-0.82)

**Comment by cobra3282000** [comment] 2023-09-01 00:30
i am having the same basic issue 

linux mint 21.2 mate.

**Comment by andrewmeyer** [comment] 2023-09-01 16:55
can confirm on 0.58.0
OS: Linux Mint 21.1 x86_64

rolling back to 0.57.4 fixed the issue it looks like

**Comment by pahosler** [comment] 2023-09-06 22:49
I've had this issue for months now thru several versions of caprine on Fedora 38. I've tried rpm, flatpak, and appimage, all crash when a new message is received. Currently using version 2.58.1

**Comment by searinminecraft** [comment] 2023-09-10 05:42
I'm having the same issue here on Windows 11. I'm chatting with my best friend, and when she chats the entire Caprine window freezes. Can still minimize and all of that but cannot use the context menu. I'm forced to kill it via the tray icon. Very very annoying... I haven't tested if this issue occurs on Linux. I have Caprine installed (Flatpak) on my Fedora 38 partition so I can test if the issue occurs there as well.

My theory is that this has something to do with push notifications? I'm not sure...

**Comment by pahosler** [comment] 2023-09-10 08:57
> I've had this issue for months now thru several versions of caprine on Fedora 38. I've tried rpm, flatpak, and appimage, all crash when a new message is received. Currently using version 2.58.1 and app still has the same issue.

after a recent update for fedora 38, caprine is magically working again. I'm using the rpm version of caprine.

**Comment by pahosler** [comment] 2023-09-10 09:01
> > I've had this issue for months now thru several versions of caprine on Fedora 38. I've tried rpm, flatpak, and appimage, all crash when a new message is received. Currently using version 2.58.1 and app still has the same issue.
> 
> after a recent update for fedora 38, caprine is magically working again. I'm using the rpm version of caprine. I wish I knew what part of the update fixed it. Now I just cross fingers and hope it keeps working for a while.

oh... it seems I was able to revert to 2.57.0, I thought attempt had failed. 

so, this is why it's "magically" working again.

**Comment by davidian-sk** [comment] 2023-09-10 15:17
updated to 2.58.1 = issue stiill perists

**Comment by procule** [comment] 2023-09-10 21:30
> updated to 2.58.1 = issue still perists

Confirmed for me too. With or without hardware acceleration.

I get this in the console:

```shell
(node:83141) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'checked')
    at /tmp/.mount_caprint6bxXw/resources/app.asar/dist-js/browser.js:208:34
    at async EventEmitter.listener (/tmp/.mount_caprint6bxXw/resources/app.asar/node_modules/electron-better-ipc/source/renderer.js:46:34)
(Use `caprine --trace-warnings ...` to show where the warning was created)
(node:83141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```

**Comment by Bastigonzales** [comment] 2023-09-11 13:06
Same issue with the latest update 2.58.1 on Windows 11.

**Comment by Ptaski** [comment] 2023-09-11 17:11
Same here, I just downloaded the app, used it for a week without issues, and now it started freezing after opening the app for some time.
Linux Pop!_OS 22.04 LTS

**Comment by dusansimic** [comment] 2023-09-12 15:02
Thanks everyone for reporting the issue but commenting that you have the same issue all the time won't help. Use reaction emojis to let other people know you have the same issue. If you have some useful information that hasn't been already posted, feel free to comment.

**Comment by cobra3282000** [comment] 2023-09-12 16:45
i have noticed something interesting, the issue has disappeared with version 2.58.0, but 2.58.1 its back if that makes any sense.

**Comment by FlooferLand** [comment] 2023-09-14 23:33
It appears to consistently freeze every time someone sends me a message in my case _(v2.58.1)_
Can confirm it doesn't happen in v2.58.0, and it happens regardless of hardware acceleration settings.

**Comment by carneeki** [comment] 2023-09-15 06:06
> It appears to consistently freeze every time someone sends me a message in my case _(v2.58.1)_ Can confirm it doesn't happen in v2.58.0, and it happens regardless of hardware acceleration settings.

Can confirm this is the same case for me. It is as soon as a message is received, but reactions do not cause a freeze.

System details: Arch Linux (kernel Linux 6.4.12 Zen1.1), Wayland + GNOME 44.4).

**Comment by sgtcoder** [comment] 2023-09-15 16:39
Still happening for me for a few months. Any resolution here? It cooks my CPU to 70C

```
Debian GNU/Linux 12 (bookworm)
6.1.53-x64v4-xanmod1
```

**Comment by goddva** [comment] 2023-09-16 08:20
I did have the same issue (on Arch - Linux), but it did resolve if I removed the [`:has([role=grid])`](https://github.com/sindresorhus/caprine/blob/v2.58.1/source/browser/conversation-list.ts) from a query selector. I did play around to see why, but did not understand why it happened.

If you are using Linux, you could try to remove the same thing in your installation, to see if that solves your issue.

Find your installation path, and remove it from the file: `dist-js/browser/conversation-list.js` and line 183

Or by this one-liner; 
```shell
sudo sed -i.backup 's/:has(\[role=grid\])//' /usr/lib/caprine/dist-js/browser/conversation-list.js
```

**Comment by kacnje** [comment] 2023-09-16 14:37
I can't find a mentioned .js file. 
Installed on Linux Mint (Flatpak). Some files can be found in `/var/lib/flatpak/app`. Is this the right path to look into?

**Comment by goddva** [comment] 2023-09-16 15:28
> I can't find a mentioned .js file. Installed on Linux Mint (Flatpak). Some files can be found in `/var/lib/flatpak/app`. Is this the right path to look into?

I'm not sure, seems that it's not shipped the same way as the arch package :/

**Comment by maxoku** [comment] 2023-09-17 10:21
I've updated to v2.58.1 because the badges supposed to be fix and tested it. It freezes every time someone send me a message. After restart the badges are visible, so I guess that was fixed, but maybe they also cause the freeze. Another thing as the window can be normally closed, there is still 1 process working in the background draining 1/3 of CPU.

**Comment by dusansimic** [comment] 2023-09-17 11:00
@stkrknds this seems to be caused by the fix for tray indicator. Could you take a look?

**Comment by stkrknds** [comment] 2023-09-17 12:23
@dusansimic This change is actually not needed for the tray icon, since its observer monitors specifically the left sidebar. We could just remove it for now, but will be needed for the notifications workaround later. I'm confused because I read that there were crashes with the previous version as well. 
@goddva Did 2.58 work without crashes for you?

**Comment by sgtcoder** [comment] 2023-09-17 12:26
Let me know if you need anything from me. Or what kind of logs.

For me the app freezes once a few notifications come in. Then spiking the CPU load.

**Comment by stkrknds** [comment] 2023-09-17 12:35
> Let me know if you need anything from me. Or what kind of logs.
Run caprine using the terminal and If you see anything other than what was reported above, send it.
> For me the app freezes once a few notifications come in. Then spiking the CPU load.
What do you mean by notifications(messages?)? Did this happen on 2.58?

**Comment by sgtcoder** [comment] 2023-09-17 12:48
Like when you receive a message.

I will have to check, but been happening for awhile. Was told it's something with electron:

https://github.com/sindresorhus/caprine/issues/1051

**Comment by goddva** [comment] 2023-09-17 13:59
@stkrknds Ok, so I found the bug. There is a [while loop](https://github.com/sindresorhus/caprine/blob/v2.58.1/source/browser/conversation-list.ts#L179-L181) that gets stuck with the value null. This does explain the CPU usage and the hang.

I tested it by using main branch, with this change only:
```ts
diff --git a/source/browser/conversation-list.ts b/source/browser/conversation-list.ts
index 935ed61..e2a10ee 100644
--- a/source/browser/conversation-list.ts
+++ b/source/browser/conversation-list.ts
@@ -178,6 +178,7 @@ function countUnread(mutationsList: MutationRecord[]): void {
                // Find the parent element with the message preview and sender
                while (curr?.className !== 'rq0escxv l9j0dhe7 du4w35lb j83agx80 pfnyh3mw i1fnvgqd bp9cbjyn owycx6da btwxx1t3') {
                        curr = curr?.parentElement ?? null;
+                       if (curr === null) return;
                }

                // Get the image data URI from the parent of the author/text

```

... and then everything was working fine.

**Comment by stkrknds** [comment] 2023-09-17 14:30
@goddva Makes sense, this is what probably is causing this.  Thank you, that's helpful. The best than can be done for now I think is to remove countUnread and the observer completely and see if it solves this issue for everyone.
```diff
diff --git a/source/browser/conversation-list.ts b/source/browser/conversation-list.ts
index 935ed61..9e7527c 100644
--- a/source/browser/conversation-list.ts
+++ b/source/browser/conversation-list.ts
@@ -169,50 +169,6 @@ export async function sendConversationList(): Promise<void> {
 	ipc.callMain('conversations', conversationsToRender);
 }
 
-function countUnread(mutationsList: MutationRecord[]): void {
-	// Look through the mutations for the one with the unread dot
-	const unreadMutations = mutationsList.filter(mutation => mutation.type === 'childList' && mutation.addedNodes.length > 0 && ((mutation.addedNodes[0] as Element).getAttribute('aria-label') === 'Mark as read'));
-
-	for (const mutation of unreadMutations) {
-		let curr = (mutation.addedNodes[0] as Element).parentElement;
-		// Find the parent element with the message preview and sender
-		while (curr?.className !== 'rq0escxv l9j0dhe7 du4w35lb j83agx80 pfnyh3mw i1fnvgqd bp9cbjyn owycx6da btwxx1t3') {
-			curr = curr?.parentElement ?? null;
-		}
-
-		// Get the image data URI from the parent of the author/text
-		const imgUrl = curr.parentElement?.getElementsByTagName('img')[0].dataset.caprineIcon;
-		// Get the author and text of the new message
-		// const titleText = curr.querySelectorAll('.d2edcug0.hpfvmrgz.qv66sw1b.c1et5uql.b0tq1wua.jq4qci2q.a3bd9o3v.lrazzd5p.oo9gr5id')[0].textContent;
-		let titleTextOptions = curr.querySelectorAll('.a8c37x1j.d2edcug0.ni8dbmo4.ltmttdrg.g0qnabr5');
-		if (titleTextOptions.length === 0) {
-			titleTextOptions = curr.querySelectorAll('.a8c37x1j.ni8dbmo4.stjgntxs.l9j0dhe7.ltmttdrg.g0qnabr5');
-		}
-
-		const titleText = titleTextOptions[0].textContent;
-		let bodyTextOptions = curr.querySelectorAll('.a8c37x1j.ni8dbmo4.stjgntxs.l9j0dhe7.ltmttdrg.g0qnabr5');
-		if (bodyTextOptions.length === 0) {
-			bodyTextOptions = curr.querySelectorAll('.a8c37x1j.d2edcug0.ni8dbmo4.ltmttdrg.g0qnabr5');
-		}
-
-		let loc = 0;
-		if (bodyTextOptions.length >= 2) {
-			loc = 1;
-		}
-
-		const bodyText = bodyTextOptions[loc].textContent;
-
-		// Send a notification
-		ipc.callMain('notification', {
-			id: 0,
-			title: titleText,
-			body: bodyText,
-			icon: imgUrl,
-			silent: false,
-		});
-	}
-}
-
 async function updateTrayIcon(): Promise<void> {
 	const chatsIcon = await elementReady(selectors.chatsIcon, {
 		stopOnDomReady: false,
@@ -229,7 +185,6 @@ window.addEventListener('load', async () => {
 
 	if (sidebar) {
 		const conversationListObserver = new MutationObserver(async () => sendConversationList());
-		const conversationCountObserver = new MutationObserver(countUnread);
 
 		conversationListObserver.observe(sidebar, {
 			subtree: true,
@@ -237,13 +192,6 @@ window.addEventListener('load', async () => {
 			attributes: true,
 			attributeFilter: ['class'],
 		});
-
-		conversationCountObserver.observe(sidebar, {
-			subtree: true,
-			childList: true,
-			attributes: true,
-			attributeFilter: ['class'],
-		});
 	}
 
 	if (leftSidebar) {
```
I'm currently working on rewriting this (in #2051) hopefully making work again.

**Comment by sgtcoder** [comment] 2023-09-17 20:07
Thank you! Squashing this long standing but would be incredible. Definitely cooks up the high performance i9 processors.

Let me know if you need any testing.

**Comment by dusansimic** [comment] 2023-09-25 21:35
@stkrknds, could you send a pr for this if the patch in your comment solves the issue? I'd like to push it together with the fix for notifications workaround in the next release.

**Comment by dusansimic** [comment] 2023-09-27 01:19
We've pushed an update (2.59.0) which should have this issue fixed. Please let us know!

**Comment by sgtcoder** [comment] 2023-09-27 01:24
I got the update. I will monitor it and let you know.

Thank you!!

**Comment by devCKVargas** [comment] 2023-09-27 08:27
Notification finally works and no freezing so far! **Thank you!**

**Comment by sgtcoder** [comment] 2023-09-28 01:42
Everything is working. Notifications, systray icon. No freezing or locking up. This is great!

**Comment by dusansimic** [comment] 2023-09-29 08:47
Thanks everyone for reporting the issue and the feedback! Closing this now.

**Closed by dusansimic** 2023-09-29 08:47 UTC
