### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by nalexeyev** [sindresorhus/caprine#1214] opened 2019-12-11 10:04 UTC
https://github.com/sindresorhus/caprine/issues/22#issuecomment-435273012

It is needed to get FB from office.
Just add solution proposed in comments

**Comment by sindresorhus** [comment] 2019-12-11 12:16
Duplicate of #22

**Comment by sindresorhus** [comment] 2019-12-11 12:16
I'm not interested in adding any config for this. Caprine is based on Electron which is based on Chrome, which should read the system proxy setting.

**Closed by sindresorhus** 2019-12-11 12:16 UTC

**Comment by taro-ball** [comment] 2020-08-13 01:09
> I'm not interested in adding any config for this. Caprine is based on Electron which is based on Chrome, which should read the system proxy setting.

But it doesn't  read the system settings. My chrome works fine, still Caprine shows an "You appear to be offline" message.
